apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kscore-server-data
  namespace: kscore-system
  labels:
    app.kubernetes.io/name: kscore-server
    app.kubernetes.io/component: control-plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
