// SPDX-License-Identifier: Apache-2.0

// gendocs/modules generates the docs-site "State Modules" reference from
// each stdlib module's structured [statemgmt.ModuleDoc] (its Doc method).
// It writes one Markdown page per module plus a grouped _index.md into
// the output directory.
//
// Source of truth is the code: every registered module must implement
// statemgmt.Documented, and each Doc's States must match the module's
// ValidStates() exactly — the generator fails otherwise, so a module
// can't drift from its reference page. Wired into `make docs-sync`;
// `make docs-sync-check` regenerates to a tmp dir and diffs.
//
// Usage:
//
//	go run ./tools/gendocs/modules -out docs/content/docs/modules
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"go.keystone-core.io/keystone-core/internal/statemgmt"
	"go.keystone-core.io/keystone-core/internal/statemgmt/stdlib"
)

// categoryOrder fixes the index ordering (and per-category weight base).
// Mirrors FEATURES.md §8 / STATE-SUPPORT-MATRIX.md grouping. A module
// whose Category is not listed here sorts after all known categories.
var categoryOrder = []string{
	"System & core",
	"Scheduled tasks",
	"Storage",
	"Network (base)",
	"Firewall (base)",
	"SSH & security",
	"System config",
	"Files & VCS",
	"Certificates",
}

type modPage struct {
	name string
	doc  statemgmt.ModuleDoc
}

func main() {
	out := flag.String("out", "docs/content/docs/modules", "output directory for the State Modules reference")
	strict := flag.Bool("strict", true, "require every registered module to implement statemgmt.Documented")
	flag.Parse()
	if err := run(*out, *strict); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs/modules:", err)
		os.Exit(1)
	}
}

func run(out string, strict bool) error {
	reg := statemgmt.NewRegistry()
	if err := stdlib.RegisterAll(reg); err != nil {
		return fmt.Errorf("RegisterAll: %w", err)
	}

	var pages []modPage
	var undocumented []string
	for _, name := range reg.List() {
		mod, err := reg.Get(name)
		if err != nil {
			return fmt.Errorf("Get %q: %w", name, err)
		}
		documented, ok := mod.(statemgmt.Documented)
		if !ok {
			undocumented = append(undocumented, name)
			continue
		}
		doc := documented.Doc()
		if err := checkConsistency(name, doc, mod.ValidStates()); err != nil {
			return err
		}
		pages = append(pages, modPage{name: name, doc: doc})
	}

	if len(undocumented) > 0 {
		msg := fmt.Sprintf("%d module(s) do not implement statemgmt.Documented "+
			"(add a Doc method in a doc.go — see internal/statemgmt/stdlib/file/doc.go): %s",
			len(undocumented), strings.Join(undocumented, ", "))
		if strict {
			return fmt.Errorf("%s", msg)
		}
		fmt.Fprintln(os.Stderr, "gendocs/modules: WARNING —", msg)
	}

	sort.Slice(pages, func(i, j int) bool {
		ci, cj := catIndex(pages[i].doc.Category), catIndex(pages[j].doc.Category)
		if ci != cj {
			return ci < cj
		}
		return pages[i].name < pages[j].name
	})

	if err := resetDir(out); err != nil {
		return err
	}
	for i, p := range pages {
		weight := (catIndex(p.doc.Category)+1)*100 + i
		if err := os.WriteFile(filepath.Join(out, p.name+".md"), []byte(renderPage(p, weight)), 0o644); err != nil {
			return err
		}
	}
	return os.WriteFile(filepath.Join(out, "_index.md"), []byte(renderIndex(pages)), 0o644)
}

// checkConsistency enforces that Doc.States and ValidStates() describe
// the same set — the core in-sync guarantee.
func checkConsistency(name string, doc statemgmt.ModuleDoc, valid []string) error {
	if doc.Category == "" {
		return fmt.Errorf("module %q: Doc.Category is empty", name)
	}
	if strings.TrimSpace(doc.Summary) == "" {
		return fmt.Errorf("module %q: Doc.Summary is empty", name)
	}
	documented := map[string]bool{}
	for _, s := range doc.States {
		documented[s.Name] = true
	}
	validSet := map[string]bool{}
	for _, s := range valid {
		validSet[s] = true
		if !documented[s] {
			return fmt.Errorf("module %q: ValidStates() has %q but Doc.States does not", name, s)
		}
	}
	for _, s := range doc.States {
		if !validSet[s.Name] {
			return fmt.Errorf("module %q: Doc.States has %q but ValidStates() does not", name, s.Name)
		}
	}
	return nil
}

func catIndex(c string) int {
	for i, name := range categoryOrder {
		if name == c {
			return i
		}
	}
	return len(categoryOrder) // unknown categories sort last
}

const genWarning = "<!-- Generated by `make docs-sync` (tools/gendocs/modules) from the module's " +
	"Doc method. Do not edit by hand. -->\n"

func renderPage(p modPage, weight int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: %q\nlinkTitle: %q\nweight: %d\n---\n\n", p.name, p.name, weight)
	b.WriteString(genWarning)
	b.WriteByte('\n')
	fmt.Fprintf(&b, "%s\n\n", p.doc.Summary)
	fmt.Fprintf(&b, "**Category:** %s\n\n", p.doc.Category)

	b.WriteString("## States\n\n| State | Meaning |\n| --- | --- |\n")
	for _, s := range p.doc.States {
		fmt.Fprintf(&b, "| `%s` | %s |\n", s.Name, cell(s.Desc))
	}
	b.WriteByte('\n')

	if len(p.doc.Params) > 0 {
		b.WriteString("## Parameters\n\n| Parameter | Type | Required | Description |\n| --- | --- | --- | --- |\n")
		for _, pr := range p.doc.Params {
			req := ""
			if pr.Required {
				req = "yes"
			}
			desc := cell(pr.Desc)
			if pr.Default != "" {
				desc += fmt.Sprintf(" Default: `%s`.", pr.Default)
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", pr.Name, pr.Type, req, desc)
		}
		b.WriteByte('\n')
	}

	if len(p.doc.Examples) > 0 {
		b.WriteString("## Examples\n\n")
		for _, ex := range p.doc.Examples {
			fmt.Fprintf(&b, "### %s\n\n", ex.Title)
			if ex.Desc != "" {
				fmt.Fprintf(&b, "%s\n\n", ex.Desc)
			}
			fmt.Fprintf(&b, "```yaml\n%s\n```\n\n", strings.TrimRight(ex.YAML, "\n"))
		}
	}

	if len(p.doc.Notes) > 0 {
		b.WriteString("## Notes\n\n")
		for _, n := range p.doc.Notes {
			fmt.Fprintf(&b, "- %s\n", n)
		}
		b.WriteByte('\n')
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderIndex(pages []modPage) string {
	var b strings.Builder
	b.WriteString("---\ntitle: State Modules\nweight: 2\n---\n\n")
	b.WriteString(genWarning)
	b.WriteByte('\n')
	b.WriteString("The state engine applies declarative YAML state files through these " +
		"built-in modules. Each module manages one kind of resource idempotently — " +
		"declare the desired state and the engine converges to it (and reports drift). " +
		"See [Using State Management](../getting-started/) for the state-file language and workflow.\n\n")

	byCat := map[string][]modPage{}
	for _, p := range pages {
		byCat[p.doc.Category] = append(byCat[p.doc.Category], p)
	}
	cats := make([]string, 0, len(byCat))
	for c := range byCat {
		cats = append(cats, c)
	}
	sort.Slice(cats, func(i, j int) bool { return catIndex(cats[i]) < catIndex(cats[j]) })

	for _, c := range cats {
		fmt.Fprintf(&b, "## %s\n\n", c)
		for _, p := range byCat[c] {
			fmt.Fprintf(&b, "- [`%s`](%s/) — %s\n", p.name, p.name, firstSentence(p.doc.Summary))
		}
		b.WriteByte('\n')
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// cell escapes a value for use inside a Markdown table cell.
func cell(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.ReplaceAll(s, "|", "\\|")
}

func firstSentence(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	if i := strings.Index(s, ". "); i >= 0 {
		return s[:i+1]
	}
	return s
}

// resetDir removes any previously generated *.md so pages for removed
// modules don't linger, then recreates the directory.
func resetDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err == nil {
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
				if err := os.Remove(filepath.Join(dir, e.Name())); err != nil {
					return err
				}
			}
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	return os.MkdirAll(dir, 0o755)
}
