apiVersion: v1
kind: Service
metadata:
  name: kscore-telemetry-gateway
  namespace: keystone-core
  labels:
    app.kubernetes.io/name: kscore-telemetry-gateway
    app.kubernetes.io/component: telemetry-gateway
    app.kubernetes.io/part-of: keystone-core
  annotations:
    # For ServiceMonitor discovery
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9091
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: kscore-telemetry-gateway
