apiVersion: v1
kind: ServiceAccount
metadata:
  name: kscore-telemetry-gateway
  namespace: keystone-core
  labels:
    app.kubernetes.io/name: kscore-telemetry-gateway
    app.kubernetes.io/component: telemetry-gateway
    app.kubernetes.io/part-of: keystone-core
