// gendocs/api builds docs/project/API-REFERENCE.md by extracting
// every gRPC service + RPC from `api/proto/keystone/core/v1/*.proto`
// and every REST path + method from `api/openapi/openapi-spec.yaml`.
//
// The output is an index — each entry points back at the canonical
// proto / openapi source for detail (no duplication). Source-of-truth
// stays in the .proto / .yaml files; drift detection: re-run + git
// diff.
//
// Usage:
//
//	go run ./tools/gendocs/api > docs/project/API-REFERENCE.md
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const header = `# API reference

Generated by ` + "`make docs-sync`" + ` from ` + "`tools/gendocs/api`" + `.
Source of truth is ` + "`api/proto/keystone/core/v1/*.proto`" + ` (gRPC) and
` + "`api/openapi/openapi-spec.yaml`" + ` (REST). Do not edit by hand —
` + "`make docs-sync`" + ` re-runs the generator and ` + "`git diff`" + ` will catch drift.

This is an index. For request / response field detail, follow the
` + "`Source`" + ` link to the relevant ` + "`.proto`" + ` block or the openapi spec entry.

`

// rpcLine matches a proto `rpc Name(Req) returns (...)` declaration.
var rpcLine = regexp.MustCompile(`^\s*rpc\s+(\w+)\s*\(([^)]+)\)\s*returns\s*\(([^)]+)\)`)

// serviceLine matches `service Name {`.
var serviceLine = regexp.MustCompile(`^\s*service\s+(\w+)\s*\{`)

type rpcEntry struct {
	Service  string
	Name     string
	Request  string
	Response string
	Source   string // file:line
}

func main() {
	out := &strings.Builder{}
	out.WriteString(header)

	out.WriteString("## gRPC services\n\n")
	rpcs, err := collectProtoRPCs("api/proto/keystone/core/v1")
	if err != nil {
		fmt.Fprintln(os.Stderr, "gendocs/api: proto:", err)
		os.Exit(1)
	}
	// Group by service.
	bySvc := map[string][]rpcEntry{}
	for _, r := range rpcs {
		bySvc[r.Service] = append(bySvc[r.Service], r)
	}
	svcNames := make([]string, 0, len(bySvc))
	for s := range bySvc {
		svcNames = append(svcNames, s)
	}
	sort.Strings(svcNames)
	for _, svc := range svcNames {
		fmt.Fprintf(out, "### %s\n\n", svc)
		out.WriteString("| RPC | Request | Response | Source |\n")
		out.WriteString("|-----|---------|----------|--------|\n")
		entries := bySvc[svc]
		sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })
		for _, e := range entries {
			fmt.Fprintf(out, "| `%s` | `%s` | `%s` | [`%s`](%s) |\n",
				e.Name, e.Request, e.Response, e.Source, sourceLink(e.Source))
		}
		out.WriteString("\n")
	}

	out.WriteString("## REST endpoints\n\n")
	out.WriteString("Source: `api/openapi/openapi-spec.yaml`. Method / path tuples below.\n\n")
	rest, err := collectOpenAPIPaths("api/openapi/openapi-spec.yaml")
	if err != nil {
		fmt.Fprintln(os.Stderr, "gendocs/api: openapi:", err)
		os.Exit(1)
	}
	out.WriteString("| Method | Path | Source |\n")
	out.WriteString("|--------|------|--------|\n")
	for _, r := range rest {
		fmt.Fprintf(out, "| `%s` | `%s` | [`api/openapi/openapi-spec.yaml:%d`](../../api/openapi/openapi-spec.yaml#L%d) |\n",
			r.Method, r.Path, r.Line, r.Line)
	}
	out.WriteString("\n")

	// Trim trailing blank lines — markdownlint MD012.
	body := strings.TrimRight(out.String(), "\n") + "\n"
	if _, err := os.Stdout.WriteString(body); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs/api: write:", err)
		os.Exit(1)
	}
}

func collectProtoRPCs(dir string) ([]rpcEntry, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var out []rpcEntry
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".proto") {
			continue
		}
		path := filepath.Join(dir, e.Name())
		f, err := os.Open(path) //nolint:gosec // proto files in our repo
		if err != nil {
			return nil, err
		}
		var curService string
		ln := 0
		scan := bufio.NewScanner(f)
		for scan.Scan() {
			ln++
			line := scan.Text()
			if m := serviceLine.FindStringSubmatch(line); m != nil {
				curService = m[1]
				continue
			}
			if curService == "" {
				continue
			}
			if strings.Contains(line, "}") {
				curService = ""
				continue
			}
			if m := rpcLine.FindStringSubmatch(line); m != nil {
				out = append(out, rpcEntry{
					Service:  curService,
					Name:     m[1],
					Request:  strings.TrimSpace(m[2]),
					Response: strings.TrimSpace(m[3]),
					Source:   fmt.Sprintf("%s:%d", path, ln),
				})
			}
		}
		_ = f.Close()
		if err := scan.Err(); err != nil {
			return nil, err
		}
	}
	return out, nil
}

type restEntry struct {
	Method string
	Path   string
	Line   int
}

// pathLine matches an openapi path: `  /api/v1/foo:` (2-space indent).
var pathLine = regexp.MustCompile(`^  (/api/[^:]+):\s*$`)

// methodLine matches an openapi method under a path: `    get:`, `    post:`.
var methodLine = regexp.MustCompile(`^    (get|post|put|patch|delete|head|options):\s*$`)

func collectOpenAPIPaths(path string) ([]restEntry, error) {
	f, err := os.Open(path) //nolint:gosec // openapi spec in our repo
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	var (
		out     []restEntry
		curPath string
		ln      int
	)
	scan := bufio.NewScanner(f)
	scan.Buffer(make([]byte, 0, 64<<10), 1<<20)
	for scan.Scan() {
		ln++
		line := scan.Text()
		if m := pathLine.FindStringSubmatch(line); m != nil {
			curPath = m[1]
			continue
		}
		if curPath == "" {
			continue
		}
		if m := methodLine.FindStringSubmatch(line); m != nil {
			out = append(out, restEntry{
				Method: strings.ToUpper(m[1]),
				Path:   curPath,
				Line:   ln,
			})
		}
	}
	return out, scan.Err()
}

// sourceLink builds a relative link from docs/project/ to a proto
// file by line. We render the tail as `../../api/...`.
func sourceLink(srcWithLine string) string {
	colon := strings.LastIndex(srcWithLine, ":")
	if colon < 0 {
		return "../../" + srcWithLine
	}
	file := srcWithLine[:colon]
	line := srcWithLine[colon+1:]
	return fmt.Sprintf("../../%s#L%s", file, line)
}
