ARG VERSION=12
# kics-scan ignore-line - Root user required for systemd test containers
FROM debian:${VERSION}

# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends \
    systemd systemd-sysv \
    curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /lib/systemd/system/sysinit.target.wants/
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN find . -maxdepth 1 -type f ! -name 'systemd-tmpfiles-setup*' -delete

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]
