ARG VERSION=3.20
# kics-scan ignore-line - Root user required for test containers
FROM alpine:${VERSION}

# hadolint ignore=DL3018
RUN apk add --no-cache bash curl ca-certificates libc6-compat gcompat

CMD ["/bin/sh"]
