// Package kms provides HSM/KMS integration for key management operations.
// It supports AWS KMS, Azure Key Vault HSM, and GCP Cloud KMS for secure
// key wrapping, envelope encryption, and key hierarchy management.
package kms

import (
	"context"
	"errors"
	"time"
)

// ProviderType identifies the KMS provider.
type ProviderType string

// ProviderTypeAWS constants define the supported types.
const (
	ProviderTypeAWS        ProviderType = "aws_kms"
	ProviderTypeAzure      ProviderType = "azure_keyvault"
	ProviderTypeGCP        ProviderType = "gcp_cloudkms"
	ProviderTypePKCS11     ProviderType = "pkcs11"
	ProviderTypeThalesLuna ProviderType = "thales_luna"
	ProviderTypeCloudHSM   ProviderType = "aws_cloudhsm"
)

// String returns the string representation of the provider type.
func (p ProviderType) String() string {
	return string(p)
}

// Valid returns true if the provider type is valid.
func (p ProviderType) Valid() bool {
	switch p {
	case ProviderTypeAWS, ProviderTypeAzure, ProviderTypeGCP,
		ProviderTypePKCS11, ProviderTypeThalesLuna, ProviderTypeCloudHSM:
		return true
	default:
		return false
	}
}

// KeyType represents the type of cryptographic key.
type KeyType string

// KeyTypeSymmetric constants define the supported types.
const (
	KeyTypeSymmetric  KeyType = "symmetric"  // AES-256
	KeyTypeAsymmetric KeyType = "asymmetric" // RSA, EC
	KeyTypeDataKey    KeyType = "data_key"   // Generated data encryption key
)

// KeySpec represents the key specification.
type KeySpec string

// KeySpecAES256 constants define the key types.
const (
	KeySpecAES256           KeySpec = "AES_256"
	KeySpecRSA2048          KeySpec = "RSA_2048"
	KeySpecRSA4096          KeySpec = "RSA_4096"
	KeySpecECCNISTP256      KeySpec = "ECC_NIST_P256"
	KeySpecECCNISTP384      KeySpec = "ECC_NIST_P384"
	KeySpecSymmetricDefault KeySpec = "SYMMETRIC_DEFAULT"
)

// KeyUsage represents how a key can be used.
type KeyUsage string

// KeyUsageEncryptDecrypt constants define the key types.
const (
	KeyUsageEncryptDecrypt KeyUsage = "ENCRYPT_DECRYPT"
	KeyUsageSignVerify     KeyUsage = "SIGN_VERIFY"
)

// KeyMetadata contains metadata about a KMS key.
type KeyMetadata struct {
	// KeyID is the unique key identifier.
	KeyID string `json:"key_id"`

	// ARN is the provider-specific resource identifier.
	ARN string `json:"arn,omitempty"`

	// Alias is the key alias/name.
	Alias string `json:"alias,omitempty"`

	// Provider is the KMS provider.
	Provider ProviderType `json:"provider"`

	// KeyType is the type of key.
	KeyType KeyType `json:"key_type"`

	// KeySpec is the key specification.
	KeySpec KeySpec `json:"key_spec"`

	// KeyUsage is the key usage.
	KeyUsage KeyUsage `json:"key_usage"`

	// Enabled indicates if the key is enabled.
	Enabled bool `json:"enabled"`

	// Description is the key description.
	Description string `json:"description,omitempty"`

	// CreatedAt is when the key was created.
	CreatedAt time.Time `json:"created_at"`

	// RotationEnabled indicates if automatic rotation is enabled.
	RotationEnabled bool `json:"rotation_enabled"`

	// NextRotationDate is when the key will be rotated next.
	NextRotationDate time.Time `json:"next_rotation_date,omitempty"`

	// Tags are key-value pairs associated with the key.
	Tags map[string]string `json:"tags,omitempty"`
}

// DataKey represents a data encryption key generated by KMS.
type DataKey struct {
	// Plaintext is the plaintext data key (should be zeroed after use).
	Plaintext []byte `json:"-"`

	// Ciphertext is the encrypted data key (safe to store).
	Ciphertext []byte `json:"ciphertext"`

	// KeyID is the KMS key that encrypted this data key.
	KeyID string `json:"key_id"`

	// Provider is the KMS provider.
	Provider ProviderType `json:"provider"`

	// KeySpec is the data key specification.
	KeySpec KeySpec `json:"key_spec"`

	// GeneratedAt is when the data key was generated.
	GeneratedAt time.Time `json:"generated_at"`
}

// Zero clears the plaintext key from memory.
func (d *DataKey) Zero() {
	for i := range d.Plaintext {
		d.Plaintext[i] = 0
	}
}

// EncryptRequest represents a request to encrypt data.
type EncryptRequest struct {
	// KeyID is the KMS key to use for encryption.
	KeyID string `json:"key_id"`

	// Plaintext is the data to encrypt.
	Plaintext []byte `json:"plaintext"`

	// Context is additional authenticated data (AAD).
	Context map[string]string `json:"context,omitempty"`
}

// EncryptResponse represents the result of an encryption operation.
type EncryptResponse struct {
	// Ciphertext is the encrypted data.
	Ciphertext []byte `json:"ciphertext"`

	// KeyID is the KMS key used for encryption.
	KeyID string `json:"key_id"`

	// KeyVersion is the key version used (if applicable).
	KeyVersion int `json:"key_version,omitempty"`
}

// DecryptRequest represents a request to decrypt data.
type DecryptRequest struct {
	// KeyID is the KMS key to use for decryption (may be optional if embedded in ciphertext).
	KeyID string `json:"key_id,omitempty"`

	// Ciphertext is the data to decrypt.
	Ciphertext []byte `json:"ciphertext"`

	// Context is additional authenticated data (AAD) that must match encryption.
	Context map[string]string `json:"context,omitempty"`
}

// DecryptResponse represents the result of a decryption operation.
type DecryptResponse struct {
	// Plaintext is the decrypted data.
	Plaintext []byte `json:"plaintext"`

	// KeyID is the KMS key used for decryption.
	KeyID string `json:"key_id"`
}

// GenerateDataKeyRequest represents a request to generate a data key.
type GenerateDataKeyRequest struct {
	// KeyID is the KMS key to use for wrapping the data key.
	KeyID string `json:"key_id"`

	// KeySpec is the specification for the generated data key.
	KeySpec KeySpec `json:"key_spec,omitempty"`

	// NumberOfBytes is the length of the data key in bytes (alternative to KeySpec).
	NumberOfBytes int `json:"number_of_bytes,omitempty"`

	// Context is additional authenticated data (AAD).
	Context map[string]string `json:"context,omitempty"`

	// WithoutPlaintext generates only the encrypted data key.
	WithoutPlaintext bool `json:"without_plaintext,omitempty"`
}

// WrapKeyRequest represents a request to wrap (encrypt) a key.
type WrapKeyRequest struct {
	// WrapperKeyID is the KMS key to use for wrapping.
	WrapperKeyID string `json:"wrapper_key_id"`

	// KeyToWrap is the plaintext key to wrap.
	KeyToWrap []byte `json:"key_to_wrap"`

	// Context is additional authenticated data (AAD).
	Context map[string]string `json:"context,omitempty"`
}

// WrapKeyResponse represents the result of a key wrapping operation.
type WrapKeyResponse struct {
	// WrappedKey is the encrypted key.
	WrappedKey []byte `json:"wrapped_key"`

	// WrapperKeyID is the KMS key used for wrapping.
	WrapperKeyID string `json:"wrapper_key_id"`

	// KeyVersion is the wrapper key version used (if applicable).
	KeyVersion int `json:"key_version,omitempty"`
}

// UnwrapKeyRequest represents a request to unwrap (decrypt) a key.
type UnwrapKeyRequest struct {
	// WrapperKeyID is the KMS key to use for unwrapping.
	WrapperKeyID string `json:"wrapper_key_id"`

	// WrappedKey is the encrypted key to unwrap.
	WrappedKey []byte `json:"wrapped_key"`

	// Context is additional authenticated data (AAD) that must match wrapping.
	Context map[string]string `json:"context,omitempty"`
}

// UnwrapKeyResponse represents the result of a key unwrapping operation.
type UnwrapKeyResponse struct {
	// PlaintextKey is the decrypted key.
	PlaintextKey []byte `json:"plaintext_key"`

	// WrapperKeyID is the KMS key used for unwrapping.
	WrapperKeyID string `json:"wrapper_key_id"`
}

// SignRequest represents a request to sign data.
type SignRequest struct {
	// KeyID is the KMS key to use for signing.
	KeyID string `json:"key_id"`

	// Message is the data to sign.
	Message []byte `json:"message"`

	// MessageType indicates if Message is "RAW" or "DIGEST".
	MessageType string `json:"message_type,omitempty"`

	// Algorithm is the signing algorithm.
	Algorithm string `json:"algorithm,omitempty"`
}

// SignResponse represents the result of a signing operation.
type SignResponse struct {
	// Signature is the generated signature.
	Signature []byte `json:"signature"`

	// KeyID is the KMS key used for signing.
	KeyID string `json:"key_id"`

	// Algorithm is the signing algorithm used.
	Algorithm string `json:"algorithm"`
}

// VerifyRequest represents a request to verify a signature.
type VerifyRequest struct {
	// KeyID is the KMS key to use for verification.
	KeyID string `json:"key_id"`

	// Message is the original data.
	Message []byte `json:"message"`

	// Signature is the signature to verify.
	Signature []byte `json:"signature"`

	// MessageType indicates if Message is "RAW" or "DIGEST".
	MessageType string `json:"message_type,omitempty"`

	// Algorithm is the signing algorithm.
	Algorithm string `json:"algorithm,omitempty"`
}

// VerifyResponse represents the result of a verification operation.
type VerifyResponse struct {
	// Valid indicates if the signature is valid.
	Valid bool `json:"valid"`

	// KeyID is the KMS key used for verification.
	KeyID string `json:"key_id"`
}

// Provider defines the interface for KMS providers.
type Provider interface {
	// Type returns the provider type.
	Type() ProviderType

	// Name returns the provider instance name.
	Name() string

	// Healthy checks if the provider is healthy.
	Healthy(ctx context.Context) bool

	// GetKeyMetadata retrieves metadata for a key.
	GetKeyMetadata(ctx context.Context, keyID string) (*KeyMetadata, error)

	// Encrypt encrypts plaintext data.
	Encrypt(ctx context.Context, req *EncryptRequest) (*EncryptResponse, error)

	// Decrypt decrypts ciphertext data.
	Decrypt(ctx context.Context, req *DecryptRequest) (*DecryptResponse, error)

	// GenerateDataKey generates a data encryption key.
	GenerateDataKey(ctx context.Context, req *GenerateDataKeyRequest) (*DataKey, error)

	// WrapKey wraps (encrypts) a key with the KMS key.
	WrapKey(ctx context.Context, req *WrapKeyRequest) (*WrapKeyResponse, error)

	// UnwrapKey unwraps (decrypts) a key with the KMS key.
	UnwrapKey(ctx context.Context, req *UnwrapKeyRequest) (*UnwrapKeyResponse, error)

	// Close closes the provider connection.
	Close() error
}

// SigningProvider extends Provider with signing capabilities.
type SigningProvider interface {
	Provider

	// Sign signs data with the KMS key.
	Sign(ctx context.Context, req *SignRequest) (*SignResponse, error)

	// Verify verifies a signature with the KMS key.
	Verify(ctx context.Context, req *VerifyRequest) (*VerifyResponse, error)
}

// RotatingProvider extends Provider with key rotation capabilities.
type RotatingProvider interface {
	Provider

	// EnableKeyRotation enables automatic key rotation.
	EnableKeyRotation(ctx context.Context, keyID string) error

	// DisableKeyRotation disables automatic key rotation.
	DisableKeyRotation(ctx context.Context, keyID string) error

	// RotateKey manually rotates a key.
	RotateKey(ctx context.Context, keyID string) error

	// ListKeyVersions lists all versions of a key.
	ListKeyVersions(ctx context.Context, keyID string) ([]KeyVersion, error)
}

// KeyVersion represents a version of a KMS key.
type KeyVersion struct {
	// Version is the version number or identifier.
	Version string `json:"version"`

	// CreatedAt is when the version was created.
	CreatedAt time.Time `json:"created_at"`

	// State is the version state (enabled, disabled, destroyed, etc.).
	State string `json:"state"`

	// Primary indicates if this is the primary version.
	Primary bool `json:"primary"`
}

// Common errors for KMS operations.
var (
	// ErrKeyNotFound indicates the requested key was not found.
	ErrKeyNotFound = errors.New("kms key not found")

	// ErrKeyDisabled indicates the key is disabled.
	ErrKeyDisabled = errors.New("kms key is disabled")

	// ErrAccessDenied indicates access to the key was denied.
	ErrAccessDenied = errors.New("kms access denied")

	// ErrEncryptionFailed indicates encryption failed.
	ErrEncryptionFailed = errors.New("kms encryption failed")

	// ErrDecryptionFailed indicates decryption failed.
	ErrDecryptionFailed = errors.New("kms decryption failed")

	// ErrInvalidCiphertext indicates the ciphertext is invalid.
	ErrInvalidCiphertext = errors.New("invalid ciphertext")

	// ErrInvalidKey indicates the key is invalid.
	ErrInvalidKey = errors.New("invalid kms key")

	// ErrProviderUnavailable indicates the KMS provider is unavailable.
	ErrProviderUnavailable = errors.New("kms provider unavailable")

	// ErrUnsupportedOperation indicates the operation is not supported.
	ErrUnsupportedOperation = errors.New("unsupported kms operation")

	// ErrInvalidContext indicates the encryption context is invalid or mismatched.
	ErrInvalidContext = errors.New("invalid encryption context")
)

// ProviderConfig is the base configuration for KMS providers.
type ProviderConfig struct {
	// Name is the provider instance name.
	Name string `json:"name,omitempty"`

	// Type is the provider type.
	Type ProviderType `json:"type"`

	// Timeout is the request timeout.
	Timeout time.Duration `json:"timeout,omitempty"`

	// MaxRetries is the maximum number of retries.
	MaxRetries int `json:"max_retries,omitempty"`
}

// DefaultProviderConfig returns default provider configuration.
func DefaultProviderConfig() *ProviderConfig {
	return &ProviderConfig{
		Name:       "default",
		Timeout:    30 * time.Second,
		MaxRetries: 3,
	}
}
