package natsauth

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/nats-io/jwt/v2"
)

// Deployment artifact names. The broker fixture and compose.yaml both consume
// this directory, so the names are part of the generator's interface rather
// than a test's convention.
const (
	ServerConfigFile = "nats-server.conf"
	CredentialsDir   = "creds"

	configMode      = 0o600
	credentialMode  = 0o600
	directoryMode   = 0o700
	credentialsExt  = ".creds"
	bootstrapPrefix = "bootstrap-"
)

// Write renders the deployment a broker actually runs.
//
// THE OPERATOR SEED IS NEVER WRITTEN. ADR-0002 § 2 holds it outside every
// Keystone process, and the account signing key -- which is the server's -- is
// what lets enrollment mint agent identities without it. GEN-7 reads every byte
// this produces and fails if the seed is among them, so the rule is checked
// rather than asserted here.
func (d *Deployment) Write(dir string) error {
	if err := os.MkdirAll(dir, directoryMode); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}
	credsDir := filepath.Join(dir, CredentialsDir)
	if err := os.MkdirAll(credsDir, directoryMode); err != nil {
		return fmt.Errorf("create %s: %w", credsDir, err)
	}

	for name, identity := range d.credentialSet() {
		content, err := jwt.FormatUserConfig(identity.JWT, identity.Seed)
		if err != nil {
			return fmt.Errorf("format %s credentials: %w", name, err)
		}
		path := filepath.Join(credsDir, name+credentialsExt)
		if err := os.WriteFile(path, content, credentialMode); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}

	// The account signing seed is the server's, per ADR-0002 § 2. It is written
	// beside the credentials because the server needs it to mint agent
	// identities at C05; the operator seed, which would let it mint accounts,
	// is not here.
	signingPath := filepath.Join(credsDir, "account-signing.nk")
	if err := os.WriteFile(signingPath, d.Keystone.SigningSeed, credentialMode); err != nil {
		return fmt.Errorf("write %s: %w", signingPath, err)
	}

	config := d.ServerConfig()
	configPath := filepath.Join(dir, ServerConfigFile)
	if err := os.WriteFile(configPath, []byte(config), configMode); err != nil {
		return fmt.Errorf("write %s: %w", configPath, err)
	}
	return nil
}

// credentialSet names every credential file the deployment holds. Bootstrap
// identities are prefixed so a token can never collide with a service role's
// file name -- the service tokens are valid identifiers, which is the collision
// ADR-0005 § 3 reserves them against.
//
// PERMANENT AGENTS ARE ABSENT, and that is the point. A .creds file carries a
// seed, ADR-0003 § 4 keeps the agent's seed on the agent, and this side has
// none to write. An agent's JWT is not secret and returns to it over the
// enrollment reply subject (ADR-0003 § 4); it is not deployment state here.
func (d *Deployment) credentialSet() map[string]Identity {
	set := map[string]Identity{}
	for p, identity := range d.Services {
		set[string(p)] = identity
	}
	for token, identity := range d.Bootstraps {
		set[bootstrapPrefix+token] = identity
	}
	return set
}

// ServerConfig is the broker configuration this deployment runs. It trusts one
// operator, preloads both account JWTs, and names the system account; no user
// is configured in the file, because every user is a JWT the account signed.
func (d *Deployment) ServerConfig() string {
	var b strings.Builder
	b.WriteString("# Generated by internal/natsauth. ADR-0010 section 3 forbids a\n")
	b.WriteString("# test-only authorization adapter, so this is the configuration a\n")
	b.WriteString("# deployment runs and the one the contract measures.\n")
	b.WriteString("#\n")
	b.WriteString("# No operator seed appears here. The operator JWT below is public.\n\n")
	fmt.Fprintf(&b, "operator: %s\n\n", d.OperatorJWT)
	fmt.Fprintf(&b, "system_account: %s\n\n", d.System.PublicKey)
	b.WriteString("resolver: MEMORY\n\n")
	b.WriteString("resolver_preload: {\n")
	preload := []struct{ key, value string }{
		{d.System.PublicKey, d.System.JWT},
		{d.Keystone.PublicKey, d.Keystone.JWT},
	}
	sort.Slice(preload, func(i, j int) bool { return preload[i].key < preload[j].key })
	for _, entry := range preload {
		fmt.Fprintf(&b, "  %s: %s\n", entry.key, entry.value)
	}
	b.WriteString("}\n\n")
	b.WriteString("jetstream {\n")
	fmt.Fprintf(&b, "  max_memory_store: %d\n", 0)
	fmt.Fprintf(&b, "  max_file_store: %d\n", d.Limits.Account.MaxJetStreamDiskByte)
	b.WriteString("}\n")
	return b.String()
}
