// Package vault provides a HashiCorp Vault backend for the secrets broker.
package vault

import (
	"context"
	"fmt"
	"time"

	"github.com/shawnbutts/keystone-core/internal/secrets"
)

// DatabaseType represents a supported database type.
type DatabaseType string

const (
	DatabaseTypePostgreSQL DatabaseType = "postgresql"
	DatabaseTypeMySQL      DatabaseType = "mysql"
	DatabaseTypeMongoDB    DatabaseType = "mongodb"
	DatabaseTypeMSSQL      DatabaseType = "mssql"
	DatabaseTypeOracle     DatabaseType = "oracle"
	DatabaseTypeRedshift   DatabaseType = "redshift"
	DatabaseTypeCassandra  DatabaseType = "cassandra"
	DatabaseTypeElastic    DatabaseType = "elasticsearch"
	DatabaseTypeSnowflake  DatabaseType = "snowflake"
)

// DatabaseCredentials represents credentials generated by the database secret engine.
type DatabaseCredentials struct {
	// Username is the generated username.
	Username string `json:"username"`

	// Password is the generated password.
	Password string `json:"password"`

	// LeaseID is the Vault lease ID for these credentials.
	LeaseID string `json:"lease_id"`

	// LeaseDuration is how long the credentials are valid.
	LeaseDuration time.Duration `json:"lease_duration"`

	// Renewable indicates if the lease can be renewed.
	Renewable bool `json:"renewable"`

	// Metadata contains additional metadata about the credentials.
	Metadata map[string]string `json:"metadata,omitempty"`
}

// DatabaseConfig configures a database secret engine mount.
type DatabaseConfig struct {
	// MountPath is the mount path for the database engine (default: "database").
	MountPath string `json:"mount_path,omitempty"`

	// DefaultTTL is the default TTL for generated credentials.
	DefaultTTL time.Duration `json:"default_ttl,omitempty"`

	// MaxTTL is the maximum TTL for generated credentials.
	MaxTTL time.Duration `json:"max_ttl,omitempty"`
}

// DatabaseEngine provides methods for working with Vault's database secret engine.
type DatabaseEngine struct {
	client *Client
	config *DatabaseConfig
}

// NewDatabaseEngine creates a new database engine client.
func NewDatabaseEngine(client *Client, config *DatabaseConfig) *DatabaseEngine {
	if config == nil {
		config = &DatabaseConfig{}
	}
	if config.MountPath == "" {
		config.MountPath = "database"
	}
	return &DatabaseEngine{
		client: client,
		config: config,
	}
}

// GenerateCredentials generates database credentials for a role.
func (d *DatabaseEngine) GenerateCredentials(ctx context.Context, role string) (*DatabaseCredentials, error) {
	return d.GenerateCredentialsWithTTL(ctx, role, 0)
}

// GenerateCredentialsWithTTL generates database credentials with a specific TTL.
func (d *DatabaseEngine) GenerateCredentialsWithTTL(ctx context.Context, role string, ttl time.Duration) (*DatabaseCredentials, error) {
	if role == "" {
		return nil, fmt.Errorf("role is required")
	}

	path := fmt.Sprintf("%s/creds/%s", d.config.MountPath, role)

	resp, err := d.client.Read(ctx, path)
	if err != nil {
		return nil, fmt.Errorf("failed to generate credentials: %w", err)
	}

	return d.parseCredentials(resp)
}

// GenerateStaticCredentials retrieves or rotates static credentials for a role.
func (d *DatabaseEngine) GenerateStaticCredentials(ctx context.Context, role string) (*DatabaseCredentials, error) {
	if role == "" {
		return nil, fmt.Errorf("role is required")
	}

	path := fmt.Sprintf("%s/static-creds/%s", d.config.MountPath, role)

	resp, err := d.client.Read(ctx, path)
	if err != nil {
		return nil, fmt.Errorf("failed to get static credentials: %w", err)
	}

	return d.parseCredentials(resp)
}

// RotateStaticCredentials forces rotation of static credentials for a role.
func (d *DatabaseEngine) RotateStaticCredentials(ctx context.Context, role string) error {
	if role == "" {
		return fmt.Errorf("role is required")
	}

	path := fmt.Sprintf("%s/rotate-role/%s", d.config.MountPath, role)

	_, err := d.client.Write(ctx, path, nil)
	if err != nil {
		return fmt.Errorf("failed to rotate credentials: %w", err)
	}

	return nil
}

// RotateRootCredentials rotates the root credentials for a database connection.
func (d *DatabaseEngine) RotateRootCredentials(ctx context.Context, connection string) error {
	if connection == "" {
		return fmt.Errorf("connection name is required")
	}

	path := fmt.Sprintf("%s/rotate-root/%s", d.config.MountPath, connection)

	_, err := d.client.Write(ctx, path, nil)
	if err != nil {
		return fmt.Errorf("failed to rotate root credentials: %w", err)
	}

	return nil
}

// ListRoles lists all configured roles.
func (d *DatabaseEngine) ListRoles(ctx context.Context) ([]string, error) {
	path := fmt.Sprintf("%s/roles", d.config.MountPath)
	return d.client.List(ctx, path)
}

// ListStaticRoles lists all configured static roles.
func (d *DatabaseEngine) ListStaticRoles(ctx context.Context) ([]string, error) {
	path := fmt.Sprintf("%s/static-roles", d.config.MountPath)
	return d.client.List(ctx, path)
}

// ListConnections lists all configured database connections.
func (d *DatabaseEngine) ListConnections(ctx context.Context) ([]string, error) {
	path := fmt.Sprintf("%s/config", d.config.MountPath)
	return d.client.List(ctx, path)
}

// GetRole retrieves configuration for a dynamic role.
func (d *DatabaseEngine) GetRole(ctx context.Context, role string) (*DatabaseRole, error) {
	if role == "" {
		return nil, fmt.Errorf("role is required")
	}

	path := fmt.Sprintf("%s/roles/%s", d.config.MountPath, role)

	resp, err := d.client.Read(ctx, path)
	if err != nil {
		return nil, fmt.Errorf("failed to get role: %w", err)
	}

	return d.parseRole(resp)
}

// DatabaseRole represents a database role configuration.
type DatabaseRole struct {
	// Name is the role name.
	Name string `json:"name"`

	// DBName is the database connection name.
	DBName string `json:"db_name"`

	// DefaultTTL is the default TTL for credentials.
	DefaultTTL time.Duration `json:"default_ttl"`

	// MaxTTL is the maximum TTL for credentials.
	MaxTTL time.Duration `json:"max_ttl"`

	// CreationStatements are SQL statements to create a user.
	CreationStatements []string `json:"creation_statements"`

	// RevocationStatements are SQL statements to revoke a user.
	RevocationStatements []string `json:"revocation_statements"`

	// RenewStatements are SQL statements executed during renewal.
	RenewStatements []string `json:"renew_statements"`

	// RollbackStatements are SQL statements for rollback on failure.
	RollbackStatements []string `json:"rollback_statements"`
}

// parseRole parses a role response.
func (d *DatabaseEngine) parseRole(resp map[string]interface{}) (*DatabaseRole, error) {
	if resp == nil {
		return nil, secrets.ErrSecretNotFound
	}

	data, ok := resp["data"].(map[string]interface{})
	if !ok {
		return nil, fmt.Errorf("invalid role response")
	}

	role := &DatabaseRole{}

	if dbName, ok := data["db_name"].(string); ok {
		role.DBName = dbName
	}
	if dbNames, ok := data["db_name"].([]interface{}); ok && len(dbNames) > 0 {
		if name, ok := dbNames[0].(string); ok {
			role.DBName = name
		}
	}

	if defaultTTL, ok := data["default_ttl"].(float64); ok {
		role.DefaultTTL = time.Duration(defaultTTL) * time.Second
	}

	if maxTTL, ok := data["max_ttl"].(float64); ok {
		role.MaxTTL = time.Duration(maxTTL) * time.Second
	}

	role.CreationStatements = parseStringSlice(data, "creation_statements")
	role.RevocationStatements = parseStringSlice(data, "revocation_statements")
	role.RenewStatements = parseStringSlice(data, "renew_statements")
	role.RollbackStatements = parseStringSlice(data, "rollback_statements")

	return role, nil
}

// parseCredentials parses a credentials response.
func (d *DatabaseEngine) parseCredentials(resp map[string]interface{}) (*DatabaseCredentials, error) {
	if resp == nil {
		return nil, secrets.ErrSecretNotFound
	}

	creds := &DatabaseCredentials{
		Metadata: make(map[string]string),
	}

	// Parse data section
	if data, ok := resp["data"].(map[string]interface{}); ok {
		if username, ok := data["username"].(string); ok {
			creds.Username = username
		}
		if password, ok := data["password"].(string); ok {
			creds.Password = password
		}
	}

	// Parse lease information
	if leaseID, ok := resp["lease_id"].(string); ok {
		creds.LeaseID = leaseID
	}

	if leaseDuration, ok := resp["lease_duration"].(float64); ok {
		creds.LeaseDuration = time.Duration(leaseDuration) * time.Second
	}

	if renewable, ok := resp["renewable"].(bool); ok {
		creds.Renewable = renewable
	}

	return creds, nil
}

// parseStringSlice parses a string slice from a map.
func parseStringSlice(data map[string]interface{}, key string) []string {
	val, ok := data[key]
	if !ok {
		return nil
	}

	switch v := val.(type) {
	case []interface{}:
		result := make([]string, 0, len(v))
		for _, item := range v {
			if s, ok := item.(string); ok {
				result = append(result, s)
			}
		}
		return result
	case []string:
		return v
	default:
		return nil
	}
}

// ToSecret converts DatabaseCredentials to a Secret.
func (c *DatabaseCredentials) ToSecret(path string) *secrets.Secret {
	secret := &secrets.Secret{
		Path:    path,
		Backend: secrets.BackendTypeVault,
		Type:    secrets.SecretTypeDatabase,
		Data: map[string]interface{}{
			"username": c.Username,
			"password": c.Password,
		},
		Metadata:  c.Metadata,
		Renewable: c.Renewable,
	}

	if c.LeaseID != "" {
		secret.Lease = &secrets.Lease{
			ID:         c.LeaseID,
			SecretPath: path,
			Backend:    secrets.BackendTypeVault,
			State:      secrets.LeaseStateActive,
			TTL:        c.LeaseDuration,
			IssuedAt:   time.Now(),
			ExpiresAt:  time.Now().Add(c.LeaseDuration),
			Renewable:  c.Renewable,
			Revocable:  true,
		}
	}

	return secret
}

// PostgreSQLConfig holds PostgreSQL-specific configuration.
type PostgreSQLConfig struct {
	// ConnectionURL is the PostgreSQL connection string.
	// Format: postgresql://{{username}}:{{password}}@host:port/database
	ConnectionURL string `json:"connection_url"`

	// MaxOpenConnections is the maximum number of open connections.
	MaxOpenConnections int `json:"max_open_connections,omitempty"`

	// MaxIdleConnections is the maximum number of idle connections.
	MaxIdleConnections int `json:"max_idle_connections,omitempty"`

	// MaxConnectionLifetime is the maximum connection lifetime.
	MaxConnectionLifetime time.Duration `json:"max_connection_lifetime,omitempty"`

	// Username is the initial admin username.
	Username string `json:"username,omitempty"`

	// Password is the initial admin password.
	Password string `json:"password,omitempty"`

	// UsernameTemplate is the template for generated usernames.
	UsernameTemplate string `json:"username_template,omitempty"`

	// DisableEscaping disables special character escaping.
	DisableEscaping bool `json:"disable_escaping,omitempty"`
}

// MySQLConfig holds MySQL-specific configuration.
type MySQLConfig struct {
	// ConnectionURL is the MySQL connection string.
	// Format: {{username}}:{{password}}@tcp(host:port)/database
	ConnectionURL string `json:"connection_url"`

	// MaxOpenConnections is the maximum number of open connections.
	MaxOpenConnections int `json:"max_open_connections,omitempty"`

	// MaxIdleConnections is the maximum number of idle connections.
	MaxIdleConnections int `json:"max_idle_connections,omitempty"`

	// MaxConnectionLifetime is the maximum connection lifetime.
	MaxConnectionLifetime time.Duration `json:"max_connection_lifetime,omitempty"`

	// Username is the initial admin username.
	Username string `json:"username,omitempty"`

	// Password is the initial admin password.
	Password string `json:"password,omitempty"`

	// UsernameTemplate is the template for generated usernames.
	UsernameTemplate string `json:"username_template,omitempty"`

	// TLSCertificateKey is the PEM-encoded TLS certificate key.
	TLSCertificateKey string `json:"tls_certificate_key,omitempty"`

	// TLSCA is the PEM-encoded CA certificate.
	TLSCA string `json:"tls_ca,omitempty"`
}

// MongoDBConfig holds MongoDB-specific configuration.
type MongoDBConfig struct {
	// ConnectionURL is the MongoDB connection string.
	// Format: mongodb://{{username}}:{{password}}@host:port/database
	ConnectionURL string `json:"connection_url"`

	// WriteConcern specifies the write concern.
	WriteConcern string `json:"write_concern,omitempty"`

	// Username is the initial admin username.
	Username string `json:"username,omitempty"`

	// Password is the initial admin password.
	Password string `json:"password,omitempty"`

	// UsernameTemplate is the template for generated usernames.
	UsernameTemplate string `json:"username_template,omitempty"`

	// TLSCertificateKey is the PEM-encoded TLS certificate key.
	TLSCertificateKey string `json:"tls_certificate_key,omitempty"`

	// TLSCA is the PEM-encoded CA certificate.
	TLSCA string `json:"tls_ca,omitempty"`
}

// ConfigurePostgreSQL configures a PostgreSQL database connection.
func (d *DatabaseEngine) ConfigurePostgreSQL(ctx context.Context, name string, config *PostgreSQLConfig) error {
	if name == "" {
		return fmt.Errorf("connection name is required")
	}
	if config == nil || config.ConnectionURL == "" {
		return fmt.Errorf("connection URL is required")
	}

	path := fmt.Sprintf("%s/config/%s", d.config.MountPath, name)

	data := map[string]interface{}{
		"plugin_name":    "postgresql-database-plugin",
		"connection_url": config.ConnectionURL,
		"allowed_roles":  "*",
	}

	if config.MaxOpenConnections > 0 {
		data["max_open_connections"] = config.MaxOpenConnections
	}
	if config.MaxIdleConnections > 0 {
		data["max_idle_connections"] = config.MaxIdleConnections
	}
	if config.MaxConnectionLifetime > 0 {
		data["max_connection_lifetime"] = config.MaxConnectionLifetime.String()
	}
	if config.Username != "" {
		data["username"] = config.Username
	}
	if config.Password != "" {
		data["password"] = config.Password
	}
	if config.UsernameTemplate != "" {
		data["username_template"] = config.UsernameTemplate
	}
	if config.DisableEscaping {
		data["disable_escaping"] = true
	}

	_, err := d.client.Write(ctx, path, data)
	return err
}

// ConfigureMySQL configures a MySQL database connection.
func (d *DatabaseEngine) ConfigureMySQL(ctx context.Context, name string, config *MySQLConfig) error {
	if name == "" {
		return fmt.Errorf("connection name is required")
	}
	if config == nil || config.ConnectionURL == "" {
		return fmt.Errorf("connection URL is required")
	}

	path := fmt.Sprintf("%s/config/%s", d.config.MountPath, name)

	data := map[string]interface{}{
		"plugin_name":    "mysql-database-plugin",
		"connection_url": config.ConnectionURL,
		"allowed_roles":  "*",
	}

	if config.MaxOpenConnections > 0 {
		data["max_open_connections"] = config.MaxOpenConnections
	}
	if config.MaxIdleConnections > 0 {
		data["max_idle_connections"] = config.MaxIdleConnections
	}
	if config.MaxConnectionLifetime > 0 {
		data["max_connection_lifetime"] = config.MaxConnectionLifetime.String()
	}
	if config.Username != "" {
		data["username"] = config.Username
	}
	if config.Password != "" {
		data["password"] = config.Password
	}
	if config.UsernameTemplate != "" {
		data["username_template"] = config.UsernameTemplate
	}
	if config.TLSCertificateKey != "" {
		data["tls_certificate_key"] = config.TLSCertificateKey
	}
	if config.TLSCA != "" {
		data["tls_ca"] = config.TLSCA
	}

	_, err := d.client.Write(ctx, path, data)
	return err
}

// ConfigureMongoDB configures a MongoDB database connection.
func (d *DatabaseEngine) ConfigureMongoDB(ctx context.Context, name string, config *MongoDBConfig) error {
	if name == "" {
		return fmt.Errorf("connection name is required")
	}
	if config == nil || config.ConnectionURL == "" {
		return fmt.Errorf("connection URL is required")
	}

	path := fmt.Sprintf("%s/config/%s", d.config.MountPath, name)

	data := map[string]interface{}{
		"plugin_name":    "mongodb-database-plugin",
		"connection_url": config.ConnectionURL,
		"allowed_roles":  "*",
	}

	if config.WriteConcern != "" {
		data["write_concern"] = config.WriteConcern
	}
	if config.Username != "" {
		data["username"] = config.Username
	}
	if config.Password != "" {
		data["password"] = config.Password
	}
	if config.UsernameTemplate != "" {
		data["username_template"] = config.UsernameTemplate
	}
	if config.TLSCertificateKey != "" {
		data["tls_certificate_key"] = config.TLSCertificateKey
	}
	if config.TLSCA != "" {
		data["tls_ca"] = config.TLSCA
	}

	_, err := d.client.Write(ctx, path, data)
	return err
}

// CreateRole creates a dynamic database role.
func (d *DatabaseEngine) CreateRole(ctx context.Context, name string, role *DatabaseRole) error {
	if name == "" {
		return fmt.Errorf("role name is required")
	}
	if role == nil || role.DBName == "" {
		return fmt.Errorf("database connection name is required")
	}
	if len(role.CreationStatements) == 0 {
		return fmt.Errorf("creation statements are required")
	}

	path := fmt.Sprintf("%s/roles/%s", d.config.MountPath, name)

	data := map[string]interface{}{
		"db_name":             role.DBName,
		"creation_statements": role.CreationStatements,
	}

	if role.DefaultTTL > 0 {
		data["default_ttl"] = int(role.DefaultTTL.Seconds())
	}
	if role.MaxTTL > 0 {
		data["max_ttl"] = int(role.MaxTTL.Seconds())
	}
	if len(role.RevocationStatements) > 0 {
		data["revocation_statements"] = role.RevocationStatements
	}
	if len(role.RenewStatements) > 0 {
		data["renew_statements"] = role.RenewStatements
	}
	if len(role.RollbackStatements) > 0 {
		data["rollback_statements"] = role.RollbackStatements
	}

	_, err := d.client.Write(ctx, path, data)
	return err
}

// DeleteRole deletes a database role.
func (d *DatabaseEngine) DeleteRole(ctx context.Context, name string) error {
	if name == "" {
		return fmt.Errorf("role name is required")
	}

	path := fmt.Sprintf("%s/roles/%s", d.config.MountPath, name)
	_, err := d.client.Delete(ctx, path)
	return err
}

// DeleteConnection deletes a database connection.
func (d *DatabaseEngine) DeleteConnection(ctx context.Context, name string) error {
	if name == "" {
		return fmt.Errorf("connection name is required")
	}

	path := fmt.Sprintf("%s/config/%s", d.config.MountPath, name)
	_, err := d.client.Delete(ctx, path)
	return err
}
