// SPDX-License-Identifier: Apache-2.0

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func promoDirWithTemplate(t *testing.T, tmpl string) string {
	t.Helper()
	dir := t.TempDir()
	tapes := filepath.Join(dir, "tapes")
	if err := os.MkdirAll(tapes, 0o750); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(tapes, "card.tape.tmpl"), []byte(tmpl), 0o600); err != nil {
		t.Fatalf("write template: %v", err)
	}
	return dir
}

var testFacts = &Facts{
	Version:      "v0.5.0",
	PreRelease:   true,
	ReleaseLabel: "v0.5.0 — pre-release",
	ModuleCount:  35,
	BinaryCount:  20,
	DistroCount:  8,
}

func TestSyncTapes_WritesAndIsIdempotent(t *testing.T) {
	dir := promoDirWithTemplate(t, "Type `{{ .ReleaseLabel }} / {{ .ModuleCount }}`\n")

	res, err := SyncTapes(dir, testFacts, false)
	if err != nil {
		t.Fatalf("SyncTapes: %v", err)
	}
	if len(res.Written) != 1 || res.Written[0] != filepath.Join("tapes", "card.tape") {
		t.Fatalf("Written = %v, want [tapes/card.tape]", res.Written)
	}

	out, err := os.ReadFile(filepath.Join(dir, "tapes", "card.tape"))
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	got := string(out)
	if !strings.Contains(got, "v0.5.0 — pre-release / 35") {
		t.Errorf("rendered tape missing substituted facts:\n%s", got)
	}
	if !strings.HasPrefix(got, "# Code generated by tools/promogen; DO NOT EDIT.") {
		t.Errorf("rendered tape missing generated header:\n%s", got)
	}

	// A second pass must report no drift.
	res, err = SyncTapes(dir, testFacts, false)
	if err != nil {
		t.Fatalf("SyncTapes (second pass): %v", err)
	}
	if len(res.Written) != 0 || len(res.Unchanged) != 1 {
		t.Errorf("second pass Written=%v Unchanged=%v, want none written", res.Written, res.Unchanged)
	}
}

func TestSyncTapes_DryRunDetectsDriftWithoutWriting(t *testing.T) {
	dir := promoDirWithTemplate(t, "Type `{{ .Version }}`\n")
	out := filepath.Join(dir, "tapes", "card.tape")
	if err := os.WriteFile(out, []byte("stale\n"), 0o600); err != nil {
		t.Fatalf("seed stale output: %v", err)
	}

	res, err := SyncTapes(dir, testFacts, true)
	if err != nil {
		t.Fatalf("SyncTapes: %v", err)
	}
	if len(res.Written) != 1 {
		t.Errorf("Written = %v, want the drifted tape reported", res.Written)
	}
	body, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if string(body) != "stale\n" {
		t.Errorf("dry run rewrote the file: %q", body)
	}
}

// A typo'd field must fail the render rather than baking "<no value>"
// into a frame of the finished video.
func TestSyncTapes_UnknownFieldIsAnError(t *testing.T) {
	dir := promoDirWithTemplate(t, "Type `{{ .NoSuchFact }}`\n")
	if _, err := SyncTapes(dir, testFacts, false); err == nil {
		t.Fatal("SyncTapes() = nil error, want an error for an unknown template field")
	}
}

func TestSyncTapes_MalformedTemplate(t *testing.T) {
	dir := promoDirWithTemplate(t, "Type `{{ .Version `\n")
	if _, err := SyncTapes(dir, testFacts, false); err == nil {
		t.Fatal("SyncTapes() = nil error, want a parse error")
	}
}

func TestSyncTapes_NoTemplates(t *testing.T) {
	res, err := SyncTapes(t.TempDir(), testFacts, false)
	if err != nil {
		t.Fatalf("SyncTapes: %v", err)
	}
	if len(res.Written) != 0 || len(res.Unchanged) != 0 {
		t.Errorf("res = %+v, want empty", res)
	}
}

// The committed tapes must match what a sync would produce right now —
// the same contract docs-sync-check enforces for the reference docs.
func TestRepoTapesAreInSync(t *testing.T) {
	repoRoot := filepath.Join("..", "..")
	facts, err := DeriveFacts(repoRoot)
	if err != nil {
		t.Fatalf("DeriveFacts: %v", err)
	}
	res, err := SyncTapes(filepath.Join(repoRoot, defaultPromoDir), facts, true)
	if err != nil {
		t.Fatalf("SyncTapes: %v", err)
	}
	if len(res.Written) != 0 {
		t.Errorf("generated tapes are stale: %v — run `make update-promo`", res.Written)
	}
}
