// SPDX-License-Identifier: Apache-2.0

//go:build linux

package iptables

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

type capture struct {
	bin  string
	args []string
}

func newRecordingProvider(out string, err error) (*linuxProvider, *[]capture) {
	var calls []capture
	run := func(_ context.Context, bin string, args []string) (string, error) {
		calls = append(calls, capture{bin: bin, args: args})
		return out, err
	}
	p := &linuxProvider{
		bin:     map[string]string{FamilyIPv4: "iptables", FamilyIPv6: "ip6tables"},
		saveBin: map[string]string{FamilyIPv4: "iptables-save", FamilyIPv6: "ip6tables-save"},
		run:     run,
	}
	return p, &calls
}

func TestLinuxProvider_HasRule(t *testing.T) {
	t.Parallel()
	// -C exits 0 → rule present
	p, calls := newRecordingProvider("", nil)
	has, err := p.HasRule(context.Background(), FamilyIPv4, "filter", "INPUT", []string{"-p", "tcp", "-j", "ACCEPT"})
	if err != nil || !has {
		t.Fatalf("HasRule(present) = %v,%v", has, err)
	}
	if (*calls)[0].bin != "iptables" || strings.Join((*calls)[0].args, " ") != "-t filter -C INPUT -p tcp -j ACCEPT" {
		t.Errorf("-C args: %+v", (*calls)[0])
	}
	// -C non-zero → rule absent (no error)
	p, _ = newRecordingProvider("", errors.New("exit 1: rule does not exist"))
	has, err = p.HasRule(context.Background(), FamilyIPv4, "filter", "INPUT", []string{"-j", "ACCEPT"})
	if err != nil || has {
		t.Errorf("HasRule(absent) = %v,%v", has, err)
	}
	// ipv6 uses ip6tables; missing binary → ErrNoIptables
	p6 := &linuxProvider{bin: map[string]string{}, saveBin: map[string]string{}, run: func(context.Context, string, []string) (string, error) { return "", nil }}
	if _, err := p6.HasRule(context.Background(), FamilyIPv6, "filter", "INPUT", []string{"-j", "DROP"}); !errors.Is(err, ErrNoIptables) {
		t.Errorf("missing ip6tables → %v", err)
	}
}

func TestLinuxProvider_AddDeleteArgs(t *testing.T) {
	t.Parallel()
	rule := []string{"-p", "tcp", "--dport", "22", "-j", "ACCEPT"}

	// append
	p, calls := newRecordingProvider("", nil)
	if err := p.AddRule(context.Background(), FamilyIPv4, "filter", "INPUT", 0, rule); err != nil {
		t.Fatal(err)
	}
	if strings.Join((*calls)[0].args, " ") != "-t filter -A INPUT -p tcp --dport 22 -j ACCEPT" {
		t.Errorf("append args: %v", (*calls)[0].args)
	}
	// insert at position, ipv6
	p, calls = newRecordingProvider("", nil)
	if err := p.AddRule(context.Background(), FamilyIPv6, "nat", "POSTROUTING", 3, []string{"-o", "eth0", "-j", "MASQUERADE"}); err != nil {
		t.Fatal(err)
	}
	if (*calls)[0].bin != "ip6tables" || strings.Join((*calls)[0].args, " ") != "-t nat -I POSTROUTING 3 -o eth0 -j MASQUERADE" {
		t.Errorf("insert args: %+v", (*calls)[0])
	}
	// delete
	p, calls = newRecordingProvider("", nil)
	if err := p.DeleteRule(context.Background(), FamilyIPv4, "filter", "INPUT", rule); err != nil {
		t.Fatal(err)
	}
	if strings.Join((*calls)[0].args, " ") != "-t filter -D INPUT -p tcp --dport 22 -j ACCEPT" {
		t.Errorf("delete args: %v", (*calls)[0].args)
	}
	// runner error propagates from Add/Delete
	p, _ = newRecordingProvider("", errors.New("iptables: No chain/target/match by that name"))
	if err := p.AddRule(context.Background(), FamilyIPv4, "filter", "INPUT", 0, rule); err == nil {
		t.Error("AddRule should propagate a runner error")
	}
}

func TestLinuxProvider_Save(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, "rules.v4")
	p, calls := newRecordingProvider("# Generated by iptables-save\n*filter\nCOMMIT\n", nil)
	if err := p.Save(context.Background(), FamilyIPv4, path); err != nil {
		t.Fatal(err)
	}
	if (*calls)[0].bin != "iptables-save" {
		t.Errorf("Save used %q", (*calls)[0].bin)
	}
	b, err := os.ReadFile(path)
	if err != nil || !strings.Contains(string(b), "*filter") {
		t.Errorf("save file: %q %v", b, err)
	}
	if fi, _ := os.Stat(path); fi.Mode().Perm() != 0o600 {
		t.Errorf("save file mode = %o, want 0600", fi.Mode().Perm())
	}
	// ipv6 uses ip6tables-save
	p, calls = newRecordingProvider("*filter\nCOMMIT\n", nil)
	if err := p.Save(context.Background(), FamilyIPv6, filepath.Join(dir, "rules.v6")); err != nil {
		t.Fatal(err)
	}
	if (*calls)[0].bin != "ip6tables-save" {
		t.Errorf("Save(ipv6) used %q", (*calls)[0].bin)
	}
	// missing save tool
	p2 := &linuxProvider{bin: map[string]string{FamilyIPv4: "iptables"}, saveBin: map[string]string{}, run: func(context.Context, string, []string) (string, error) { return "", nil }}
	if err := p2.Save(context.Background(), FamilyIPv4, path); !errors.Is(err, ErrNoIptables) {
		t.Errorf("missing iptables-save → %v", err)
	}
	// runner error
	p3, _ := newRecordingProvider("", errors.New("iptables-save: permission denied"))
	if err := p3.Save(context.Background(), FamilyIPv4, path); err == nil {
		t.Error("Save should propagate a runner error")
	}
}

func TestExecRun(t *testing.T) {
	t.Parallel()
	if _, err := execRun(context.Background(), "false", nil); err == nil {
		t.Error("expected an error from `false`")
	}
	if _, err := execRun(context.Background(), "/nonexistent/iptables", nil); err == nil {
		t.Error("expected an error from a missing binary")
	}
	out, err := execRun(context.Background(), "echo", []string{"-n", "ok"})
	if err != nil {
		t.Fatal(err)
	}
	if out != "ok" {
		t.Errorf("echo = %q", out)
	}
}

func TestDefaultProvider_NonNil(t *testing.T) {
	t.Parallel()
	if defaultProvider() == nil {
		t.Fatal("defaultProvider returned nil")
	}
}
