apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keystone-core

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: kscore-registry
  app.kubernetes.io/component: registry
  app.kubernetes.io/part-of: keystone-core
