apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kscore-registry-data
  namespace: keystone-core
  labels:
    app.kubernetes.io/name: kscore-registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: keystone-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment to specify storage class
  # storageClassName: standard
