apiVersion: v1
kind: ServiceAccount
metadata:
  name: kscore-registry
  namespace: keystone-core
  labels:
    app.kubernetes.io/name: kscore-registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: keystone-core
