{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kscore-server.fullname" . }}
  labels:
    {{- include "kscore-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "kscore-server.fullname" $ }}
                port:
                  {{- if eq (.backend | default "http") "grpc" }}
                  name: grpc
                  {{- else }}
                  name: http
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
---
{{- if .Values.grpcIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kscore-server.fullname" . }}-grpc
  labels:
    {{- include "kscore-server.labels" . | nindent 4 }}
  {{- with .Values.grpcIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.grpcIngress.className }}
  ingressClassName: {{ .Values.grpcIngress.className }}
  {{- end }}
  {{- if .Values.grpcIngress.tls }}
  tls:
    {{- range .Values.grpcIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.grpcIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "kscore-server.fullname" $ }}
                port:
                  name: grpc
          {{- end }}
    {{- end }}
{{- end }}
