apiVersion: v1
kind: Service
metadata:
  name: {{ include "kscore-server.fullname" . }}
  labels:
    {{- include "kscore-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
      {{- if and (eq .Values.service.type "NodePort") .Values.service.grpc.nodePort }}
      nodePort: {{ .Values.service.grpc.nodePort }}
      {{- end }}
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.http.nodePort }}
      nodePort: {{ .Values.service.http.nodePort }}
      {{- end }}
    {{- if and (eq .Values.nats.mode "embedded") .Values.service.nats.enabled }}
    - port: {{ .Values.service.nats.port }}
      targetPort: nats
      protocol: TCP
      name: nats
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nats.nodePort }}
      nodePort: {{ .Values.service.nats.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.webhook.enabled }}
    - port: {{ .Values.service.webhook.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
      {{- if and (eq .Values.service.type "NodePort") .Values.service.webhook.nodePort }}
      nodePort: {{ .Values.service.webhook.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "kscore-server.selectorLabels" . | nindent 4 }}
