// BlueprintService — minimal operator-facing blueprint query +
// apply RPCs (Epic 15 task 12). v1.0 ships query (list/get) and
// execute (apply); richer surfaces are post-v1.0.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: keystone/core/v1/blueprint.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlueprintService_ListBlueprints_FullMethodName    = "/keystone.core.v1.BlueprintService/ListBlueprints"
	BlueprintService_GetBlueprint_FullMethodName      = "/keystone.core.v1.BlueprintService/GetBlueprint"
	BlueprintService_ApplyBlueprint_FullMethodName    = "/keystone.core.v1.BlueprintService/ApplyBlueprint"
	BlueprintService_RollbackBlueprint_FullMethodName = "/keystone.core.v1.BlueprintService/RollbackBlueprint"
)

// BlueprintServiceClient is the client API for BlueprintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlueprintServiceClient interface {
	ListBlueprints(ctx context.Context, in *ListBlueprintsRequest, opts ...grpc.CallOption) (*ListBlueprintsResponse, error)
	GetBlueprint(ctx context.Context, in *GetBlueprintRequest, opts ...grpc.CallOption) (*GetBlueprintResponse, error)
	ApplyBlueprint(ctx context.Context, in *ApplyBlueprintRequest, opts ...grpc.CallOption) (*ApplyBlueprintResponse, error)
	RollbackBlueprint(ctx context.Context, in *RollbackBlueprintRequest, opts ...grpc.CallOption) (*RollbackBlueprintResponse, error)
}

type blueprintServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlueprintServiceClient(cc grpc.ClientConnInterface) BlueprintServiceClient {
	return &blueprintServiceClient{cc}
}

func (c *blueprintServiceClient) ListBlueprints(ctx context.Context, in *ListBlueprintsRequest, opts ...grpc.CallOption) (*ListBlueprintsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlueprintsResponse)
	err := c.cc.Invoke(ctx, BlueprintService_ListBlueprints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blueprintServiceClient) GetBlueprint(ctx context.Context, in *GetBlueprintRequest, opts ...grpc.CallOption) (*GetBlueprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlueprintResponse)
	err := c.cc.Invoke(ctx, BlueprintService_GetBlueprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blueprintServiceClient) ApplyBlueprint(ctx context.Context, in *ApplyBlueprintRequest, opts ...grpc.CallOption) (*ApplyBlueprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyBlueprintResponse)
	err := c.cc.Invoke(ctx, BlueprintService_ApplyBlueprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blueprintServiceClient) RollbackBlueprint(ctx context.Context, in *RollbackBlueprintRequest, opts ...grpc.CallOption) (*RollbackBlueprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackBlueprintResponse)
	err := c.cc.Invoke(ctx, BlueprintService_RollbackBlueprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlueprintServiceServer is the server API for BlueprintService service.
// All implementations must embed UnimplementedBlueprintServiceServer
// for forward compatibility.
type BlueprintServiceServer interface {
	ListBlueprints(context.Context, *ListBlueprintsRequest) (*ListBlueprintsResponse, error)
	GetBlueprint(context.Context, *GetBlueprintRequest) (*GetBlueprintResponse, error)
	ApplyBlueprint(context.Context, *ApplyBlueprintRequest) (*ApplyBlueprintResponse, error)
	RollbackBlueprint(context.Context, *RollbackBlueprintRequest) (*RollbackBlueprintResponse, error)
	mustEmbedUnimplementedBlueprintServiceServer()
}

// UnimplementedBlueprintServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlueprintServiceServer struct{}

func (UnimplementedBlueprintServiceServer) ListBlueprints(context.Context, *ListBlueprintsRequest) (*ListBlueprintsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlueprints not implemented")
}
func (UnimplementedBlueprintServiceServer) GetBlueprint(context.Context, *GetBlueprintRequest) (*GetBlueprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlueprint not implemented")
}
func (UnimplementedBlueprintServiceServer) ApplyBlueprint(context.Context, *ApplyBlueprintRequest) (*ApplyBlueprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyBlueprint not implemented")
}
func (UnimplementedBlueprintServiceServer) RollbackBlueprint(context.Context, *RollbackBlueprintRequest) (*RollbackBlueprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackBlueprint not implemented")
}
func (UnimplementedBlueprintServiceServer) mustEmbedUnimplementedBlueprintServiceServer() {}
func (UnimplementedBlueprintServiceServer) testEmbeddedByValue()                          {}

// UnsafeBlueprintServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlueprintServiceServer will
// result in compilation errors.
type UnsafeBlueprintServiceServer interface {
	mustEmbedUnimplementedBlueprintServiceServer()
}

func RegisterBlueprintServiceServer(s grpc.ServiceRegistrar, srv BlueprintServiceServer) {
	// If the following call panics, it indicates UnimplementedBlueprintServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlueprintService_ServiceDesc, srv)
}

func _BlueprintService_ListBlueprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlueprintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueprintServiceServer).ListBlueprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlueprintService_ListBlueprints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueprintServiceServer).ListBlueprints(ctx, req.(*ListBlueprintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlueprintService_GetBlueprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlueprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueprintServiceServer).GetBlueprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlueprintService_GetBlueprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueprintServiceServer).GetBlueprint(ctx, req.(*GetBlueprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlueprintService_ApplyBlueprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyBlueprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueprintServiceServer).ApplyBlueprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlueprintService_ApplyBlueprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueprintServiceServer).ApplyBlueprint(ctx, req.(*ApplyBlueprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlueprintService_RollbackBlueprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackBlueprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueprintServiceServer).RollbackBlueprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlueprintService_RollbackBlueprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueprintServiceServer).RollbackBlueprint(ctx, req.(*RollbackBlueprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlueprintService_ServiceDesc is the grpc.ServiceDesc for BlueprintService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlueprintService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keystone.core.v1.BlueprintService",
	HandlerType: (*BlueprintServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBlueprints",
			Handler:    _BlueprintService_ListBlueprints_Handler,
		},
		{
			MethodName: "GetBlueprint",
			Handler:    _BlueprintService_GetBlueprint_Handler,
		},
		{
			MethodName: "ApplyBlueprint",
			Handler:    _BlueprintService_ApplyBlueprint_Handler,
		},
		{
			MethodName: "RollbackBlueprint",
			Handler:    _BlueprintService_RollbackBlueprint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keystone/core/v1/blueprint.proto",
}
