// BlueprintService — minimal operator-facing blueprint query +
// apply RPCs (Epic 15 task 12). v1.0 ships query (list/get) and
// execute (apply); richer surfaces are post-v1.0.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: keystone/core/v1/blueprint.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlueprintSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    []string               `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"` // parameter names only — values are never exposed
	Features      []string               `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty"`
	Entrypoints   []string               `protobuf:"bytes,6,rep,name=entrypoints,proto3" json:"entrypoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlueprintSummary) Reset() {
	*x = BlueprintSummary{}
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlueprintSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlueprintSummary) ProtoMessage() {}

func (x *BlueprintSummary) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlueprintSummary.ProtoReflect.Descriptor instead.
func (*BlueprintSummary) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_blueprint_proto_rawDescGZIP(), []int{0}
}

func (x *BlueprintSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BlueprintSummary) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BlueprintSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BlueprintSummary) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *BlueprintSummary) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *BlueprintSummary) GetEntrypoints() []string {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

type ApplyReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Changed       int32                  `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyReport) Reset() {
	*x = ApplyReport{}
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyReport) ProtoMessage() {}

func (x *ApplyReport) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyReport.ProtoReflect.Descriptor instead.
func (*ApplyReport) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_blueprint_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyReport) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ApplyReport) GetChanged() int32 {
	if x != nil {
		return x.Changed
	}
	return 0
}

func (x *ApplyReport) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type ListBlueprintsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlueprintsRequest) Reset() {
	*x = ListBlueprintsRequest{}
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlueprintsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlueprintsRequest) ProtoMessage() {}

func (x *ListBlueprintsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlueprintsRequest.ProtoReflect.Descriptor instead.
func (*ListBlueprintsRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_blueprint_proto_rawDescGZIP(), []int{2}
}

type ListBlueprintsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blueprints    []*BlueprintSummary    `protobuf:"bytes,1,rep,name=blueprints,proto3" json:"blueprints,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlueprintsResponse) Reset() {
	*x = ListBlueprintsResponse{}
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlueprintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlueprintsResponse) ProtoMessage() {}

func (x *ListBlueprintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlueprintsResponse.ProtoReflect.Descriptor instead.
func (*ListBlueprintsResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_blueprint_proto_rawDescGZIP(), []int{3}
}

func (x *ListBlueprintsResponse) GetBlueprints() []*BlueprintSummary {
	if x != nil {
		return x.Blueprints
	}
	return nil
}

func (x *ListBlueprintsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetBlueprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlueprintRequest) Reset() {
	*x = GetBlueprintRequest{}
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlueprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlueprintRequest) ProtoMessage() {}

func (x *GetBlueprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlueprintRequest.ProtoReflect.Descriptor instead.
func (*GetBlueprintRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_blueprint_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlueprintRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBlueprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blueprint     *BlueprintSummary      `protobuf:"bytes,1,opt,name=blueprint,proto3" json:"blueprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlueprintResponse) Reset() {
	*x = GetBlueprintResponse{}
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlueprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlueprintResponse) ProtoMessage() {}

func (x *GetBlueprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlueprintResponse.ProtoReflect.Descriptor instead.
func (*GetBlueprintResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_blueprint_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlueprintResponse) GetBlueprint() *BlueprintSummary {
	if x != nil {
		return x.Blueprint
	}
	return nil
}

type ApplyBlueprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enable        []string               `protobuf:"bytes,3,rep,name=enable,proto3" json:"enable,omitempty"`
	Disable       []string               `protobuf:"bytes,4,rep,name=disable,proto3" json:"disable,omitempty"`
	As            string                 `protobuf:"bytes,5,opt,name=as,proto3" json:"as,omitempty"`
	Entrypoint    string                 `protobuf:"bytes,6,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyBlueprintRequest) Reset() {
	*x = ApplyBlueprintRequest{}
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyBlueprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyBlueprintRequest) ProtoMessage() {}

func (x *ApplyBlueprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyBlueprintRequest.ProtoReflect.Descriptor instead.
func (*ApplyBlueprintRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_blueprint_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyBlueprintRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplyBlueprintRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ApplyBlueprintRequest) GetEnable() []string {
	if x != nil {
		return x.Enable
	}
	return nil
}

func (x *ApplyBlueprintRequest) GetDisable() []string {
	if x != nil {
		return x.Disable
	}
	return nil
}

func (x *ApplyBlueprintRequest) GetAs() string {
	if x != nil {
		return x.As
	}
	return ""
}

func (x *ApplyBlueprintRequest) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

type ApplyBlueprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Outputs       map[string]string      `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Report        *ApplyReport           `protobuf:"bytes,4,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyBlueprintResponse) Reset() {
	*x = ApplyBlueprintResponse{}
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyBlueprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyBlueprintResponse) ProtoMessage() {}

func (x *ApplyBlueprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_blueprint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyBlueprintResponse.ProtoReflect.Descriptor instead.
func (*ApplyBlueprintResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_blueprint_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyBlueprintResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ApplyBlueprintResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApplyBlueprintResponse) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ApplyBlueprintResponse) GetReport() *ApplyReport {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_keystone_core_v1_blueprint_proto protoreflect.FileDescriptor

const file_keystone_core_v1_blueprint_proto_rawDesc = "" +
	"\n" +
	" keystone/core/v1/blueprint.proto\x12\x10keystone.core.v1\"\xc0\x01\n" +
	"\x10BlueprintSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x04 \x03(\tR\n" +
	"parameters\x12\x1a\n" +
	"\bfeatures\x18\x05 \x03(\tR\bfeatures\x12 \n" +
	"\ventrypoints\x18\x06 \x03(\tR\ventrypoints\"U\n" +
	"\vApplyReport\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\achanged\x18\x02 \x01(\x05R\achanged\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\"\x17\n" +
	"\x15ListBlueprintsRequest\"}\n" +
	"\x16ListBlueprintsResponse\x12B\n" +
	"\n" +
	"blueprints\x18\x01 \x03(\v2\".keystone.core.v1.BlueprintSummaryR\n" +
	"blueprints\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\")\n" +
	"\x13GetBlueprintRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"X\n" +
	"\x14GetBlueprintResponse\x12@\n" +
	"\tblueprint\x18\x01 \x01(\v2\".keystone.core.v1.BlueprintSummaryR\tblueprint\"\x95\x02\n" +
	"\x15ApplyBlueprintRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12K\n" +
	"\x06params\x18\x02 \x03(\v23.keystone.core.v1.ApplyBlueprintRequest.ParamsEntryR\x06params\x12\x16\n" +
	"\x06enable\x18\x03 \x03(\tR\x06enable\x12\x18\n" +
	"\adisable\x18\x04 \x03(\tR\adisable\x12\x0e\n" +
	"\x02as\x18\x05 \x01(\tR\x02as\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x06 \x01(\tR\n" +
	"entrypoint\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x02\n" +
	"\x16ApplyBlueprintResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12O\n" +
	"\aoutputs\x18\x03 \x03(\v25.keystone.core.v1.ApplyBlueprintResponse.OutputsEntryR\aoutputs\x125\n" +
	"\x06report\x18\x04 \x01(\v2\x1d.keystone.core.v1.ApplyReportR\x06report\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xbb\x02\n" +
	"\x10BlueprintService\x12c\n" +
	"\x0eListBlueprints\x12'.keystone.core.v1.ListBlueprintsRequest\x1a(.keystone.core.v1.ListBlueprintsResponse\x12]\n" +
	"\fGetBlueprint\x12%.keystone.core.v1.GetBlueprintRequest\x1a&.keystone.core.v1.GetBlueprintResponse\x12c\n" +
	"\x0eApplyBlueprint\x12'.keystone.core.v1.ApplyBlueprintRequest\x1a(.keystone.core.v1.ApplyBlueprintResponseB1Z/go.keystone-core.io/keystone-core/pkg/api/v1;v1b\x06proto3"

var (
	file_keystone_core_v1_blueprint_proto_rawDescOnce sync.Once
	file_keystone_core_v1_blueprint_proto_rawDescData []byte
)

func file_keystone_core_v1_blueprint_proto_rawDescGZIP() []byte {
	file_keystone_core_v1_blueprint_proto_rawDescOnce.Do(func() {
		file_keystone_core_v1_blueprint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keystone_core_v1_blueprint_proto_rawDesc), len(file_keystone_core_v1_blueprint_proto_rawDesc)))
	})
	return file_keystone_core_v1_blueprint_proto_rawDescData
}

var file_keystone_core_v1_blueprint_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_keystone_core_v1_blueprint_proto_goTypes = []any{
	(*BlueprintSummary)(nil),       // 0: keystone.core.v1.BlueprintSummary
	(*ApplyReport)(nil),            // 1: keystone.core.v1.ApplyReport
	(*ListBlueprintsRequest)(nil),  // 2: keystone.core.v1.ListBlueprintsRequest
	(*ListBlueprintsResponse)(nil), // 3: keystone.core.v1.ListBlueprintsResponse
	(*GetBlueprintRequest)(nil),    // 4: keystone.core.v1.GetBlueprintRequest
	(*GetBlueprintResponse)(nil),   // 5: keystone.core.v1.GetBlueprintResponse
	(*ApplyBlueprintRequest)(nil),  // 6: keystone.core.v1.ApplyBlueprintRequest
	(*ApplyBlueprintResponse)(nil), // 7: keystone.core.v1.ApplyBlueprintResponse
	nil,                            // 8: keystone.core.v1.ApplyBlueprintRequest.ParamsEntry
	nil,                            // 9: keystone.core.v1.ApplyBlueprintResponse.OutputsEntry
}
var file_keystone_core_v1_blueprint_proto_depIdxs = []int32{
	0, // 0: keystone.core.v1.ListBlueprintsResponse.blueprints:type_name -> keystone.core.v1.BlueprintSummary
	0, // 1: keystone.core.v1.GetBlueprintResponse.blueprint:type_name -> keystone.core.v1.BlueprintSummary
	8, // 2: keystone.core.v1.ApplyBlueprintRequest.params:type_name -> keystone.core.v1.ApplyBlueprintRequest.ParamsEntry
	9, // 3: keystone.core.v1.ApplyBlueprintResponse.outputs:type_name -> keystone.core.v1.ApplyBlueprintResponse.OutputsEntry
	1, // 4: keystone.core.v1.ApplyBlueprintResponse.report:type_name -> keystone.core.v1.ApplyReport
	2, // 5: keystone.core.v1.BlueprintService.ListBlueprints:input_type -> keystone.core.v1.ListBlueprintsRequest
	4, // 6: keystone.core.v1.BlueprintService.GetBlueprint:input_type -> keystone.core.v1.GetBlueprintRequest
	6, // 7: keystone.core.v1.BlueprintService.ApplyBlueprint:input_type -> keystone.core.v1.ApplyBlueprintRequest
	3, // 8: keystone.core.v1.BlueprintService.ListBlueprints:output_type -> keystone.core.v1.ListBlueprintsResponse
	5, // 9: keystone.core.v1.BlueprintService.GetBlueprint:output_type -> keystone.core.v1.GetBlueprintResponse
	7, // 10: keystone.core.v1.BlueprintService.ApplyBlueprint:output_type -> keystone.core.v1.ApplyBlueprintResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_keystone_core_v1_blueprint_proto_init() }
func file_keystone_core_v1_blueprint_proto_init() {
	if File_keystone_core_v1_blueprint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keystone_core_v1_blueprint_proto_rawDesc), len(file_keystone_core_v1_blueprint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keystone_core_v1_blueprint_proto_goTypes,
		DependencyIndexes: file_keystone_core_v1_blueprint_proto_depIdxs,
		MessageInfos:      file_keystone_core_v1_blueprint_proto_msgTypes,
	}.Build()
	File_keystone_core_v1_blueprint_proto = out.File
	file_keystone_core_v1_blueprint_proto_goTypes = nil
	file_keystone_core_v1_blueprint_proto_depIdxs = nil
}
