// ControlPlaneService — operator-facing RPCs (kscorectl, dashboards,
// scripts).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: keystone/core/v1/controlplane.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusRequest) Reset() {
	*x = ServerStatusRequest{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusRequest) ProtoMessage() {}

func (x *ServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusRequest.ProtoReflect.Descriptor instead.
func (*ServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

type ServerStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit          string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	BuildDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ConnectedAgents int32                  `protobuf:"varint,5,opt,name=connected_agents,json=connectedAgents,proto3" json:"connected_agents,omitempty"`
	NatsHealthy     bool                   `protobuf:"varint,6,opt,name=nats_healthy,json=natsHealthy,proto3" json:"nats_healthy,omitempty"`
	StorageHealthy  bool                   `protobuf:"varint,7,opt,name=storage_healthy,json=storageHealthy,proto3" json:"storage_healthy,omitempty"`
	Mode            string                 `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"` // "development" | "production"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerStatusResponse) Reset() {
	*x = ServerStatusResponse{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusResponse) ProtoMessage() {}

func (x *ServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusResponse.ProtoReflect.Descriptor instead.
func (*ServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *ServerStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerStatusResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *ServerStatusResponse) GetBuildDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BuildDate
	}
	return nil
}

func (x *ServerStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ServerStatusResponse) GetConnectedAgents() int32 {
	if x != nil {
		return x.ConnectedAgents
	}
	return 0
}

func (x *ServerStatusResponse) GetNatsHealthy() bool {
	if x != nil {
		return x.NatsHealthy
	}
	return false
}

func (x *ServerStatusResponse) GetStorageHealthy() bool {
	if x != nil {
		return x.StorageHealthy
	}
	return false
}

func (x *ServerStatusResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AgentStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=keystone.core.v1.AgentStatus" json:"status,omitempty"` // UNSPECIFIED = no filter
	LabelKey      string                 `protobuf:"bytes,2,opt,name=label_key,json=labelKey,proto3" json:"label_key,omitempty"`
	LabelValue    string                 `protobuf:"bytes,3,opt,name=label_value,json=labelValue,proto3" json:"label_value,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *ListAgentsRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *ListAgentsRequest) GetLabelKey() string {
	if x != nil {
		return x.LabelKey
	}
	return ""
}

func (x *ListAgentsRequest) GetLabelValue() string {
	if x != nil {
		return x.LabelValue
	}
	return ""
}

func (x *ListAgentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAgentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type ExecuteCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir     string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	User           string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteCommandRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecuteCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteCommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteCommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecuteCommandRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ExecuteCommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecuteCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecuteCommandResponse_CommandId
	//	*ExecuteCommandResponse_Output
	//	*ExecuteCommandResponse_Completion
	Event         isExecuteCommandResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteCommandResponse) GetEvent() isExecuteCommandResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteCommandResponse) GetCommandId() string {
	if x != nil {
		if x, ok := x.Event.(*ExecuteCommandResponse_CommandId); ok {
			return x.CommandId
		}
	}
	return ""
}

func (x *ExecuteCommandResponse) GetOutput() *CommandOutputChunk {
	if x != nil {
		if x, ok := x.Event.(*ExecuteCommandResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ExecuteCommandResponse) GetCompletion() *CommandCompletion {
	if x != nil {
		if x, ok := x.Event.(*ExecuteCommandResponse_Completion); ok {
			return x.Completion
		}
	}
	return nil
}

type isExecuteCommandResponse_Event interface {
	isExecuteCommandResponse_Event()
}

type ExecuteCommandResponse_CommandId struct {
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3,oneof"` // emitted first; identifies the dispatched command
}

type ExecuteCommandResponse_Output struct {
	Output *CommandOutputChunk `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type ExecuteCommandResponse_Completion struct {
	Completion *CommandCompletion `protobuf:"bytes,3,opt,name=completion,proto3,oneof"`
}

func (*ExecuteCommandResponse_CommandId) isExecuteCommandResponse_Event() {}

func (*ExecuteCommandResponse_Output) isExecuteCommandResponse_Event() {}

func (*ExecuteCommandResponse_Completion) isExecuteCommandResponse_Event() {}

type BatchExecuteCommandRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Target            *Target                `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Command           string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args              []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env               map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir        string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	User              string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	TimeoutSeconds    int32                  `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Concurrency       int32                  `protobuf:"varint,8,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	ContinueOnFailure bool                   `protobuf:"varint,9,opt,name=continue_on_failure,json=continueOnFailure,proto3" json:"continue_on_failure,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BatchExecuteCommandRequest) Reset() {
	*x = BatchExecuteCommandRequest{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExecuteCommandRequest) ProtoMessage() {}

func (x *BatchExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*BatchExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *BatchExecuteCommandRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *BatchExecuteCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *BatchExecuteCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *BatchExecuteCommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *BatchExecuteCommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *BatchExecuteCommandRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *BatchExecuteCommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *BatchExecuteCommandRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *BatchExecuteCommandRequest) GetContinueOnFailure() bool {
	if x != nil {
		return x.ContinueOnFailure
	}
	return false
}

type BatchExecuteCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*BatchExecuteCommandResponse_BatchJobId
	//	*BatchExecuteCommandResponse_Lifecycle
	//	*BatchExecuteCommandResponse_Output
	//	*BatchExecuteCommandResponse_Terminal
	Event         isBatchExecuteCommandResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchExecuteCommandResponse) Reset() {
	*x = BatchExecuteCommandResponse{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExecuteCommandResponse) ProtoMessage() {}

func (x *BatchExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*BatchExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *BatchExecuteCommandResponse) GetEvent() isBatchExecuteCommandResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *BatchExecuteCommandResponse) GetBatchJobId() string {
	if x != nil {
		if x, ok := x.Event.(*BatchExecuteCommandResponse_BatchJobId); ok {
			return x.BatchJobId
		}
	}
	return ""
}

func (x *BatchExecuteCommandResponse) GetLifecycle() *BatchAgentLifecycle {
	if x != nil {
		if x, ok := x.Event.(*BatchExecuteCommandResponse_Lifecycle); ok {
			return x.Lifecycle
		}
	}
	return nil
}

func (x *BatchExecuteCommandResponse) GetOutput() *BatchAgentOutput {
	if x != nil {
		if x, ok := x.Event.(*BatchExecuteCommandResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *BatchExecuteCommandResponse) GetTerminal() *BatchTerminal {
	if x != nil {
		if x, ok := x.Event.(*BatchExecuteCommandResponse_Terminal); ok {
			return x.Terminal
		}
	}
	return nil
}

type isBatchExecuteCommandResponse_Event interface {
	isBatchExecuteCommandResponse_Event()
}

type BatchExecuteCommandResponse_BatchJobId struct {
	BatchJobId string `protobuf:"bytes,1,opt,name=batch_job_id,json=batchJobId,proto3,oneof"`
}

type BatchExecuteCommandResponse_Lifecycle struct {
	Lifecycle *BatchAgentLifecycle `protobuf:"bytes,2,opt,name=lifecycle,proto3,oneof"`
}

type BatchExecuteCommandResponse_Output struct {
	Output *BatchAgentOutput `protobuf:"bytes,3,opt,name=output,proto3,oneof"`
}

type BatchExecuteCommandResponse_Terminal struct {
	Terminal *BatchTerminal `protobuf:"bytes,4,opt,name=terminal,proto3,oneof"`
}

func (*BatchExecuteCommandResponse_BatchJobId) isBatchExecuteCommandResponse_Event() {}

func (*BatchExecuteCommandResponse_Lifecycle) isBatchExecuteCommandResponse_Event() {}

func (*BatchExecuteCommandResponse_Output) isBatchExecuteCommandResponse_Event() {}

func (*BatchExecuteCommandResponse_Terminal) isBatchExecuteCommandResponse_Event() {}

// BatchAgentOutput is one agent's output chunk within a batch stream.
type BatchAgentOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Output        *CommandOutputChunk    `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAgentOutput) Reset() {
	*x = BatchAgentOutput{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAgentOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAgentOutput) ProtoMessage() {}

func (x *BatchAgentOutput) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAgentOutput.ProtoReflect.Descriptor instead.
func (*BatchAgentOutput) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *BatchAgentOutput) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BatchAgentOutput) GetOutput() *CommandOutputChunk {
	if x != nil {
		return x.Output
	}
	return nil
}

type GetCommandStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandStatusRequest) Reset() {
	*x = GetCommandStatusRequest{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandStatusRequest) ProtoMessage() {}

func (x *GetCommandStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCommandStatusRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *GetCommandStatusRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type GetCommandStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandStatusResponse) Reset() {
	*x = GetCommandStatusResponse{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandStatusResponse) ProtoMessage() {}

func (x *GetCommandStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCommandStatusResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{12}
}

func (x *GetCommandStatusResponse) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type ListCommandHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // empty = all agents
	Status        CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=keystone.core.v1.CommandStatus" json:"status,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=until,proto3" json:"until,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandHistoryRequest) Reset() {
	*x = ListCommandHistoryRequest{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandHistoryRequest) ProtoMessage() {}

func (x *ListCommandHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListCommandHistoryRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{13}
}

func (x *ListCommandHistoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListCommandHistoryRequest) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *ListCommandHistoryRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListCommandHistoryRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *ListCommandHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCommandHistoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCommandHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandHistoryResponse) Reset() {
	*x = ListCommandHistoryResponse{}
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandHistoryResponse) ProtoMessage() {}

func (x *ListCommandHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListCommandHistoryResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *ListCommandHistoryResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ListCommandHistoryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListCommandHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_keystone_core_v1_controlplane_proto protoreflect.FileDescriptor

const file_keystone_core_v1_controlplane_proto_rawDesc = "" +
	"\n" +
	"#keystone/core/v1/controlplane.proto\x12\x10keystone.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dkeystone/core/v1/common.proto\"\x15\n" +
	"\x13ServerStatusRequest\"\xc9\x02\n" +
	"\x14ServerStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x129\n" +
	"\n" +
	"build_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tbuildDate\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12)\n" +
	"\x10connected_agents\x18\x05 \x01(\x05R\x0fconnectedAgents\x12!\n" +
	"\fnats_healthy\x18\x06 \x01(\bR\vnatsHealthy\x12'\n" +
	"\x0fstorage_healthy\x18\a \x01(\bR\x0estorageHealthy\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04mode\"\xc4\x01\n" +
	"\x11ListAgentsRequest\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.keystone.core.v1.AgentStatusR\x06status\x12\x1b\n" +
	"\tlabel_key\x18\x02 \x01(\tR\blabelKey\x12\x1f\n" +
	"\vlabel_value\x18\x03 \x01(\tR\n" +
	"labelValue\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x8e\x01\n" +
	"\x12ListAgentsResponse\x12/\n" +
	"\x06agents\x18\x01 \x03(\v2\x17.keystone.core.v1.AgentR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"A\n" +
	"\x10GetAgentResponse\x12-\n" +
	"\x05agent\x18\x01 \x01(\v2\x17.keystone.core.v1.AgentR\x05agent\"\xba\x02\n" +
	"\x15ExecuteCommandRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12B\n" +
	"\x03env\x18\x04 \x03(\v20.keystone.core.v1.ExecuteCommandRequest.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x16ExecuteCommandResponse\x12\x1f\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tH\x00R\tcommandId\x12>\n" +
	"\x06output\x18\x02 \x01(\v2$.keystone.core.v1.CommandOutputChunkH\x00R\x06output\x12E\n" +
	"\n" +
	"completion\x18\x03 \x01(\v2#.keystone.core.v1.CommandCompletionH\x00R\n" +
	"completionB\a\n" +
	"\x05event\"\xad\x03\n" +
	"\x1aBatchExecuteCommandRequest\x120\n" +
	"\x06target\x18\x01 \x01(\v2\x18.keystone.core.v1.TargetR\x06target\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12G\n" +
	"\x03env\x18\x04 \x03(\v25.keystone.core.v1.BatchExecuteCommandRequest.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\x12 \n" +
	"\vconcurrency\x18\b \x01(\x05R\vconcurrency\x12.\n" +
	"\x13continue_on_failure\x18\t \x01(\bR\x11continueOnFailure\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x02\n" +
	"\x1bBatchExecuteCommandResponse\x12\"\n" +
	"\fbatch_job_id\x18\x01 \x01(\tH\x00R\n" +
	"batchJobId\x12E\n" +
	"\tlifecycle\x18\x02 \x01(\v2%.keystone.core.v1.BatchAgentLifecycleH\x00R\tlifecycle\x12<\n" +
	"\x06output\x18\x03 \x01(\v2\".keystone.core.v1.BatchAgentOutputH\x00R\x06output\x12=\n" +
	"\bterminal\x18\x04 \x01(\v2\x1f.keystone.core.v1.BatchTerminalH\x00R\bterminalB\a\n" +
	"\x05event\"k\n" +
	"\x10BatchAgentOutput\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12<\n" +
	"\x06output\x18\x02 \x01(\v2$.keystone.core.v1.CommandOutputChunkR\x06output\"8\n" +
	"\x17GetCommandStatusRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"O\n" +
	"\x18GetCommandStatusResponse\x123\n" +
	"\acommand\x18\x01 \x01(\v2\x19.keystone.core.v1.CommandR\acommand\"\x8f\x02\n" +
	"\x19ListCommandHistoryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.keystone.core.v1.CommandStatusR\x06status\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\x9c\x01\n" +
	"\x1aListCommandHistoryResponse\x125\n" +
	"\bcommands\x18\x01 \x03(\v2\x19.keystone.core.v1.CommandR\bcommands\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount2\xd9\x05\n" +
	"\x13ControlPlaneService\x12]\n" +
	"\fServerStatus\x12%.keystone.core.v1.ServerStatusRequest\x1a&.keystone.core.v1.ServerStatusResponse\x12W\n" +
	"\n" +
	"ListAgents\x12#.keystone.core.v1.ListAgentsRequest\x1a$.keystone.core.v1.ListAgentsResponse\x12Q\n" +
	"\bGetAgent\x12!.keystone.core.v1.GetAgentRequest\x1a\".keystone.core.v1.GetAgentResponse\x12e\n" +
	"\x0eExecuteCommand\x12'.keystone.core.v1.ExecuteCommandRequest\x1a(.keystone.core.v1.ExecuteCommandResponse0\x01\x12t\n" +
	"\x13BatchExecuteCommand\x12,.keystone.core.v1.BatchExecuteCommandRequest\x1a-.keystone.core.v1.BatchExecuteCommandResponse0\x01\x12i\n" +
	"\x10GetCommandStatus\x12).keystone.core.v1.GetCommandStatusRequest\x1a*.keystone.core.v1.GetCommandStatusResponse\x12o\n" +
	"\x12ListCommandHistory\x12+.keystone.core.v1.ListCommandHistoryRequest\x1a,.keystone.core.v1.ListCommandHistoryResponseB1Z/go.keystone-core.io/keystone-core/pkg/api/v1;v1b\x06proto3"

var (
	file_keystone_core_v1_controlplane_proto_rawDescOnce sync.Once
	file_keystone_core_v1_controlplane_proto_rawDescData []byte
)

func file_keystone_core_v1_controlplane_proto_rawDescGZIP() []byte {
	file_keystone_core_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_keystone_core_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keystone_core_v1_controlplane_proto_rawDesc), len(file_keystone_core_v1_controlplane_proto_rawDesc)))
	})
	return file_keystone_core_v1_controlplane_proto_rawDescData
}

var file_keystone_core_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_keystone_core_v1_controlplane_proto_goTypes = []any{
	(*ServerStatusRequest)(nil),         // 0: keystone.core.v1.ServerStatusRequest
	(*ServerStatusResponse)(nil),        // 1: keystone.core.v1.ServerStatusResponse
	(*ListAgentsRequest)(nil),           // 2: keystone.core.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),          // 3: keystone.core.v1.ListAgentsResponse
	(*GetAgentRequest)(nil),             // 4: keystone.core.v1.GetAgentRequest
	(*GetAgentResponse)(nil),            // 5: keystone.core.v1.GetAgentResponse
	(*ExecuteCommandRequest)(nil),       // 6: keystone.core.v1.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil),      // 7: keystone.core.v1.ExecuteCommandResponse
	(*BatchExecuteCommandRequest)(nil),  // 8: keystone.core.v1.BatchExecuteCommandRequest
	(*BatchExecuteCommandResponse)(nil), // 9: keystone.core.v1.BatchExecuteCommandResponse
	(*BatchAgentOutput)(nil),            // 10: keystone.core.v1.BatchAgentOutput
	(*GetCommandStatusRequest)(nil),     // 11: keystone.core.v1.GetCommandStatusRequest
	(*GetCommandStatusResponse)(nil),    // 12: keystone.core.v1.GetCommandStatusResponse
	(*ListCommandHistoryRequest)(nil),   // 13: keystone.core.v1.ListCommandHistoryRequest
	(*ListCommandHistoryResponse)(nil),  // 14: keystone.core.v1.ListCommandHistoryResponse
	nil,                                 // 15: keystone.core.v1.ExecuteCommandRequest.EnvEntry
	nil,                                 // 16: keystone.core.v1.BatchExecuteCommandRequest.EnvEntry
	(*timestamppb.Timestamp)(nil),       // 17: google.protobuf.Timestamp
	(AgentStatus)(0),                    // 18: keystone.core.v1.AgentStatus
	(*Agent)(nil),                       // 19: keystone.core.v1.Agent
	(*CommandOutputChunk)(nil),          // 20: keystone.core.v1.CommandOutputChunk
	(*CommandCompletion)(nil),           // 21: keystone.core.v1.CommandCompletion
	(*Target)(nil),                      // 22: keystone.core.v1.Target
	(*BatchAgentLifecycle)(nil),         // 23: keystone.core.v1.BatchAgentLifecycle
	(*BatchTerminal)(nil),               // 24: keystone.core.v1.BatchTerminal
	(*Command)(nil),                     // 25: keystone.core.v1.Command
	(CommandStatus)(0),                  // 26: keystone.core.v1.CommandStatus
}
var file_keystone_core_v1_controlplane_proto_depIdxs = []int32{
	17, // 0: keystone.core.v1.ServerStatusResponse.build_date:type_name -> google.protobuf.Timestamp
	17, // 1: keystone.core.v1.ServerStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	18, // 2: keystone.core.v1.ListAgentsRequest.status:type_name -> keystone.core.v1.AgentStatus
	19, // 3: keystone.core.v1.ListAgentsResponse.agents:type_name -> keystone.core.v1.Agent
	19, // 4: keystone.core.v1.GetAgentResponse.agent:type_name -> keystone.core.v1.Agent
	15, // 5: keystone.core.v1.ExecuteCommandRequest.env:type_name -> keystone.core.v1.ExecuteCommandRequest.EnvEntry
	20, // 6: keystone.core.v1.ExecuteCommandResponse.output:type_name -> keystone.core.v1.CommandOutputChunk
	21, // 7: keystone.core.v1.ExecuteCommandResponse.completion:type_name -> keystone.core.v1.CommandCompletion
	22, // 8: keystone.core.v1.BatchExecuteCommandRequest.target:type_name -> keystone.core.v1.Target
	16, // 9: keystone.core.v1.BatchExecuteCommandRequest.env:type_name -> keystone.core.v1.BatchExecuteCommandRequest.EnvEntry
	23, // 10: keystone.core.v1.BatchExecuteCommandResponse.lifecycle:type_name -> keystone.core.v1.BatchAgentLifecycle
	10, // 11: keystone.core.v1.BatchExecuteCommandResponse.output:type_name -> keystone.core.v1.BatchAgentOutput
	24, // 12: keystone.core.v1.BatchExecuteCommandResponse.terminal:type_name -> keystone.core.v1.BatchTerminal
	20, // 13: keystone.core.v1.BatchAgentOutput.output:type_name -> keystone.core.v1.CommandOutputChunk
	25, // 14: keystone.core.v1.GetCommandStatusResponse.command:type_name -> keystone.core.v1.Command
	26, // 15: keystone.core.v1.ListCommandHistoryRequest.status:type_name -> keystone.core.v1.CommandStatus
	17, // 16: keystone.core.v1.ListCommandHistoryRequest.since:type_name -> google.protobuf.Timestamp
	17, // 17: keystone.core.v1.ListCommandHistoryRequest.until:type_name -> google.protobuf.Timestamp
	25, // 18: keystone.core.v1.ListCommandHistoryResponse.commands:type_name -> keystone.core.v1.Command
	0,  // 19: keystone.core.v1.ControlPlaneService.ServerStatus:input_type -> keystone.core.v1.ServerStatusRequest
	2,  // 20: keystone.core.v1.ControlPlaneService.ListAgents:input_type -> keystone.core.v1.ListAgentsRequest
	4,  // 21: keystone.core.v1.ControlPlaneService.GetAgent:input_type -> keystone.core.v1.GetAgentRequest
	6,  // 22: keystone.core.v1.ControlPlaneService.ExecuteCommand:input_type -> keystone.core.v1.ExecuteCommandRequest
	8,  // 23: keystone.core.v1.ControlPlaneService.BatchExecuteCommand:input_type -> keystone.core.v1.BatchExecuteCommandRequest
	11, // 24: keystone.core.v1.ControlPlaneService.GetCommandStatus:input_type -> keystone.core.v1.GetCommandStatusRequest
	13, // 25: keystone.core.v1.ControlPlaneService.ListCommandHistory:input_type -> keystone.core.v1.ListCommandHistoryRequest
	1,  // 26: keystone.core.v1.ControlPlaneService.ServerStatus:output_type -> keystone.core.v1.ServerStatusResponse
	3,  // 27: keystone.core.v1.ControlPlaneService.ListAgents:output_type -> keystone.core.v1.ListAgentsResponse
	5,  // 28: keystone.core.v1.ControlPlaneService.GetAgent:output_type -> keystone.core.v1.GetAgentResponse
	7,  // 29: keystone.core.v1.ControlPlaneService.ExecuteCommand:output_type -> keystone.core.v1.ExecuteCommandResponse
	9,  // 30: keystone.core.v1.ControlPlaneService.BatchExecuteCommand:output_type -> keystone.core.v1.BatchExecuteCommandResponse
	12, // 31: keystone.core.v1.ControlPlaneService.GetCommandStatus:output_type -> keystone.core.v1.GetCommandStatusResponse
	14, // 32: keystone.core.v1.ControlPlaneService.ListCommandHistory:output_type -> keystone.core.v1.ListCommandHistoryResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_keystone_core_v1_controlplane_proto_init() }
func file_keystone_core_v1_controlplane_proto_init() {
	if File_keystone_core_v1_controlplane_proto != nil {
		return
	}
	file_keystone_core_v1_common_proto_init()
	file_keystone_core_v1_controlplane_proto_msgTypes[7].OneofWrappers = []any{
		(*ExecuteCommandResponse_CommandId)(nil),
		(*ExecuteCommandResponse_Output)(nil),
		(*ExecuteCommandResponse_Completion)(nil),
	}
	file_keystone_core_v1_controlplane_proto_msgTypes[9].OneofWrappers = []any{
		(*BatchExecuteCommandResponse_BatchJobId)(nil),
		(*BatchExecuteCommandResponse_Lifecycle)(nil),
		(*BatchExecuteCommandResponse_Output)(nil),
		(*BatchExecuteCommandResponse_Terminal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keystone_core_v1_controlplane_proto_rawDesc), len(file_keystone_core_v1_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keystone_core_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_keystone_core_v1_controlplane_proto_depIdxs,
		MessageInfos:      file_keystone_core_v1_controlplane_proto_msgTypes,
	}.Build()
	File_keystone_core_v1_controlplane_proto = out.File
	file_keystone_core_v1_controlplane_proto_goTypes = nil
	file_keystone_core_v1_controlplane_proto_depIdxs = nil
}
