// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: controlplane.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandStatus represents the status of a command execution
type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_PENDING     CommandStatus = 1
	CommandStatus_COMMAND_STATUS_RUNNING     CommandStatus = 2
	CommandStatus_COMMAND_STATUS_COMPLETED   CommandStatus = 3
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 4
	CommandStatus_COMMAND_STATUS_TIMEOUT     CommandStatus = 5
	CommandStatus_COMMAND_STATUS_CANCELLED   CommandStatus = 6
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_PENDING",
		2: "COMMAND_STATUS_RUNNING",
		3: "COMMAND_STATUS_COMPLETED",
		4: "COMMAND_STATUS_FAILED",
		5: "COMMAND_STATUS_TIMEOUT",
		6: "COMMAND_STATUS_CANCELLED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_PENDING":     1,
		"COMMAND_STATUS_RUNNING":     2,
		"COMMAND_STATUS_COMPLETED":   3,
		"COMMAND_STATUS_FAILED":      4,
		"COMMAND_STATUS_TIMEOUT":     5,
		"COMMAND_STATUS_CANCELLED":   6,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_proto_enumTypes[0].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_controlplane_proto_enumTypes[0]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{0}
}

// ListAgentsRequest requests a list of agents
type ListAgentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by status (optional)
	Status AgentStatus `protobuf:"varint,1,opt,name=status,proto3,enum=titan.anvil.v1.AgentStatus" json:"status,omitempty"`
	// Filter by labels (optional)
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Pagination
	PageSize      int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *ListAgentsRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *ListAgentsRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListAgentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListAgentsResponse returns a list of agents
type ListAgentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of agents
	Agents []*AgentInfo `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	// Next page token
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAgentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// AgentInfo contains detailed agent information
type AgentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Agent metadata
	Metadata *AgentMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Current status
	Status AgentStatus `protobuf:"varint,3,opt,name=status,proto3,enum=titan.anvil.v1.AgentStatus" json:"status,omitempty"`
	// Last heartbeat timestamp
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	// Registration timestamp
	RegisteredAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	// System metrics
	Metrics       *SystemMetrics `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AgentInfo) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *AgentInfo) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *AgentInfo) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *AgentInfo) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// GetAgentRequest requests agent information
type GetAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// GetAgentResponse returns agent information
type GetAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent information
	Agent         *AgentInfo `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

// GetCommandStatusRequest requests command execution status
type GetCommandStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command ID
	CommandId     string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandStatusRequest) Reset() {
	*x = GetCommandStatusRequest{}
	mi := &file_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandStatusRequest) ProtoMessage() {}

func (x *GetCommandStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCommandStatusRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *GetCommandStatusRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

// GetCommandStatusResponse returns command execution status
type GetCommandStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command ID
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Command status
	Status CommandStatus `protobuf:"varint,2,opt,name=status,proto3,enum=titan.anvil.v1.CommandStatus" json:"status,omitempty"`
	// Target agent ID
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Command details
	Command string   `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	// Execution results
	ExitCode int32  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout   string `protobuf:"bytes,7,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr   string `protobuf:"bytes,8,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Error    string `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	// Timestamps
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Duration in milliseconds
	DurationMs    int64 `protobuf:"varint,13,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandStatusResponse) Reset() {
	*x = GetCommandStatusResponse{}
	mi := &file_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandStatusResponse) ProtoMessage() {}

func (x *GetCommandStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCommandStatusResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *GetCommandStatusResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *GetCommandStatusResponse) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *GetCommandStatusResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetCommandStatusResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetCommandStatusResponse) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *GetCommandStatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *GetCommandStatusResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *GetCommandStatusResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *GetCommandStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetCommandStatusResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetCommandStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetCommandStatusResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *GetCommandStatusResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// ListCommandsRequest requests command execution history
type ListCommandsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by agent ID (optional)
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Filter by status (optional)
	Status CommandStatus `protobuf:"varint,2,opt,name=status,proto3,enum=titan.anvil.v1.CommandStatus" json:"status,omitempty"`
	// Filter by time range (optional)
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Pagination
	PageSize      int32  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsRequest) Reset() {
	*x = ListCommandsRequest{}
	mi := &file_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsRequest) ProtoMessage() {}

func (x *ListCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsRequest.ProtoReflect.Descriptor instead.
func (*ListCommandsRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *ListCommandsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListCommandsRequest) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *ListCommandsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListCommandsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListCommandsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCommandsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListCommandsResponse returns command execution history
type ListCommandsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of commands
	Commands []*CommandInfo `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	// Next page token
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsResponse) Reset() {
	*x = ListCommandsResponse{}
	mi := &file_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsResponse) ProtoMessage() {}

func (x *ListCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsResponse.ProtoReflect.Descriptor instead.
func (*ListCommandsResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *ListCommandsResponse) GetCommands() []*CommandInfo {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ListCommandsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListCommandsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// CommandInfo contains command execution information
type CommandInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command ID
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Target agent ID
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Command details
	Command string   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	// Status
	Status CommandStatus `protobuf:"varint,5,opt,name=status,proto3,enum=titan.anvil.v1.CommandStatus" json:"status,omitempty"`
	// Exit code
	ExitCode int32 `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Timestamps
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Duration in milliseconds
	DurationMs    int64 `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandInfo) Reset() {
	*x = CommandInfo{}
	mi := &file_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInfo) ProtoMessage() {}

func (x *CommandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInfo.ProtoReflect.Descriptor instead.
func (*CommandInfo) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *CommandInfo) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommandInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandInfo) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandInfo) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *CommandInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CommandInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CommandInfo) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *CommandInfo) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_controlplane_proto protoreflect.FileDescriptor

const file_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x12controlplane.proto\x12\x0etitan.anvil.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\vagent.proto\"\x86\x02\n" +
	"\x11ListAgentsRequest\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.titan.anvil.v1.AgentStatusR\x06status\x12E\n" +
	"\x06labels\x18\x02 \x03(\v2-.titan.anvil.v1.ListAgentsRequest.LabelsEntryR\x06labels\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x12ListAgentsResponse\x121\n" +
	"\x06agents\x18\x01 \x03(\v2\x19.titan.anvil.v1.AgentInfoR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xd3\x02\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x129\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1d.titan.anvil.v1.AgentMetadataR\bmetadata\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.titan.anvil.v1.AgentStatusR\x06status\x12A\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x127\n" +
	"\ametrics\x18\x06 \x01(\v2\x1d.titan.anvil.v1.SystemMetricsR\ametrics\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"C\n" +
	"\x10GetAgentResponse\x12/\n" +
	"\x05agent\x18\x01 \x01(\v2\x19.titan.anvil.v1.AgentInfoR\x05agent\"8\n" +
	"\x17GetCommandStatusRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"\xf2\x03\n" +
	"\x18GetCommandStatusResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.titan.anvil.v1.CommandStatusR\x06status\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\a \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\b \x01(\tR\x06stderr\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\r \x01(\x03R\n" +
	"durationMs\"\x95\x02\n" +
	"\x13ListCommandsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.titan.anvil.v1.CommandStatusR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\x98\x01\n" +
	"\x14ListCommandsResponse\x127\n" +
	"\bcommands\x18\x01 \x03(\v2\x1b.titan.anvil.v1.CommandInfoR\bcommands\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\x9f\x03\n" +
	"\vCommandInfo\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x125\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1d.titan.anvil.v1.CommandStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x03R\n" +
	"durationMs*\xda\x01\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMMAND_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16COMMAND_STATUS_RUNNING\x10\x02\x12\x1c\n" +
	"\x18COMMAND_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15COMMAND_STATUS_FAILED\x10\x04\x12\x1a\n" +
	"\x16COMMAND_STATUS_TIMEOUT\x10\x05\x12\x1c\n" +
	"\x18COMMAND_STATUS_CANCELLED\x10\x062\xde\x03\n" +
	"\x13ControlPlaneService\x12S\n" +
	"\n" +
	"ListAgents\x12!.titan.anvil.v1.ListAgentsRequest\x1a\".titan.anvil.v1.ListAgentsResponse\x12M\n" +
	"\bGetAgent\x12\x1f.titan.anvil.v1.GetAgentRequest\x1a .titan.anvil.v1.GetAgentResponse\x12a\n" +
	"\x0eExecuteCommand\x12%.titan.anvil.v1.ExecuteCommandRequest\x1a&.titan.anvil.v1.ExecuteCommandResponse0\x01\x12e\n" +
	"\x10GetCommandStatus\x12'.titan.anvil.v1.GetCommandStatusRequest\x1a(.titan.anvil.v1.GetCommandStatusResponse\x12Y\n" +
	"\fListCommands\x12#.titan.anvil.v1.ListCommandsRequest\x1a$.titan.anvil.v1.ListCommandsResponseB1Z/github.com/titananvil/titan-anvil/pkg/api/v1;v1b\x06proto3"

var (
	file_controlplane_proto_rawDescOnce sync.Once
	file_controlplane_proto_rawDescData []byte
)

func file_controlplane_proto_rawDescGZIP() []byte {
	file_controlplane_proto_rawDescOnce.Do(func() {
		file_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_proto_rawDesc), len(file_controlplane_proto_rawDesc)))
	})
	return file_controlplane_proto_rawDescData
}

var file_controlplane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_controlplane_proto_goTypes = []any{
	(CommandStatus)(0),               // 0: titan.anvil.v1.CommandStatus
	(*ListAgentsRequest)(nil),        // 1: titan.anvil.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),       // 2: titan.anvil.v1.ListAgentsResponse
	(*AgentInfo)(nil),                // 3: titan.anvil.v1.AgentInfo
	(*GetAgentRequest)(nil),          // 4: titan.anvil.v1.GetAgentRequest
	(*GetAgentResponse)(nil),         // 5: titan.anvil.v1.GetAgentResponse
	(*GetCommandStatusRequest)(nil),  // 6: titan.anvil.v1.GetCommandStatusRequest
	(*GetCommandStatusResponse)(nil), // 7: titan.anvil.v1.GetCommandStatusResponse
	(*ListCommandsRequest)(nil),      // 8: titan.anvil.v1.ListCommandsRequest
	(*ListCommandsResponse)(nil),     // 9: titan.anvil.v1.ListCommandsResponse
	(*CommandInfo)(nil),              // 10: titan.anvil.v1.CommandInfo
	nil,                              // 11: titan.anvil.v1.ListAgentsRequest.LabelsEntry
	(AgentStatus)(0),                 // 12: titan.anvil.v1.AgentStatus
	(*AgentMetadata)(nil),            // 13: titan.anvil.v1.AgentMetadata
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(*SystemMetrics)(nil),            // 15: titan.anvil.v1.SystemMetrics
	(*ExecuteCommandRequest)(nil),    // 16: titan.anvil.v1.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil),   // 17: titan.anvil.v1.ExecuteCommandResponse
}
var file_controlplane_proto_depIdxs = []int32{
	12, // 0: titan.anvil.v1.ListAgentsRequest.status:type_name -> titan.anvil.v1.AgentStatus
	11, // 1: titan.anvil.v1.ListAgentsRequest.labels:type_name -> titan.anvil.v1.ListAgentsRequest.LabelsEntry
	3,  // 2: titan.anvil.v1.ListAgentsResponse.agents:type_name -> titan.anvil.v1.AgentInfo
	13, // 3: titan.anvil.v1.AgentInfo.metadata:type_name -> titan.anvil.v1.AgentMetadata
	12, // 4: titan.anvil.v1.AgentInfo.status:type_name -> titan.anvil.v1.AgentStatus
	14, // 5: titan.anvil.v1.AgentInfo.last_heartbeat:type_name -> google.protobuf.Timestamp
	14, // 6: titan.anvil.v1.AgentInfo.registered_at:type_name -> google.protobuf.Timestamp
	15, // 7: titan.anvil.v1.AgentInfo.metrics:type_name -> titan.anvil.v1.SystemMetrics
	3,  // 8: titan.anvil.v1.GetAgentResponse.agent:type_name -> titan.anvil.v1.AgentInfo
	0,  // 9: titan.anvil.v1.GetCommandStatusResponse.status:type_name -> titan.anvil.v1.CommandStatus
	14, // 10: titan.anvil.v1.GetCommandStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 11: titan.anvil.v1.GetCommandStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	14, // 12: titan.anvil.v1.GetCommandStatusResponse.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 13: titan.anvil.v1.ListCommandsRequest.status:type_name -> titan.anvil.v1.CommandStatus
	14, // 14: titan.anvil.v1.ListCommandsRequest.start_time:type_name -> google.protobuf.Timestamp
	14, // 15: titan.anvil.v1.ListCommandsRequest.end_time:type_name -> google.protobuf.Timestamp
	10, // 16: titan.anvil.v1.ListCommandsResponse.commands:type_name -> titan.anvil.v1.CommandInfo
	0,  // 17: titan.anvil.v1.CommandInfo.status:type_name -> titan.anvil.v1.CommandStatus
	14, // 18: titan.anvil.v1.CommandInfo.created_at:type_name -> google.protobuf.Timestamp
	14, // 19: titan.anvil.v1.CommandInfo.started_at:type_name -> google.protobuf.Timestamp
	14, // 20: titan.anvil.v1.CommandInfo.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 21: titan.anvil.v1.ControlPlaneService.ListAgents:input_type -> titan.anvil.v1.ListAgentsRequest
	4,  // 22: titan.anvil.v1.ControlPlaneService.GetAgent:input_type -> titan.anvil.v1.GetAgentRequest
	16, // 23: titan.anvil.v1.ControlPlaneService.ExecuteCommand:input_type -> titan.anvil.v1.ExecuteCommandRequest
	6,  // 24: titan.anvil.v1.ControlPlaneService.GetCommandStatus:input_type -> titan.anvil.v1.GetCommandStatusRequest
	8,  // 25: titan.anvil.v1.ControlPlaneService.ListCommands:input_type -> titan.anvil.v1.ListCommandsRequest
	2,  // 26: titan.anvil.v1.ControlPlaneService.ListAgents:output_type -> titan.anvil.v1.ListAgentsResponse
	5,  // 27: titan.anvil.v1.ControlPlaneService.GetAgent:output_type -> titan.anvil.v1.GetAgentResponse
	17, // 28: titan.anvil.v1.ControlPlaneService.ExecuteCommand:output_type -> titan.anvil.v1.ExecuteCommandResponse
	7,  // 29: titan.anvil.v1.ControlPlaneService.GetCommandStatus:output_type -> titan.anvil.v1.GetCommandStatusResponse
	9,  // 30: titan.anvil.v1.ControlPlaneService.ListCommands:output_type -> titan.anvil.v1.ListCommandsResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_controlplane_proto_init() }
func file_controlplane_proto_init() {
	if File_controlplane_proto != nil {
		return
	}
	file_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_proto_rawDesc), len(file_controlplane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_proto_goTypes,
		DependencyIndexes: file_controlplane_proto_depIdxs,
		EnumInfos:         file_controlplane_proto_enumTypes,
		MessageInfos:      file_controlplane_proto_msgTypes,
	}.Build()
	File_controlplane_proto = out.File
	file_controlplane_proto_goTypes = nil
	file_controlplane_proto_depIdxs = nil
}
