// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: controlplane.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_GetServerStatus_FullMethodName     = "/keystone.core.v1.ControlPlaneService/GetServerStatus"
	ControlPlaneService_ListAgents_FullMethodName          = "/keystone.core.v1.ControlPlaneService/ListAgents"
	ControlPlaneService_GetAgent_FullMethodName            = "/keystone.core.v1.ControlPlaneService/GetAgent"
	ControlPlaneService_ExecuteCommand_FullMethodName      = "/keystone.core.v1.ControlPlaneService/ExecuteCommand"
	ControlPlaneService_GetCommandStatus_FullMethodName    = "/keystone.core.v1.ControlPlaneService/GetCommandStatus"
	ControlPlaneService_ListCommands_FullMethodName        = "/keystone.core.v1.ControlPlaneService/ListCommands"
	ControlPlaneService_BatchExecuteCommand_FullMethodName = "/keystone.core.v1.ControlPlaneService/BatchExecuteCommand"
	ControlPlaneService_GetBatchJobStatus_FullMethodName   = "/keystone.core.v1.ControlPlaneService/GetBatchJobStatus"
	ControlPlaneService_ListBatchJobs_FullMethodName       = "/keystone.core.v1.ControlPlaneService/ListBatchJobs"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlaneService defines the control plane API
type ControlPlaneServiceClient interface {
	// GetServerStatus retrieves the server status and runtime information
	GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*GetServerStatusResponse, error)
	// ListAgents lists all registered agents
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// GetAgent retrieves information about a specific agent
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error)
	// ExecuteCommand executes a command on one or more agents
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteCommandResponse], error)
	// GetCommandStatus retrieves the status of a command execution
	GetCommandStatus(ctx context.Context, in *GetCommandStatusRequest, opts ...grpc.CallOption) (*GetCommandStatusResponse, error)
	// ListCommands lists command execution history
	ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error)
	// BatchExecuteCommand executes a command across multiple agents using a target expression
	BatchExecuteCommand(ctx context.Context, in *BatchExecuteCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BatchExecuteCommandResponse], error)
	// GetBatchJobStatus retrieves the status of a batch job
	GetBatchJobStatus(ctx context.Context, in *GetBatchJobStatusRequest, opts ...grpc.CallOption) (*GetBatchJobStatusResponse, error)
	// ListBatchJobs lists batch job execution history
	ListBatchJobs(ctx context.Context, in *ListBatchJobsRequest, opts ...grpc.CallOption) (*ListBatchJobsResponse, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*GetServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerStatusResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteCommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[0], ControlPlaneService_ExecuteCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteCommandRequest, ExecuteCommandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_ExecuteCommandClient = grpc.ServerStreamingClient[ExecuteCommandResponse]

func (c *controlPlaneServiceClient) GetCommandStatus(ctx context.Context, in *GetCommandStatusRequest, opts ...grpc.CallOption) (*GetCommandStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommandStatusResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetCommandStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommandsResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) BatchExecuteCommand(ctx context.Context, in *BatchExecuteCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BatchExecuteCommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[1], ControlPlaneService_BatchExecuteCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchExecuteCommandRequest, BatchExecuteCommandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_BatchExecuteCommandClient = grpc.ServerStreamingClient[BatchExecuteCommandResponse]

func (c *controlPlaneServiceClient) GetBatchJobStatus(ctx context.Context, in *GetBatchJobStatusRequest, opts ...grpc.CallOption) (*GetBatchJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchJobStatusResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetBatchJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ListBatchJobs(ctx context.Context, in *ListBatchJobsRequest, opts ...grpc.CallOption) (*ListBatchJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBatchJobsResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListBatchJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
//
// ControlPlaneService defines the control plane API
type ControlPlaneServiceServer interface {
	// GetServerStatus retrieves the server status and runtime information
	GetServerStatus(context.Context, *GetServerStatusRequest) (*GetServerStatusResponse, error)
	// ListAgents lists all registered agents
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// GetAgent retrieves information about a specific agent
	GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error)
	// ExecuteCommand executes a command on one or more agents
	ExecuteCommand(*ExecuteCommandRequest, grpc.ServerStreamingServer[ExecuteCommandResponse]) error
	// GetCommandStatus retrieves the status of a command execution
	GetCommandStatus(context.Context, *GetCommandStatusRequest) (*GetCommandStatusResponse, error)
	// ListCommands lists command execution history
	ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error)
	// BatchExecuteCommand executes a command across multiple agents using a target expression
	BatchExecuteCommand(*BatchExecuteCommandRequest, grpc.ServerStreamingServer[BatchExecuteCommandResponse]) error
	// GetBatchJobStatus retrieves the status of a batch job
	GetBatchJobStatus(context.Context, *GetBatchJobStatusRequest) (*GetBatchJobStatusResponse, error)
	// ListBatchJobs lists batch job execution history
	ListBatchJobs(context.Context, *ListBatchJobsRequest) (*ListBatchJobsResponse, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) GetServerStatus(context.Context, *GetServerStatusRequest) (*GetServerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerStatus not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedControlPlaneServiceServer) ExecuteCommand(*ExecuteCommandRequest, grpc.ServerStreamingServer[ExecuteCommandResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetCommandStatus(context.Context, *GetCommandStatusRequest) (*GetCommandStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommandStatus not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommands not implemented")
}
func (UnimplementedControlPlaneServiceServer) BatchExecuteCommand(*BatchExecuteCommandRequest, grpc.ServerStreamingServer[BatchExecuteCommandResponse]) error {
	return status.Error(codes.Unimplemented, "method BatchExecuteCommand not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetBatchJobStatus(context.Context, *GetBatchJobStatusRequest) (*GetBatchJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBatchJobStatus not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListBatchJobs(context.Context, *ListBatchJobsRequest) (*ListBatchJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBatchJobs not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_GetServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetServerStatus(ctx, req.(*GetServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ExecuteCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).ExecuteCommand(m, &grpc.GenericServerStream[ExecuteCommandRequest, ExecuteCommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_ExecuteCommandServer = grpc.ServerStreamingServer[ExecuteCommandResponse]

func _ControlPlaneService_GetCommandStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommandStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetCommandStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetCommandStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetCommandStatus(ctx, req.(*GetCommandStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ListCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListCommands(ctx, req.(*ListCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_BatchExecuteCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BatchExecuteCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).BatchExecuteCommand(m, &grpc.GenericServerStream[BatchExecuteCommandRequest, BatchExecuteCommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_BatchExecuteCommandServer = grpc.ServerStreamingServer[BatchExecuteCommandResponse]

func _ControlPlaneService_GetBatchJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetBatchJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetBatchJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetBatchJobStatus(ctx, req.(*GetBatchJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ListBatchJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBatchJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListBatchJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListBatchJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListBatchJobs(ctx, req.(*ListBatchJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keystone.core.v1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerStatus",
			Handler:    _ControlPlaneService_GetServerStatus_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _ControlPlaneService_ListAgents_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _ControlPlaneService_GetAgent_Handler,
		},
		{
			MethodName: "GetCommandStatus",
			Handler:    _ControlPlaneService_GetCommandStatus_Handler,
		},
		{
			MethodName: "ListCommands",
			Handler:    _ControlPlaneService_ListCommands_Handler,
		},
		{
			MethodName: "GetBatchJobStatus",
			Handler:    _ControlPlaneService_GetBatchJobStatus_Handler,
		},
		{
			MethodName: "ListBatchJobs",
			Handler:    _ControlPlaneService_ListBatchJobs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteCommand",
			Handler:       _ControlPlaneService_ExecuteCommand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BatchExecuteCommand",
			Handler:       _ControlPlaneService_BatchExecuteCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controlplane.proto",
}
