// CoordinationService — server↔server-only RPCs, the NATS-down
// recovery channel (PROJECT-DETAILS §4.15 Clustering & HA).
// mTLS-required: the CoordinationServer rejects callers without a
// verified client certificate (codes.Unauthenticated) per the
// Epic 13 acceptance criterion.
//
// Naming note: NodeHeartbeat / LookupLeader (not the spec-natural
// Heartbeat / GetLeader) keep message-type names unique within
// keystone.core.v1 (AgentService owns Heartbeat, ClusterService
// owns GetLeader).
//
// Epic 13 task 12 realigned this to the real cluster surface
// purely ADDITIVELY (new fields/messages; no removals or renames)
// so it stays wire-compatible with the Epic-03 placeholder.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: keystone/core/v1/coordination.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinationService_ClusterHealth_FullMethodName      = "/keystone.core.v1.CoordinationService/ClusterHealth"
	CoordinationService_LookupLeader_FullMethodName       = "/keystone.core.v1.CoordinationService/LookupLeader"
	CoordinationService_NATSStatus_FullMethodName         = "/keystone.core.v1.CoordinationService/NATSStatus"
	CoordinationService_RecoveryCoordinate_FullMethodName = "/keystone.core.v1.CoordinationService/RecoveryCoordinate"
	CoordinationService_NodeHeartbeat_FullMethodName      = "/keystone.core.v1.CoordinationService/NodeHeartbeat"
	CoordinationService_PropagateState_FullMethodName     = "/keystone.core.v1.CoordinationService/PropagateState"
)

// CoordinationServiceClient is the client API for CoordinationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinationServiceClient interface {
	ClusterHealth(ctx context.Context, in *ClusterHealthRequest, opts ...grpc.CallOption) (*ClusterHealthResponse, error)
	LookupLeader(ctx context.Context, in *LookupLeaderRequest, opts ...grpc.CallOption) (*LookupLeaderResponse, error)
	NATSStatus(ctx context.Context, in *NATSStatusRequest, opts ...grpc.CallOption) (*NATSStatusResponse, error)
	RecoveryCoordinate(ctx context.Context, in *RecoveryCoordinateRequest, opts ...grpc.CallOption) (*RecoveryCoordinateResponse, error)
	NodeHeartbeat(ctx context.Context, in *NodeHeartbeatRequest, opts ...grpc.CallOption) (*NodeHeartbeatResponse, error)
	PropagateState(ctx context.Context, in *PropagateStateRequest, opts ...grpc.CallOption) (*PropagateStateResponse, error)
}

type coordinationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinationServiceClient(cc grpc.ClientConnInterface) CoordinationServiceClient {
	return &coordinationServiceClient{cc}
}

func (c *coordinationServiceClient) ClusterHealth(ctx context.Context, in *ClusterHealthRequest, opts ...grpc.CallOption) (*ClusterHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterHealthResponse)
	err := c.cc.Invoke(ctx, CoordinationService_ClusterHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) LookupLeader(ctx context.Context, in *LookupLeaderRequest, opts ...grpc.CallOption) (*LookupLeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupLeaderResponse)
	err := c.cc.Invoke(ctx, CoordinationService_LookupLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) NATSStatus(ctx context.Context, in *NATSStatusRequest, opts ...grpc.CallOption) (*NATSStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NATSStatusResponse)
	err := c.cc.Invoke(ctx, CoordinationService_NATSStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) RecoveryCoordinate(ctx context.Context, in *RecoveryCoordinateRequest, opts ...grpc.CallOption) (*RecoveryCoordinateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoveryCoordinateResponse)
	err := c.cc.Invoke(ctx, CoordinationService_RecoveryCoordinate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) NodeHeartbeat(ctx context.Context, in *NodeHeartbeatRequest, opts ...grpc.CallOption) (*NodeHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeHeartbeatResponse)
	err := c.cc.Invoke(ctx, CoordinationService_NodeHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) PropagateState(ctx context.Context, in *PropagateStateRequest, opts ...grpc.CallOption) (*PropagateStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropagateStateResponse)
	err := c.cc.Invoke(ctx, CoordinationService_PropagateState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinationServiceServer is the server API for CoordinationService service.
// All implementations must embed UnimplementedCoordinationServiceServer
// for forward compatibility.
type CoordinationServiceServer interface {
	ClusterHealth(context.Context, *ClusterHealthRequest) (*ClusterHealthResponse, error)
	LookupLeader(context.Context, *LookupLeaderRequest) (*LookupLeaderResponse, error)
	NATSStatus(context.Context, *NATSStatusRequest) (*NATSStatusResponse, error)
	RecoveryCoordinate(context.Context, *RecoveryCoordinateRequest) (*RecoveryCoordinateResponse, error)
	NodeHeartbeat(context.Context, *NodeHeartbeatRequest) (*NodeHeartbeatResponse, error)
	PropagateState(context.Context, *PropagateStateRequest) (*PropagateStateResponse, error)
	mustEmbedUnimplementedCoordinationServiceServer()
}

// UnimplementedCoordinationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinationServiceServer struct{}

func (UnimplementedCoordinationServiceServer) ClusterHealth(context.Context, *ClusterHealthRequest) (*ClusterHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterHealth not implemented")
}
func (UnimplementedCoordinationServiceServer) LookupLeader(context.Context, *LookupLeaderRequest) (*LookupLeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupLeader not implemented")
}
func (UnimplementedCoordinationServiceServer) NATSStatus(context.Context, *NATSStatusRequest) (*NATSStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NATSStatus not implemented")
}
func (UnimplementedCoordinationServiceServer) RecoveryCoordinate(context.Context, *RecoveryCoordinateRequest) (*RecoveryCoordinateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoveryCoordinate not implemented")
}
func (UnimplementedCoordinationServiceServer) NodeHeartbeat(context.Context, *NodeHeartbeatRequest) (*NodeHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeHeartbeat not implemented")
}
func (UnimplementedCoordinationServiceServer) PropagateState(context.Context, *PropagateStateRequest) (*PropagateStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PropagateState not implemented")
}
func (UnimplementedCoordinationServiceServer) mustEmbedUnimplementedCoordinationServiceServer() {}
func (UnimplementedCoordinationServiceServer) testEmbeddedByValue()                             {}

// UnsafeCoordinationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinationServiceServer will
// result in compilation errors.
type UnsafeCoordinationServiceServer interface {
	mustEmbedUnimplementedCoordinationServiceServer()
}

func RegisterCoordinationServiceServer(s grpc.ServiceRegistrar, srv CoordinationServiceServer) {
	// If the following call panics, it indicates UnimplementedCoordinationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinationService_ServiceDesc, srv)
}

func _CoordinationService_ClusterHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).ClusterHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_ClusterHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).ClusterHealth(ctx, req.(*ClusterHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_LookupLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).LookupLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_LookupLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).LookupLeader(ctx, req.(*LookupLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_NATSStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NATSStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).NATSStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_NATSStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).NATSStatus(ctx, req.(*NATSStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_RecoveryCoordinate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoveryCoordinateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).RecoveryCoordinate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_RecoveryCoordinate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).RecoveryCoordinate(ctx, req.(*RecoveryCoordinateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_NodeHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).NodeHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_NodeHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).NodeHeartbeat(ctx, req.(*NodeHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_PropagateState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropagateStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).PropagateState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_PropagateState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).PropagateState(ctx, req.(*PropagateStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinationService_ServiceDesc is the grpc.ServiceDesc for CoordinationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keystone.core.v1.CoordinationService",
	HandlerType: (*CoordinationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClusterHealth",
			Handler:    _CoordinationService_ClusterHealth_Handler,
		},
		{
			MethodName: "LookupLeader",
			Handler:    _CoordinationService_LookupLeader_Handler,
		},
		{
			MethodName: "NATSStatus",
			Handler:    _CoordinationService_NATSStatus_Handler,
		},
		{
			MethodName: "RecoveryCoordinate",
			Handler:    _CoordinationService_RecoveryCoordinate_Handler,
		},
		{
			MethodName: "NodeHeartbeat",
			Handler:    _CoordinationService_NodeHeartbeat_Handler,
		},
		{
			MethodName: "PropagateState",
			Handler:    _CoordinationService_PropagateState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keystone/core/v1/coordination.proto",
}
