// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: coordination.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinationService_ClusterHealth_FullMethodName      = "/keystone.core.v1.CoordinationService/ClusterHealth"
	CoordinationService_GetLeader_FullMethodName          = "/keystone.core.v1.CoordinationService/GetLeader"
	CoordinationService_NATSStatus_FullMethodName         = "/keystone.core.v1.CoordinationService/NATSStatus"
	CoordinationService_RecoveryCoordinate_FullMethodName = "/keystone.core.v1.CoordinationService/RecoveryCoordinate"
	CoordinationService_Heartbeat_FullMethodName          = "/keystone.core.v1.CoordinationService/Heartbeat"
	CoordinationService_PropagateState_FullMethodName     = "/keystone.core.v1.CoordinationService/PropagateState"
)

// CoordinationServiceClient is the client API for CoordinationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoordinationService defines the server-to-server coordination protocol.
// This service is used for cluster coordination when NATS is unavailable.
// All RPCs require mTLS authentication.
type CoordinationServiceClient interface {
	// ClusterHealth returns the health status of the cluster from this server's perspective
	ClusterHealth(ctx context.Context, in *ClusterHealthRequest, opts ...grpc.CallOption) (*ClusterHealthResponse, error)
	// GetLeader returns information about the current cluster leader
	GetLeader(ctx context.Context, in *GetLeaderRequest, opts ...grpc.CallOption) (*GetLeaderResponse, error)
	// NATSStatus returns the NATS connectivity status for this server
	NATSStatus(ctx context.Context, in *NATSStatusRequest, opts ...grpc.CallOption) (*NATSStatusResponse, error)
	// RecoveryCoordinate coordinates NATS recovery actions across servers
	RecoveryCoordinate(ctx context.Context, in *RecoveryCoordinateRequest, opts ...grpc.CallOption) (*RecoveryCoordinateResponse, error)
	// Heartbeat performs a lightweight liveness check between servers
	Heartbeat(ctx context.Context, in *ServerHeartbeatRequest, opts ...grpc.CallOption) (*ServerHeartbeatResponse, error)
	// PropagateState propagates cluster state changes when NATS is down
	PropagateState(ctx context.Context, in *PropagateStateRequest, opts ...grpc.CallOption) (*PropagateStateResponse, error)
}

type coordinationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinationServiceClient(cc grpc.ClientConnInterface) CoordinationServiceClient {
	return &coordinationServiceClient{cc}
}

func (c *coordinationServiceClient) ClusterHealth(ctx context.Context, in *ClusterHealthRequest, opts ...grpc.CallOption) (*ClusterHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterHealthResponse)
	err := c.cc.Invoke(ctx, CoordinationService_ClusterHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) GetLeader(ctx context.Context, in *GetLeaderRequest, opts ...grpc.CallOption) (*GetLeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderResponse)
	err := c.cc.Invoke(ctx, CoordinationService_GetLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) NATSStatus(ctx context.Context, in *NATSStatusRequest, opts ...grpc.CallOption) (*NATSStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NATSStatusResponse)
	err := c.cc.Invoke(ctx, CoordinationService_NATSStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) RecoveryCoordinate(ctx context.Context, in *RecoveryCoordinateRequest, opts ...grpc.CallOption) (*RecoveryCoordinateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoveryCoordinateResponse)
	err := c.cc.Invoke(ctx, CoordinationService_RecoveryCoordinate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) Heartbeat(ctx context.Context, in *ServerHeartbeatRequest, opts ...grpc.CallOption) (*ServerHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerHeartbeatResponse)
	err := c.cc.Invoke(ctx, CoordinationService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) PropagateState(ctx context.Context, in *PropagateStateRequest, opts ...grpc.CallOption) (*PropagateStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropagateStateResponse)
	err := c.cc.Invoke(ctx, CoordinationService_PropagateState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinationServiceServer is the server API for CoordinationService service.
// All implementations must embed UnimplementedCoordinationServiceServer
// for forward compatibility.
//
// CoordinationService defines the server-to-server coordination protocol.
// This service is used for cluster coordination when NATS is unavailable.
// All RPCs require mTLS authentication.
type CoordinationServiceServer interface {
	// ClusterHealth returns the health status of the cluster from this server's perspective
	ClusterHealth(context.Context, *ClusterHealthRequest) (*ClusterHealthResponse, error)
	// GetLeader returns information about the current cluster leader
	GetLeader(context.Context, *GetLeaderRequest) (*GetLeaderResponse, error)
	// NATSStatus returns the NATS connectivity status for this server
	NATSStatus(context.Context, *NATSStatusRequest) (*NATSStatusResponse, error)
	// RecoveryCoordinate coordinates NATS recovery actions across servers
	RecoveryCoordinate(context.Context, *RecoveryCoordinateRequest) (*RecoveryCoordinateResponse, error)
	// Heartbeat performs a lightweight liveness check between servers
	Heartbeat(context.Context, *ServerHeartbeatRequest) (*ServerHeartbeatResponse, error)
	// PropagateState propagates cluster state changes when NATS is down
	PropagateState(context.Context, *PropagateStateRequest) (*PropagateStateResponse, error)
	mustEmbedUnimplementedCoordinationServiceServer()
}

// UnimplementedCoordinationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinationServiceServer struct{}

func (UnimplementedCoordinationServiceServer) ClusterHealth(context.Context, *ClusterHealthRequest) (*ClusterHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterHealth not implemented")
}
func (UnimplementedCoordinationServiceServer) GetLeader(context.Context, *GetLeaderRequest) (*GetLeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeader not implemented")
}
func (UnimplementedCoordinationServiceServer) NATSStatus(context.Context, *NATSStatusRequest) (*NATSStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NATSStatus not implemented")
}
func (UnimplementedCoordinationServiceServer) RecoveryCoordinate(context.Context, *RecoveryCoordinateRequest) (*RecoveryCoordinateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoveryCoordinate not implemented")
}
func (UnimplementedCoordinationServiceServer) Heartbeat(context.Context, *ServerHeartbeatRequest) (*ServerHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCoordinationServiceServer) PropagateState(context.Context, *PropagateStateRequest) (*PropagateStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PropagateState not implemented")
}
func (UnimplementedCoordinationServiceServer) mustEmbedUnimplementedCoordinationServiceServer() {}
func (UnimplementedCoordinationServiceServer) testEmbeddedByValue()                             {}

// UnsafeCoordinationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinationServiceServer will
// result in compilation errors.
type UnsafeCoordinationServiceServer interface {
	mustEmbedUnimplementedCoordinationServiceServer()
}

func RegisterCoordinationServiceServer(s grpc.ServiceRegistrar, srv CoordinationServiceServer) {
	// If the following call panics, it indicates UnimplementedCoordinationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinationService_ServiceDesc, srv)
}

func _CoordinationService_ClusterHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).ClusterHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_ClusterHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).ClusterHealth(ctx, req.(*ClusterHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_GetLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).GetLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_GetLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).GetLeader(ctx, req.(*GetLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_NATSStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NATSStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).NATSStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_NATSStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).NATSStatus(ctx, req.(*NATSStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_RecoveryCoordinate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoveryCoordinateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).RecoveryCoordinate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_RecoveryCoordinate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).RecoveryCoordinate(ctx, req.(*RecoveryCoordinateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).Heartbeat(ctx, req.(*ServerHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_PropagateState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropagateStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).PropagateState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_PropagateState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).PropagateState(ctx, req.(*PropagateStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinationService_ServiceDesc is the grpc.ServiceDesc for CoordinationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keystone.core.v1.CoordinationService",
	HandlerType: (*CoordinationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClusterHealth",
			Handler:    _CoordinationService_ClusterHealth_Handler,
		},
		{
			MethodName: "GetLeader",
			Handler:    _CoordinationService_GetLeader_Handler,
		},
		{
			MethodName: "NATSStatus",
			Handler:    _CoordinationService_NATSStatus_Handler,
		},
		{
			MethodName: "RecoveryCoordinate",
			Handler:    _CoordinationService_RecoveryCoordinate_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CoordinationService_Heartbeat_Handler,
		},
		{
			MethodName: "PropagateState",
			Handler:    _CoordinationService_PropagateState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordination.proto",
}
