// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventSeverity indicates the importance of an event
type EventSeverity int32

const (
	EventSeverity_EVENT_SEVERITY_UNSPECIFIED EventSeverity = 0
	EventSeverity_EVENT_SEVERITY_DEBUG       EventSeverity = 1
	EventSeverity_EVENT_SEVERITY_INFO        EventSeverity = 2
	EventSeverity_EVENT_SEVERITY_WARNING     EventSeverity = 3
	EventSeverity_EVENT_SEVERITY_ERROR       EventSeverity = 4
	EventSeverity_EVENT_SEVERITY_CRITICAL    EventSeverity = 5
)

// Enum value maps for EventSeverity.
var (
	EventSeverity_name = map[int32]string{
		0: "EVENT_SEVERITY_UNSPECIFIED",
		1: "EVENT_SEVERITY_DEBUG",
		2: "EVENT_SEVERITY_INFO",
		3: "EVENT_SEVERITY_WARNING",
		4: "EVENT_SEVERITY_ERROR",
		5: "EVENT_SEVERITY_CRITICAL",
	}
	EventSeverity_value = map[string]int32{
		"EVENT_SEVERITY_UNSPECIFIED": 0,
		"EVENT_SEVERITY_DEBUG":       1,
		"EVENT_SEVERITY_INFO":        2,
		"EVENT_SEVERITY_WARNING":     3,
		"EVENT_SEVERITY_ERROR":       4,
		"EVENT_SEVERITY_CRITICAL":    5,
	}
)

func (x EventSeverity) Enum() *EventSeverity {
	p := new(EventSeverity)
	*p = x
	return p
}

func (x EventSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (EventSeverity) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x EventSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventSeverity.Descriptor instead.
func (EventSeverity) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

// EventCategory groups related event types
type EventCategory int32

const (
	EventCategory_EVENT_CATEGORY_UNSPECIFIED EventCategory = 0
	EventCategory_EVENT_CATEGORY_AGENT       EventCategory = 1
	EventCategory_EVENT_CATEGORY_JOB         EventCategory = 2
	EventCategory_EVENT_CATEGORY_STATE       EventCategory = 3
	EventCategory_EVENT_CATEGORY_USER        EventCategory = 4
	EventCategory_EVENT_CATEGORY_SYSTEM      EventCategory = 5
	EventCategory_EVENT_CATEGORY_POLICY      EventCategory = 6
	EventCategory_EVENT_CATEGORY_GITOPS      EventCategory = 7
)

// Enum value maps for EventCategory.
var (
	EventCategory_name = map[int32]string{
		0: "EVENT_CATEGORY_UNSPECIFIED",
		1: "EVENT_CATEGORY_AGENT",
		2: "EVENT_CATEGORY_JOB",
		3: "EVENT_CATEGORY_STATE",
		4: "EVENT_CATEGORY_USER",
		5: "EVENT_CATEGORY_SYSTEM",
		6: "EVENT_CATEGORY_POLICY",
		7: "EVENT_CATEGORY_GITOPS",
	}
	EventCategory_value = map[string]int32{
		"EVENT_CATEGORY_UNSPECIFIED": 0,
		"EVENT_CATEGORY_AGENT":       1,
		"EVENT_CATEGORY_JOB":         2,
		"EVENT_CATEGORY_STATE":       3,
		"EVENT_CATEGORY_USER":        4,
		"EVENT_CATEGORY_SYSTEM":      5,
		"EVENT_CATEGORY_POLICY":      6,
		"EVENT_CATEGORY_GITOPS":      7,
	}
)

func (x EventCategory) Enum() *EventCategory {
	p := new(EventCategory)
	*p = x
	return p
}

func (x EventCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[1].Descriptor()
}

func (EventCategory) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[1]
}

func (x EventCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventCategory.Descriptor instead.
func (EventCategory) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

// SortOrder defines the sort direction
type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASCENDING   SortOrder = 1
	SortOrder_SORT_ORDER_DESCENDING  SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASCENDING",
		2: "SORT_ORDER_DESCENDING",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASCENDING":   1,
		"SORT_ORDER_DESCENDING":  2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[2].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[2]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

// Event represents a Keystone Core event
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique event ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Event type (e.g., "agent.connect", "state.change")
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Event source (e.g., "/agents/web-01", "/control-plane")
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Event timestamp
	Time *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	// Event severity
	Severity EventSeverity `protobuf:"varint,5,opt,name=severity,proto3,enum=keystone.core.v1.EventSeverity" json:"severity,omitempty"`
	// Correlation ID for linking related events
	CorrelationId string `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Tags for filtering and categorization
	Tags map[string]string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Event-specific data payload
	Data *structpb.Struct `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	// NATS subject (if applicable)
	Subject       string `protobuf:"bytes,9,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Event) GetSeverity() EventSeverity {
	if x != nil {
		return x.Severity
	}
	return EventSeverity_EVENT_SEVERITY_UNSPECIFIED
}

func (x *Event) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Event) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

// ListEventsRequest requests events with filtering
type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by event type (optional)
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Filter by source (optional)
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Filter by severity (optional)
	Severity EventSeverity `protobuf:"varint,3,opt,name=severity,proto3,enum=keystone.core.v1.EventSeverity" json:"severity,omitempty"`
	// Filter by minimum severity (optional)
	MinSeverity EventSeverity `protobuf:"varint,4,opt,name=min_severity,json=minSeverity,proto3,enum=keystone.core.v1.EventSeverity" json:"min_severity,omitempty"`
	// Filter by correlation ID (optional)
	CorrelationId string `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Filter by tags (all must match)
	Tags map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Filter by time range
	StartTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Filter expression (CEL)
	Filter string `protobuf:"bytes,9,opt,name=filter,proto3" json:"filter,omitempty"`
	// Pagination
	PageSize  int32  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Sort order (default: descending by time)
	SortOrder     SortOrder `protobuf:"varint,12,opt,name=sort_order,json=sortOrder,proto3,enum=keystone.core.v1.SortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *ListEventsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListEventsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListEventsRequest) GetSeverity() EventSeverity {
	if x != nil {
		return x.Severity
	}
	return EventSeverity_EVENT_SEVERITY_UNSPECIFIED
}

func (x *ListEventsRequest) GetMinSeverity() EventSeverity {
	if x != nil {
		return x.MinSeverity
	}
	return EventSeverity_EVENT_SEVERITY_UNSPECIFIED
}

func (x *ListEventsRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ListEventsRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListEventsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListEventsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListEventsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListEventsRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

// ListEventsResponse returns a list of events
type ListEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events matching the filter
	Events []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Next page token
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count (may be approximate for large result sets)
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListEventsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetEventRequest requests a specific event
type GetEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event ID
	EventId       string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// GetEventResponse returns a specific event
type GetEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event
	Event         *Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// EmitEventRequest emits a custom event
type EmitEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type (required)
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Event source (required)
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Event severity (default: INFO)
	Severity EventSeverity `protobuf:"varint,3,opt,name=severity,proto3,enum=keystone.core.v1.EventSeverity" json:"severity,omitempty"`
	// Correlation ID (optional)
	CorrelationId string `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Tags for categorization
	Tags map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Event data payload
	Data          *structpb.Struct `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitEventRequest) Reset() {
	*x = EmitEventRequest{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitEventRequest) ProtoMessage() {}

func (x *EmitEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitEventRequest.ProtoReflect.Descriptor instead.
func (*EmitEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *EmitEventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EmitEventRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EmitEventRequest) GetSeverity() EventSeverity {
	if x != nil {
		return x.Severity
	}
	return EventSeverity_EVENT_SEVERITY_UNSPECIFIED
}

func (x *EmitEventRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EmitEventRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EmitEventRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

// EmitEventResponse confirms event emission
type EmitEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generated event ID
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Event timestamp
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitEventResponse) Reset() {
	*x = EmitEventResponse{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitEventResponse) ProtoMessage() {}

func (x *EmitEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitEventResponse.ProtoReflect.Descriptor instead.
func (*EmitEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *EmitEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EmitEventResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// SubscribeEventsRequest subscribes to events
type SubscribeEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by event types (empty = all)
	Types []string `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	// Filter by sources (empty = all)
	Sources []string `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	// Filter by minimum severity
	MinSeverity EventSeverity `protobuf:"varint,3,opt,name=min_severity,json=minSeverity,proto3,enum=keystone.core.v1.EventSeverity" json:"min_severity,omitempty"`
	// Filter by tags (all must match)
	Tags map[string]string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Filter expression (CEL)
	Filter string `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	// Include historical events from the last N seconds (0 = real-time only)
	ReplaySeconds int32 `protobuf:"varint,6,opt,name=replay_seconds,json=replaySeconds,proto3" json:"replay_seconds,omitempty"`
	// Queue group for load balancing (optional)
	QueueGroup    string `protobuf:"bytes,7,opt,name=queue_group,json=queueGroup,proto3" json:"queue_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeEventsRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *SubscribeEventsRequest) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *SubscribeEventsRequest) GetMinSeverity() EventSeverity {
	if x != nil {
		return x.MinSeverity
	}
	return EventSeverity_EVENT_SEVERITY_UNSPECIFIED
}

func (x *SubscribeEventsRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SubscribeEventsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *SubscribeEventsRequest) GetReplaySeconds() int32 {
	if x != nil {
		return x.ReplaySeconds
	}
	return 0
}

func (x *SubscribeEventsRequest) GetQueueGroup() string {
	if x != nil {
		return x.QueueGroup
	}
	return ""
}

// GetEventTypesRequest requests available event types
type GetEventTypesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by category (optional)
	Category      EventCategory `protobuf:"varint,1,opt,name=category,proto3,enum=keystone.core.v1.EventCategory" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventTypesRequest) Reset() {
	*x = GetEventTypesRequest{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventTypesRequest) ProtoMessage() {}

func (x *GetEventTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventTypesRequest.ProtoReflect.Descriptor instead.
func (*GetEventTypesRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventTypesRequest) GetCategory() EventCategory {
	if x != nil {
		return x.Category
	}
	return EventCategory_EVENT_CATEGORY_UNSPECIFIED
}

// GetEventTypesResponse returns available event types
type GetEventTypesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event types
	Types         []*EventTypeInfo `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventTypesResponse) Reset() {
	*x = GetEventTypesResponse{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventTypesResponse) ProtoMessage() {}

func (x *GetEventTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventTypesResponse.ProtoReflect.Descriptor instead.
func (*GetEventTypesResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *GetEventTypesResponse) GetTypes() []*EventTypeInfo {
	if x != nil {
		return x.Types
	}
	return nil
}

// EventTypeInfo describes an event type
type EventTypeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type name
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Category
	Category EventCategory `protobuf:"varint,2,opt,name=category,proto3,enum=keystone.core.v1.EventCategory" json:"category,omitempty"`
	// Description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Example data schema
	DataSchema    string `protobuf:"bytes,4,opt,name=data_schema,json=dataSchema,proto3" json:"data_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTypeInfo) Reset() {
	*x = EventTypeInfo{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypeInfo) ProtoMessage() {}

func (x *EventTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypeInfo.ProtoReflect.Descriptor instead.
func (*EventTypeInfo) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *EventTypeInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventTypeInfo) GetCategory() EventCategory {
	if x != nil {
		return x.Category
	}
	return EventCategory_EVENT_CATEGORY_UNSPECIFIED
}

func (x *EventTypeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventTypeInfo) GetDataSchema() string {
	if x != nil {
		return x.DataSchema
	}
	return ""
}

// GetEventStatsRequest requests event statistics
type GetEventStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time range for statistics
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Group by (type, source, severity, hour, day)
	GroupBy       string `protobuf:"bytes,3,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventStatsRequest) Reset() {
	*x = GetEventStatsRequest{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventStatsRequest) ProtoMessage() {}

func (x *GetEventStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventStatsRequest.ProtoReflect.Descriptor instead.
func (*GetEventStatsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *GetEventStatsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetEventStatsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetEventStatsRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

// GetEventStatsResponse returns event statistics
type GetEventStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total events in time range
	TotalEvents int64 `protobuf:"varint,1,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	// Events by type
	ByType map[string]int64 `protobuf:"bytes,2,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Events by severity
	BySeverity map[string]int64 `protobuf:"bytes,3,rep,name=by_severity,json=bySeverity,proto3" json:"by_severity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Events by source
	BySource map[string]int64 `protobuf:"bytes,4,rep,name=by_source,json=bySource,proto3" json:"by_source,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Event rate (events per second)
	EventRate float32 `protobuf:"fixed32,5,opt,name=event_rate,json=eventRate,proto3" json:"event_rate,omitempty"`
	// Time series data (for charts)
	TimeSeries    []*EventTimeSeries `protobuf:"bytes,6,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventStatsResponse) Reset() {
	*x = GetEventStatsResponse{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventStatsResponse) ProtoMessage() {}

func (x *GetEventStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventStatsResponse.ProtoReflect.Descriptor instead.
func (*GetEventStatsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

func (x *GetEventStatsResponse) GetTotalEvents() int64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *GetEventStatsResponse) GetByType() map[string]int64 {
	if x != nil {
		return x.ByType
	}
	return nil
}

func (x *GetEventStatsResponse) GetBySeverity() map[string]int64 {
	if x != nil {
		return x.BySeverity
	}
	return nil
}

func (x *GetEventStatsResponse) GetBySource() map[string]int64 {
	if x != nil {
		return x.BySource
	}
	return nil
}

func (x *GetEventStatsResponse) GetEventRate() float32 {
	if x != nil {
		return x.EventRate
	}
	return 0
}

func (x *GetEventStatsResponse) GetTimeSeries() []*EventTimeSeries {
	if x != nil {
		return x.TimeSeries
	}
	return nil
}

// EventTimeSeries represents event counts over time
type EventTimeSeries struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp for this bucket
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Event count
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Breakdown by type (optional)
	ByType map[string]int64 `protobuf:"bytes,3,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Breakdown by severity (optional)
	BySeverity    map[string]int64 `protobuf:"bytes,4,rep,name=by_severity,json=bySeverity,proto3" json:"by_severity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTimeSeries) Reset() {
	*x = EventTimeSeries{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTimeSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTimeSeries) ProtoMessage() {}

func (x *EventTimeSeries) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTimeSeries.ProtoReflect.Descriptor instead.
func (*EventTimeSeries) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13}
}

func (x *EventTimeSeries) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventTimeSeries) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EventTimeSeries) GetByType() map[string]int64 {
	if x != nil {
		return x.ByType
	}
	return nil
}

func (x *EventTimeSeries) GetBySeverity() map[string]int64 {
	if x != nil {
		return x.BySeverity
	}
	return nil
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x10keystone.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8e\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12;\n" +
	"\bseverity\x18\x05 \x01(\x0e2\x1f.keystone.core.v1.EventSeverityR\bseverity\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x125\n" +
	"\x04tags\x18\a \x03(\v2!.keystone.core.v1.Event.TagsEntryR\x04tags\x12+\n" +
	"\x04data\x18\b \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x18\n" +
	"\asubject\x18\t \x01(\tR\asubject\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x04\n" +
	"\x11ListEventsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12;\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x1f.keystone.core.v1.EventSeverityR\bseverity\x12B\n" +
	"\fmin_severity\x18\x04 \x01(\x0e2\x1f.keystone.core.v1.EventSeverityR\vminSeverity\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12A\n" +
	"\x04tags\x18\x06 \x03(\v2-.keystone.core.v1.ListEventsRequest.TagsEntryR\x04tags\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x16\n" +
	"\x06filter\x18\t \x01(\tR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\x12:\n" +
	"\n" +
	"sort_order\x18\f \x01(\x0e2\x1b.keystone.core.v1.SortOrderR\tsortOrder\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x12ListEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.keystone.core.v1.EventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\",\n" +
	"\x0fGetEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"A\n" +
	"\x10GetEventResponse\x12-\n" +
	"\x05event\x18\x01 \x01(\v2\x17.keystone.core.v1.EventR\x05event\"\xca\x02\n" +
	"\x10EmitEventRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12;\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x1f.keystone.core.v1.EventSeverityR\bseverity\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12@\n" +
	"\x04tags\x18\x05 \x03(\v2,.keystone.core.v1.EmitEventRequest.TagsEntryR\x04tags\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x11EmitEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xed\x02\n" +
	"\x16SubscribeEventsRequest\x12\x14\n" +
	"\x05types\x18\x01 \x03(\tR\x05types\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\x12B\n" +
	"\fmin_severity\x18\x03 \x01(\x0e2\x1f.keystone.core.v1.EventSeverityR\vminSeverity\x12F\n" +
	"\x04tags\x18\x04 \x03(\v22.keystone.core.v1.SubscribeEventsRequest.TagsEntryR\x04tags\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\tR\x06filter\x12%\n" +
	"\x0ereplay_seconds\x18\x06 \x01(\x05R\rreplaySeconds\x12\x1f\n" +
	"\vqueue_group\x18\a \x01(\tR\n" +
	"queueGroup\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x14GetEventTypesRequest\x12;\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x1f.keystone.core.v1.EventCategoryR\bcategory\"N\n" +
	"\x15GetEventTypesResponse\x125\n" +
	"\x05types\x18\x01 \x03(\v2\x1f.keystone.core.v1.EventTypeInfoR\x05types\"\xa3\x01\n" +
	"\rEventTypeInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12;\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x1f.keystone.core.v1.EventCategoryR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vdata_schema\x18\x04 \x01(\tR\n" +
	"dataSchema\"\xa3\x01\n" +
	"\x14GetEventStatsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x19\n" +
	"\bgroup_by\x18\x03 \x01(\tR\agroupBy\"\xd0\x04\n" +
	"\x15GetEventStatsResponse\x12!\n" +
	"\ftotal_events\x18\x01 \x01(\x03R\vtotalEvents\x12L\n" +
	"\aby_type\x18\x02 \x03(\v23.keystone.core.v1.GetEventStatsResponse.ByTypeEntryR\x06byType\x12X\n" +
	"\vby_severity\x18\x03 \x03(\v27.keystone.core.v1.GetEventStatsResponse.BySeverityEntryR\n" +
	"bySeverity\x12R\n" +
	"\tby_source\x18\x04 \x03(\v25.keystone.core.v1.GetEventStatsResponse.BySourceEntryR\bbySource\x12\x1d\n" +
	"\n" +
	"event_rate\x18\x05 \x01(\x02R\teventRate\x12B\n" +
	"\vtime_series\x18\x06 \x03(\v2!.keystone.core.v1.EventTimeSeriesR\n" +
	"timeSeries\x1a9\n" +
	"\vByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a=\n" +
	"\x0fBySeverityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a;\n" +
	"\rBySourceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xf7\x02\n" +
	"\x0fEventTimeSeries\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12F\n" +
	"\aby_type\x18\x03 \x03(\v2-.keystone.core.v1.EventTimeSeries.ByTypeEntryR\x06byType\x12R\n" +
	"\vby_severity\x18\x04 \x03(\v21.keystone.core.v1.EventTimeSeries.BySeverityEntryR\n" +
	"bySeverity\x1a9\n" +
	"\vByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a=\n" +
	"\x0fBySeverityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01*\xb5\x01\n" +
	"\rEventSeverity\x12\x1e\n" +
	"\x1aEVENT_SEVERITY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EVENT_SEVERITY_DEBUG\x10\x01\x12\x17\n" +
	"\x13EVENT_SEVERITY_INFO\x10\x02\x12\x1a\n" +
	"\x16EVENT_SEVERITY_WARNING\x10\x03\x12\x18\n" +
	"\x14EVENT_SEVERITY_ERROR\x10\x04\x12\x1b\n" +
	"\x17EVENT_SEVERITY_CRITICAL\x10\x05*\xe5\x01\n" +
	"\rEventCategory\x12\x1e\n" +
	"\x1aEVENT_CATEGORY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EVENT_CATEGORY_AGENT\x10\x01\x12\x16\n" +
	"\x12EVENT_CATEGORY_JOB\x10\x02\x12\x18\n" +
	"\x14EVENT_CATEGORY_STATE\x10\x03\x12\x17\n" +
	"\x13EVENT_CATEGORY_USER\x10\x04\x12\x19\n" +
	"\x15EVENT_CATEGORY_SYSTEM\x10\x05\x12\x19\n" +
	"\x15EVENT_CATEGORY_POLICY\x10\x06\x12\x19\n" +
	"\x15EVENT_CATEGORY_GITOPS\x10\a*\\\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SORT_ORDER_ASCENDING\x10\x01\x12\x19\n" +
	"\x15SORT_ORDER_DESCENDING\x10\x022\xac\x04\n" +
	"\fEventService\x12W\n" +
	"\n" +
	"ListEvents\x12#.keystone.core.v1.ListEventsRequest\x1a$.keystone.core.v1.ListEventsResponse\x12Q\n" +
	"\bGetEvent\x12!.keystone.core.v1.GetEventRequest\x1a\".keystone.core.v1.GetEventResponse\x12T\n" +
	"\tEmitEvent\x12\".keystone.core.v1.EmitEventRequest\x1a#.keystone.core.v1.EmitEventResponse\x12V\n" +
	"\x0fSubscribeEvents\x12(.keystone.core.v1.SubscribeEventsRequest\x1a\x17.keystone.core.v1.Event0\x01\x12`\n" +
	"\rGetEventTypes\x12&.keystone.core.v1.GetEventTypesRequest\x1a'.keystone.core.v1.GetEventTypesResponse\x12`\n" +
	"\rGetEventStats\x12&.keystone.core.v1.GetEventStatsRequest\x1a'.keystone.core.v1.GetEventStatsResponseB\xb7\x01\n" +
	"\x14com.keystone.core.v1B\n" +
	"EventProtoP\x01Z1github.com/shawnbutts/keystone-core/pkg/api/v1;v1\xa2\x02\x03KCX\xaa\x02\x10Keystone.Core.V1\xca\x02\x10Keystone\\Core\\V1\xe2\x02\x1cKeystone\\Core\\V1\\GPBMetadata\xea\x02\x12Keystone::Core::V1b\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_event_proto_goTypes = []any{
	(EventSeverity)(0),             // 0: keystone.core.v1.EventSeverity
	(EventCategory)(0),             // 1: keystone.core.v1.EventCategory
	(SortOrder)(0),                 // 2: keystone.core.v1.SortOrder
	(*Event)(nil),                  // 3: keystone.core.v1.Event
	(*ListEventsRequest)(nil),      // 4: keystone.core.v1.ListEventsRequest
	(*ListEventsResponse)(nil),     // 5: keystone.core.v1.ListEventsResponse
	(*GetEventRequest)(nil),        // 6: keystone.core.v1.GetEventRequest
	(*GetEventResponse)(nil),       // 7: keystone.core.v1.GetEventResponse
	(*EmitEventRequest)(nil),       // 8: keystone.core.v1.EmitEventRequest
	(*EmitEventResponse)(nil),      // 9: keystone.core.v1.EmitEventResponse
	(*SubscribeEventsRequest)(nil), // 10: keystone.core.v1.SubscribeEventsRequest
	(*GetEventTypesRequest)(nil),   // 11: keystone.core.v1.GetEventTypesRequest
	(*GetEventTypesResponse)(nil),  // 12: keystone.core.v1.GetEventTypesResponse
	(*EventTypeInfo)(nil),          // 13: keystone.core.v1.EventTypeInfo
	(*GetEventStatsRequest)(nil),   // 14: keystone.core.v1.GetEventStatsRequest
	(*GetEventStatsResponse)(nil),  // 15: keystone.core.v1.GetEventStatsResponse
	(*EventTimeSeries)(nil),        // 16: keystone.core.v1.EventTimeSeries
	nil,                            // 17: keystone.core.v1.Event.TagsEntry
	nil,                            // 18: keystone.core.v1.ListEventsRequest.TagsEntry
	nil,                            // 19: keystone.core.v1.EmitEventRequest.TagsEntry
	nil,                            // 20: keystone.core.v1.SubscribeEventsRequest.TagsEntry
	nil,                            // 21: keystone.core.v1.GetEventStatsResponse.ByTypeEntry
	nil,                            // 22: keystone.core.v1.GetEventStatsResponse.BySeverityEntry
	nil,                            // 23: keystone.core.v1.GetEventStatsResponse.BySourceEntry
	nil,                            // 24: keystone.core.v1.EventTimeSeries.ByTypeEntry
	nil,                            // 25: keystone.core.v1.EventTimeSeries.BySeverityEntry
	(*timestamppb.Timestamp)(nil),  // 26: google.protobuf.Timestamp
	(*structpb.Struct)(nil),        // 27: google.protobuf.Struct
}
var file_event_proto_depIdxs = []int32{
	26, // 0: keystone.core.v1.Event.time:type_name -> google.protobuf.Timestamp
	0,  // 1: keystone.core.v1.Event.severity:type_name -> keystone.core.v1.EventSeverity
	17, // 2: keystone.core.v1.Event.tags:type_name -> keystone.core.v1.Event.TagsEntry
	27, // 3: keystone.core.v1.Event.data:type_name -> google.protobuf.Struct
	0,  // 4: keystone.core.v1.ListEventsRequest.severity:type_name -> keystone.core.v1.EventSeverity
	0,  // 5: keystone.core.v1.ListEventsRequest.min_severity:type_name -> keystone.core.v1.EventSeverity
	18, // 6: keystone.core.v1.ListEventsRequest.tags:type_name -> keystone.core.v1.ListEventsRequest.TagsEntry
	26, // 7: keystone.core.v1.ListEventsRequest.start_time:type_name -> google.protobuf.Timestamp
	26, // 8: keystone.core.v1.ListEventsRequest.end_time:type_name -> google.protobuf.Timestamp
	2,  // 9: keystone.core.v1.ListEventsRequest.sort_order:type_name -> keystone.core.v1.SortOrder
	3,  // 10: keystone.core.v1.ListEventsResponse.events:type_name -> keystone.core.v1.Event
	3,  // 11: keystone.core.v1.GetEventResponse.event:type_name -> keystone.core.v1.Event
	0,  // 12: keystone.core.v1.EmitEventRequest.severity:type_name -> keystone.core.v1.EventSeverity
	19, // 13: keystone.core.v1.EmitEventRequest.tags:type_name -> keystone.core.v1.EmitEventRequest.TagsEntry
	27, // 14: keystone.core.v1.EmitEventRequest.data:type_name -> google.protobuf.Struct
	26, // 15: keystone.core.v1.EmitEventResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 16: keystone.core.v1.SubscribeEventsRequest.min_severity:type_name -> keystone.core.v1.EventSeverity
	20, // 17: keystone.core.v1.SubscribeEventsRequest.tags:type_name -> keystone.core.v1.SubscribeEventsRequest.TagsEntry
	1,  // 18: keystone.core.v1.GetEventTypesRequest.category:type_name -> keystone.core.v1.EventCategory
	13, // 19: keystone.core.v1.GetEventTypesResponse.types:type_name -> keystone.core.v1.EventTypeInfo
	1,  // 20: keystone.core.v1.EventTypeInfo.category:type_name -> keystone.core.v1.EventCategory
	26, // 21: keystone.core.v1.GetEventStatsRequest.start_time:type_name -> google.protobuf.Timestamp
	26, // 22: keystone.core.v1.GetEventStatsRequest.end_time:type_name -> google.protobuf.Timestamp
	21, // 23: keystone.core.v1.GetEventStatsResponse.by_type:type_name -> keystone.core.v1.GetEventStatsResponse.ByTypeEntry
	22, // 24: keystone.core.v1.GetEventStatsResponse.by_severity:type_name -> keystone.core.v1.GetEventStatsResponse.BySeverityEntry
	23, // 25: keystone.core.v1.GetEventStatsResponse.by_source:type_name -> keystone.core.v1.GetEventStatsResponse.BySourceEntry
	16, // 26: keystone.core.v1.GetEventStatsResponse.time_series:type_name -> keystone.core.v1.EventTimeSeries
	26, // 27: keystone.core.v1.EventTimeSeries.timestamp:type_name -> google.protobuf.Timestamp
	24, // 28: keystone.core.v1.EventTimeSeries.by_type:type_name -> keystone.core.v1.EventTimeSeries.ByTypeEntry
	25, // 29: keystone.core.v1.EventTimeSeries.by_severity:type_name -> keystone.core.v1.EventTimeSeries.BySeverityEntry
	4,  // 30: keystone.core.v1.EventService.ListEvents:input_type -> keystone.core.v1.ListEventsRequest
	6,  // 31: keystone.core.v1.EventService.GetEvent:input_type -> keystone.core.v1.GetEventRequest
	8,  // 32: keystone.core.v1.EventService.EmitEvent:input_type -> keystone.core.v1.EmitEventRequest
	10, // 33: keystone.core.v1.EventService.SubscribeEvents:input_type -> keystone.core.v1.SubscribeEventsRequest
	11, // 34: keystone.core.v1.EventService.GetEventTypes:input_type -> keystone.core.v1.GetEventTypesRequest
	14, // 35: keystone.core.v1.EventService.GetEventStats:input_type -> keystone.core.v1.GetEventStatsRequest
	5,  // 36: keystone.core.v1.EventService.ListEvents:output_type -> keystone.core.v1.ListEventsResponse
	7,  // 37: keystone.core.v1.EventService.GetEvent:output_type -> keystone.core.v1.GetEventResponse
	9,  // 38: keystone.core.v1.EventService.EmitEvent:output_type -> keystone.core.v1.EmitEventResponse
	3,  // 39: keystone.core.v1.EventService.SubscribeEvents:output_type -> keystone.core.v1.Event
	12, // 40: keystone.core.v1.EventService.GetEventTypes:output_type -> keystone.core.v1.GetEventTypesResponse
	15, // 41: keystone.core.v1.EventService.GetEventStats:output_type -> keystone.core.v1.GetEventStatsResponse
	36, // [36:42] is the sub-list for method output_type
	30, // [30:36] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
