// IdentityService — operator-facing surface for the Epic 09 identity
// provider. Wraps internal/identity.Provider + JoinTokenStore + CAManager
// so the kscore-identity CLI (and any other operator tooling) can mint
// join tokens, query the CA, and check provider health remotely.
//
// v0.1 ships every method needed by `kscore-identity {token,ca,status}`.
// `federation` RPCs (add-domain / list / fetch-bundle) are post-v1.0 per
// §4.10 and ship under their own ROADMAP entry.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: keystone/core/v1/identity.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportCARequest_What int32

const (
	ExportCARequest_WHAT_UNSPECIFIED ExportCARequest_What = 0
	ExportCARequest_WHAT_ROOT        ExportCARequest_What = 1
	ExportCARequest_WHAT_SIGNING     ExportCARequest_What = 2
	ExportCARequest_WHAT_BUNDLE      ExportCARequest_What = 3 // SPIFFE JWKS-format trust bundle
)

// Enum value maps for ExportCARequest_What.
var (
	ExportCARequest_What_name = map[int32]string{
		0: "WHAT_UNSPECIFIED",
		1: "WHAT_ROOT",
		2: "WHAT_SIGNING",
		3: "WHAT_BUNDLE",
	}
	ExportCARequest_What_value = map[string]int32{
		"WHAT_UNSPECIFIED": 0,
		"WHAT_ROOT":        1,
		"WHAT_SIGNING":     2,
		"WHAT_BUNDLE":      3,
	}
)

func (x ExportCARequest_What) Enum() *ExportCARequest_What {
	p := new(ExportCARequest_What)
	*p = x
	return p
}

func (x ExportCARequest_What) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportCARequest_What) Descriptor() protoreflect.EnumDescriptor {
	return file_keystone_core_v1_identity_proto_enumTypes[0].Descriptor()
}

func (ExportCARequest_What) Type() protoreflect.EnumType {
	return &file_keystone_core_v1_identity_proto_enumTypes[0]
}

func (x ExportCARequest_What) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportCARequest_What.Descriptor instead.
func (ExportCARequest_What) EnumDescriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{14, 0}
}

type CreateJoinTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AgentID binds the token to a specific agent identifier.
	// Required in v0.1; "any-agent" mode is a v0.x ROADMAP item.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// TTL is the token's lifetime. 0 → DefaultJoinTokenTTL (5m).
	// Values above MaxJoinTokenTTL (24h) are rejected.
	TtlSeconds int64 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// MaxUses caps how many agents may use the token. 0 →
	// DefaultJoinTokenMaxUses (1).
	MaxUses int32 `protobuf:"varint,3,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	// Metadata is operator-supplied free-form tags surfaced through
	// ListJoinTokens + the attestor's selectors. Keys + values are
	// both strings.
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenRequest) Reset() {
	*x = CreateJoinTokenRequest{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenRequest) ProtoMessage() {}

func (x *CreateJoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJoinTokenRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateJoinTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *CreateJoinTokenRequest) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *CreateJoinTokenRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateJoinTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The minted JoinToken. The `token` cleartext is populated ONLY
	// in this response; subsequent ListJoinTokens calls return the
	// record with `token` cleared.
	Token         *JoinToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenResponse) Reset() {
	*x = CreateJoinTokenResponse{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenResponse) ProtoMessage() {}

func (x *CreateJoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJoinTokenResponse) GetToken() *JoinToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type ListJoinTokensRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AgentID filter — empty means "any agent."
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// unused = only tokens whose UsedCount < MaxUses.
	Unused bool `protobuf:"varint,2,opt,name=unused,proto3" json:"unused,omitempty"`
	// unexpired_at — if non-zero, only tokens whose ExpiresAt > this.
	UnexpiredAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=unexpired_at,json=unexpiredAt,proto3" json:"unexpired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJoinTokensRequest) Reset() {
	*x = ListJoinTokensRequest{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJoinTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJoinTokensRequest) ProtoMessage() {}

func (x *ListJoinTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJoinTokensRequest.ProtoReflect.Descriptor instead.
func (*ListJoinTokensRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *ListJoinTokensRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListJoinTokensRequest) GetUnused() bool {
	if x != nil {
		return x.Unused
	}
	return false
}

func (x *ListJoinTokensRequest) GetUnexpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UnexpiredAt
	}
	return nil
}

type ListJoinTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*JoinToken           `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJoinTokensResponse) Reset() {
	*x = ListJoinTokensResponse{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJoinTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJoinTokensResponse) ProtoMessage() {}

func (x *ListJoinTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJoinTokensResponse.ProtoReflect.Descriptor instead.
func (*ListJoinTokensResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *ListJoinTokensResponse) GetTokens() []*JoinToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type DeleteJoinTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJoinTokenRequest) Reset() {
	*x = DeleteJoinTokenRequest{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJoinTokenRequest) ProtoMessage() {}

func (x *DeleteJoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJoinTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteJoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteJoinTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteJoinTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJoinTokenResponse) Reset() {
	*x = DeleteJoinTokenResponse{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJoinTokenResponse) ProtoMessage() {}

func (x *DeleteJoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJoinTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteJoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{5}
}

type CleanupJoinTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupJoinTokensRequest) Reset() {
	*x = CleanupJoinTokensRequest{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupJoinTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupJoinTokensRequest) ProtoMessage() {}

func (x *CleanupJoinTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupJoinTokensRequest.ProtoReflect.Descriptor instead.
func (*CleanupJoinTokensRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{6}
}

type CleanupJoinTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       int32                  `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupJoinTokensResponse) Reset() {
	*x = CleanupJoinTokensResponse{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupJoinTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupJoinTokensResponse) ProtoMessage() {}

func (x *CleanupJoinTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupJoinTokensResponse.ProtoReflect.Descriptor instead.
func (*CleanupJoinTokensResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *CleanupJoinTokensResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

// JoinToken is the wire shape of internal/identity.JoinToken. The
// cleartext `token` field is populated only in
// CreateJoinTokenResponse — every other RPC returns it empty.
type JoinToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// token is the cleartext token. Populated ONLY in
	// CreateJoinTokenResponse.token; List / status responses never
	// return it.
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Salt          []byte                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	Prefix        string                 `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	AgentId       string                 `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,7,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	UsedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=used_at,json=usedAt,proto3" json:"used_at,omitempty"` // nil when never used
	MaxUses       int32                  `protobuf:"varint,11,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	UsedCount     int32                  `protobuf:"varint,12,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinToken) Reset() {
	*x = JoinToken{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToken) ProtoMessage() {}

func (x *JoinToken) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToken.ProtoReflect.Descriptor instead.
func (*JoinToken) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *JoinToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoinToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinToken) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *JoinToken) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *JoinToken) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *JoinToken) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *JoinToken) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *JoinToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JoinToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *JoinToken) GetUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UsedAt
	}
	return nil
}

func (x *JoinToken) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *JoinToken) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *JoinToken) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetCAInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCAInfoRequest) Reset() {
	*x = GetCAInfoRequest{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCAInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCAInfoRequest) ProtoMessage() {}

func (x *GetCAInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCAInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCAInfoRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{9}
}

type GetCAInfoResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	Root        *CACertInfo            `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Signing     *CACertInfo            `protobuf:"bytes,3,opt,name=signing,proto3" json:"signing,omitempty"`
	// jwt_kid is the kid the provider uses when signing JWT-SVIDs.
	// Derived from the signing CA's serial — rotates with it.
	JwtKid        string `protobuf:"bytes,4,opt,name=jwt_kid,json=jwtKid,proto3" json:"jwt_kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCAInfoResponse) Reset() {
	*x = GetCAInfoResponse{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCAInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCAInfoResponse) ProtoMessage() {}

func (x *GetCAInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCAInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCAInfoResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{10}
}

func (x *GetCAInfoResponse) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *GetCAInfoResponse) GetRoot() *CACertInfo {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *GetCAInfoResponse) GetSigning() *CACertInfo {
	if x != nil {
		return x.Signing
	}
	return nil
}

func (x *GetCAInfoResponse) GetJwtKid() string {
	if x != nil {
		return x.JwtKid
	}
	return ""
}

// CACertInfo is the subset of x509.Certificate fields operators
// need to evaluate CA health (subject, expiry, key type). PEM is
// available separately via ExportCA.
type CACertInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Subject   string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Serial    string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"` // big.Int.Text(16) — short hex form
	NotBefore *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// key_type is the human-readable algorithm (e.g. "ECDSA-P256",
	// "RSA-2048").
	KeyType       string `protobuf:"bytes,5,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CACertInfo) Reset() {
	*x = CACertInfo{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CACertInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CACertInfo) ProtoMessage() {}

func (x *CACertInfo) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CACertInfo.ProtoReflect.Descriptor instead.
func (*CACertInfo) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{11}
}

func (x *CACertInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CACertInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *CACertInfo) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CACertInfo) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CACertInfo) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

type RotateSigningCARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSigningCARequest) Reset() {
	*x = RotateSigningCARequest{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSigningCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSigningCARequest) ProtoMessage() {}

func (x *RotateSigningCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSigningCARequest.ProtoReflect.Descriptor instead.
func (*RotateSigningCARequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{12}
}

type RotateSigningCAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewSigning    *CACertInfo            `protobuf:"bytes,1,opt,name=new_signing,json=newSigning,proto3" json:"new_signing,omitempty"`
	NewJwtKid     string                 `protobuf:"bytes,2,opt,name=new_jwt_kid,json=newJwtKid,proto3" json:"new_jwt_kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSigningCAResponse) Reset() {
	*x = RotateSigningCAResponse{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSigningCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSigningCAResponse) ProtoMessage() {}

func (x *RotateSigningCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSigningCAResponse.ProtoReflect.Descriptor instead.
func (*RotateSigningCAResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{13}
}

func (x *RotateSigningCAResponse) GetNewSigning() *CACertInfo {
	if x != nil {
		return x.NewSigning
	}
	return nil
}

func (x *RotateSigningCAResponse) GetNewJwtKid() string {
	if x != nil {
		return x.NewJwtKid
	}
	return ""
}

type ExportCARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	What          ExportCARequest_What   `protobuf:"varint,1,opt,name=what,proto3,enum=keystone.core.v1.ExportCARequest_What" json:"what,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportCARequest) Reset() {
	*x = ExportCARequest{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportCARequest) ProtoMessage() {}

func (x *ExportCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportCARequest.ProtoReflect.Descriptor instead.
func (*ExportCARequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{14}
}

func (x *ExportCARequest) GetWhat() ExportCARequest_What {
	if x != nil {
		return x.What
	}
	return ExportCARequest_WHAT_UNSPECIFIED
}

type ExportCAResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pem holds the requested material as PEM bytes (for ROOT /
	// SIGNING) or as JWKS JSON bytes (for BUNDLE — operators that
	// need PEM derive it via ROOT).
	Pem           []byte `protobuf:"bytes,1,opt,name=pem,proto3" json:"pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportCAResponse) Reset() {
	*x = ExportCAResponse{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportCAResponse) ProtoMessage() {}

func (x *ExportCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportCAResponse.ProtoReflect.Descriptor instead.
func (*ExportCAResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{15}
}

func (x *ExportCAResponse) GetPem() []byte {
	if x != nil {
		return x.Pem
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{16}
}

type GetStatusResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Started     bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	TrustDomain string                 `protobuf:"bytes,2,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	StartedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// root_expires_at + signing_expires_at — same fields as
	// GetCAInfo, surfaced here for one-call health checks.
	RootExpiresAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=root_expires_at,json=rootExpiresAt,proto3" json:"root_expires_at,omitempty"`
	SigningExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=signing_expires_at,json=signingExpiresAt,proto3" json:"signing_expires_at,omitempty"`
	// watcher_count is the live trust-bundle subscriber count.
	WatcherCount int32 `protobuf:"varint,6,opt,name=watcher_count,json=watcherCount,proto3" json:"watcher_count,omitempty"`
	// token_total / unused / expired snapshot the store state at the
	// moment of the call.
	TokenTotal    int32 `protobuf:"varint,7,opt,name=token_total,json=tokenTotal,proto3" json:"token_total,omitempty"`
	TokenUnused   int32 `protobuf:"varint,8,opt,name=token_unused,json=tokenUnused,proto3" json:"token_unused,omitempty"`
	TokenExpired  int32 `protobuf:"varint,9,opt,name=token_expired,json=tokenExpired,proto3" json:"token_expired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_keystone_core_v1_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_identity_proto_rawDescGZIP(), []int{17}
}

func (x *GetStatusResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *GetStatusResponse) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *GetStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetStatusResponse) GetRootExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RootExpiresAt
	}
	return nil
}

func (x *GetStatusResponse) GetSigningExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SigningExpiresAt
	}
	return nil
}

func (x *GetStatusResponse) GetWatcherCount() int32 {
	if x != nil {
		return x.WatcherCount
	}
	return 0
}

func (x *GetStatusResponse) GetTokenTotal() int32 {
	if x != nil {
		return x.TokenTotal
	}
	return 0
}

func (x *GetStatusResponse) GetTokenUnused() int32 {
	if x != nil {
		return x.TokenUnused
	}
	return 0
}

func (x *GetStatusResponse) GetTokenExpired() int32 {
	if x != nil {
		return x.TokenExpired
	}
	return 0
}

var File_keystone_core_v1_identity_proto protoreflect.FileDescriptor

const file_keystone_core_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1fkeystone/core/v1/identity.proto\x12\x10keystone.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x02\n" +
	"\x16CreateJoinTokenRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\x12\x19\n" +
	"\bmax_uses\x18\x03 \x01(\x05R\amaxUses\x12R\n" +
	"\bmetadata\x18\x04 \x03(\v26.keystone.core.v1.CreateJoinTokenRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x17CreateJoinTokenResponse\x121\n" +
	"\x05token\x18\x01 \x01(\v2\x1b.keystone.core.v1.JoinTokenR\x05token\"\x89\x01\n" +
	"\x15ListJoinTokensRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06unused\x18\x02 \x01(\bR\x06unused\x12=\n" +
	"\funexpired_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vunexpiredAt\"M\n" +
	"\x16ListJoinTokensResponse\x123\n" +
	"\x06tokens\x18\x01 \x03(\v2\x1b.keystone.core.v1.JoinTokenR\x06tokens\"(\n" +
	"\x16DeleteJoinTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DeleteJoinTokenResponse\"\x1a\n" +
	"\x18CleanupJoinTokensRequest\"5\n" +
	"\x19CleanupJoinTokensResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\x05R\aremoved\"\x96\x04\n" +
	"\tJoinToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\fR\x04salt\x12\x16\n" +
	"\x06prefix\x18\x05 \x01(\tR\x06prefix\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\tR\aagentId\x12\x1f\n" +
	"\vttl_seconds\x18\a \x01(\x03R\n" +
	"ttlSeconds\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x123\n" +
	"\aused_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06usedAt\x12\x19\n" +
	"\bmax_uses\x18\v \x01(\x05R\amaxUses\x12\x1d\n" +
	"\n" +
	"used_count\x18\f \x01(\x05R\tusedCount\x12E\n" +
	"\bmetadata\x18\r \x03(\v2).keystone.core.v1.JoinToken.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x12\n" +
	"\x10GetCAInfoRequest\"\xb9\x01\n" +
	"\x11GetCAInfoResponse\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\x120\n" +
	"\x04root\x18\x02 \x01(\v2\x1c.keystone.core.v1.CACertInfoR\x04root\x126\n" +
	"\asigning\x18\x03 \x01(\v2\x1c.keystone.core.v1.CACertInfoR\asigning\x12\x17\n" +
	"\ajwt_kid\x18\x04 \x01(\tR\x06jwtKid\"\xcd\x01\n" +
	"\n" +
	"CACertInfo\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x129\n" +
	"\n" +
	"not_before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x19\n" +
	"\bkey_type\x18\x05 \x01(\tR\akeyType\"\x18\n" +
	"\x16RotateSigningCARequest\"x\n" +
	"\x17RotateSigningCAResponse\x12=\n" +
	"\vnew_signing\x18\x01 \x01(\v2\x1c.keystone.core.v1.CACertInfoR\n" +
	"newSigning\x12\x1e\n" +
	"\vnew_jwt_kid\x18\x02 \x01(\tR\tnewJwtKid\"\x9d\x01\n" +
	"\x0fExportCARequest\x12:\n" +
	"\x04what\x18\x01 \x01(\x0e2&.keystone.core.v1.ExportCARequest.WhatR\x04what\"N\n" +
	"\x04What\x12\x14\n" +
	"\x10WHAT_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tWHAT_ROOT\x10\x01\x12\x10\n" +
	"\fWHAT_SIGNING\x10\x02\x12\x0f\n" +
	"\vWHAT_BUNDLE\x10\x03\"$\n" +
	"\x10ExportCAResponse\x12\x10\n" +
	"\x03pem\x18\x01 \x01(\fR\x03pem\"\x12\n" +
	"\x10GetStatusRequest\"\xa7\x03\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12!\n" +
	"\ftrust_domain\x18\x02 \x01(\tR\vtrustDomain\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12B\n" +
	"\x0froot_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rrootExpiresAt\x12H\n" +
	"\x12signing_expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x10signingExpiresAt\x12#\n" +
	"\rwatcher_count\x18\x06 \x01(\x05R\fwatcherCount\x12\x1f\n" +
	"\vtoken_total\x18\a \x01(\x05R\n" +
	"tokenTotal\x12!\n" +
	"\ftoken_unused\x18\b \x01(\x05R\vtokenUnused\x12#\n" +
	"\rtoken_expired\x18\t \x01(\x05R\ftokenExpired2\x9b\x06\n" +
	"\x0fIdentityService\x12f\n" +
	"\x0fCreateJoinToken\x12(.keystone.core.v1.CreateJoinTokenRequest\x1a).keystone.core.v1.CreateJoinTokenResponse\x12c\n" +
	"\x0eListJoinTokens\x12'.keystone.core.v1.ListJoinTokensRequest\x1a(.keystone.core.v1.ListJoinTokensResponse\x12f\n" +
	"\x0fDeleteJoinToken\x12(.keystone.core.v1.DeleteJoinTokenRequest\x1a).keystone.core.v1.DeleteJoinTokenResponse\x12l\n" +
	"\x11CleanupJoinTokens\x12*.keystone.core.v1.CleanupJoinTokensRequest\x1a+.keystone.core.v1.CleanupJoinTokensResponse\x12T\n" +
	"\tGetCAInfo\x12\".keystone.core.v1.GetCAInfoRequest\x1a#.keystone.core.v1.GetCAInfoResponse\x12f\n" +
	"\x0fRotateSigningCA\x12(.keystone.core.v1.RotateSigningCARequest\x1a).keystone.core.v1.RotateSigningCAResponse\x12Q\n" +
	"\bExportCA\x12!.keystone.core.v1.ExportCARequest\x1a\".keystone.core.v1.ExportCAResponse\x12T\n" +
	"\tGetStatus\x12\".keystone.core.v1.GetStatusRequest\x1a#.keystone.core.v1.GetStatusResponseB1Z/go.keystone-core.io/keystone-core/pkg/api/v1;v1b\x06proto3"

var (
	file_keystone_core_v1_identity_proto_rawDescOnce sync.Once
	file_keystone_core_v1_identity_proto_rawDescData []byte
)

func file_keystone_core_v1_identity_proto_rawDescGZIP() []byte {
	file_keystone_core_v1_identity_proto_rawDescOnce.Do(func() {
		file_keystone_core_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keystone_core_v1_identity_proto_rawDesc), len(file_keystone_core_v1_identity_proto_rawDesc)))
	})
	return file_keystone_core_v1_identity_proto_rawDescData
}

var file_keystone_core_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keystone_core_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_keystone_core_v1_identity_proto_goTypes = []any{
	(ExportCARequest_What)(0),         // 0: keystone.core.v1.ExportCARequest.What
	(*CreateJoinTokenRequest)(nil),    // 1: keystone.core.v1.CreateJoinTokenRequest
	(*CreateJoinTokenResponse)(nil),   // 2: keystone.core.v1.CreateJoinTokenResponse
	(*ListJoinTokensRequest)(nil),     // 3: keystone.core.v1.ListJoinTokensRequest
	(*ListJoinTokensResponse)(nil),    // 4: keystone.core.v1.ListJoinTokensResponse
	(*DeleteJoinTokenRequest)(nil),    // 5: keystone.core.v1.DeleteJoinTokenRequest
	(*DeleteJoinTokenResponse)(nil),   // 6: keystone.core.v1.DeleteJoinTokenResponse
	(*CleanupJoinTokensRequest)(nil),  // 7: keystone.core.v1.CleanupJoinTokensRequest
	(*CleanupJoinTokensResponse)(nil), // 8: keystone.core.v1.CleanupJoinTokensResponse
	(*JoinToken)(nil),                 // 9: keystone.core.v1.JoinToken
	(*GetCAInfoRequest)(nil),          // 10: keystone.core.v1.GetCAInfoRequest
	(*GetCAInfoResponse)(nil),         // 11: keystone.core.v1.GetCAInfoResponse
	(*CACertInfo)(nil),                // 12: keystone.core.v1.CACertInfo
	(*RotateSigningCARequest)(nil),    // 13: keystone.core.v1.RotateSigningCARequest
	(*RotateSigningCAResponse)(nil),   // 14: keystone.core.v1.RotateSigningCAResponse
	(*ExportCARequest)(nil),           // 15: keystone.core.v1.ExportCARequest
	(*ExportCAResponse)(nil),          // 16: keystone.core.v1.ExportCAResponse
	(*GetStatusRequest)(nil),          // 17: keystone.core.v1.GetStatusRequest
	(*GetStatusResponse)(nil),         // 18: keystone.core.v1.GetStatusResponse
	nil,                               // 19: keystone.core.v1.CreateJoinTokenRequest.MetadataEntry
	nil,                               // 20: keystone.core.v1.JoinToken.MetadataEntry
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
}
var file_keystone_core_v1_identity_proto_depIdxs = []int32{
	19, // 0: keystone.core.v1.CreateJoinTokenRequest.metadata:type_name -> keystone.core.v1.CreateJoinTokenRequest.MetadataEntry
	9,  // 1: keystone.core.v1.CreateJoinTokenResponse.token:type_name -> keystone.core.v1.JoinToken
	21, // 2: keystone.core.v1.ListJoinTokensRequest.unexpired_at:type_name -> google.protobuf.Timestamp
	9,  // 3: keystone.core.v1.ListJoinTokensResponse.tokens:type_name -> keystone.core.v1.JoinToken
	21, // 4: keystone.core.v1.JoinToken.created_at:type_name -> google.protobuf.Timestamp
	21, // 5: keystone.core.v1.JoinToken.expires_at:type_name -> google.protobuf.Timestamp
	21, // 6: keystone.core.v1.JoinToken.used_at:type_name -> google.protobuf.Timestamp
	20, // 7: keystone.core.v1.JoinToken.metadata:type_name -> keystone.core.v1.JoinToken.MetadataEntry
	12, // 8: keystone.core.v1.GetCAInfoResponse.root:type_name -> keystone.core.v1.CACertInfo
	12, // 9: keystone.core.v1.GetCAInfoResponse.signing:type_name -> keystone.core.v1.CACertInfo
	21, // 10: keystone.core.v1.CACertInfo.not_before:type_name -> google.protobuf.Timestamp
	21, // 11: keystone.core.v1.CACertInfo.not_after:type_name -> google.protobuf.Timestamp
	12, // 12: keystone.core.v1.RotateSigningCAResponse.new_signing:type_name -> keystone.core.v1.CACertInfo
	0,  // 13: keystone.core.v1.ExportCARequest.what:type_name -> keystone.core.v1.ExportCARequest.What
	21, // 14: keystone.core.v1.GetStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	21, // 15: keystone.core.v1.GetStatusResponse.root_expires_at:type_name -> google.protobuf.Timestamp
	21, // 16: keystone.core.v1.GetStatusResponse.signing_expires_at:type_name -> google.protobuf.Timestamp
	1,  // 17: keystone.core.v1.IdentityService.CreateJoinToken:input_type -> keystone.core.v1.CreateJoinTokenRequest
	3,  // 18: keystone.core.v1.IdentityService.ListJoinTokens:input_type -> keystone.core.v1.ListJoinTokensRequest
	5,  // 19: keystone.core.v1.IdentityService.DeleteJoinToken:input_type -> keystone.core.v1.DeleteJoinTokenRequest
	7,  // 20: keystone.core.v1.IdentityService.CleanupJoinTokens:input_type -> keystone.core.v1.CleanupJoinTokensRequest
	10, // 21: keystone.core.v1.IdentityService.GetCAInfo:input_type -> keystone.core.v1.GetCAInfoRequest
	13, // 22: keystone.core.v1.IdentityService.RotateSigningCA:input_type -> keystone.core.v1.RotateSigningCARequest
	15, // 23: keystone.core.v1.IdentityService.ExportCA:input_type -> keystone.core.v1.ExportCARequest
	17, // 24: keystone.core.v1.IdentityService.GetStatus:input_type -> keystone.core.v1.GetStatusRequest
	2,  // 25: keystone.core.v1.IdentityService.CreateJoinToken:output_type -> keystone.core.v1.CreateJoinTokenResponse
	4,  // 26: keystone.core.v1.IdentityService.ListJoinTokens:output_type -> keystone.core.v1.ListJoinTokensResponse
	6,  // 27: keystone.core.v1.IdentityService.DeleteJoinToken:output_type -> keystone.core.v1.DeleteJoinTokenResponse
	8,  // 28: keystone.core.v1.IdentityService.CleanupJoinTokens:output_type -> keystone.core.v1.CleanupJoinTokensResponse
	11, // 29: keystone.core.v1.IdentityService.GetCAInfo:output_type -> keystone.core.v1.GetCAInfoResponse
	14, // 30: keystone.core.v1.IdentityService.RotateSigningCA:output_type -> keystone.core.v1.RotateSigningCAResponse
	16, // 31: keystone.core.v1.IdentityService.ExportCA:output_type -> keystone.core.v1.ExportCAResponse
	18, // 32: keystone.core.v1.IdentityService.GetStatus:output_type -> keystone.core.v1.GetStatusResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_keystone_core_v1_identity_proto_init() }
func file_keystone_core_v1_identity_proto_init() {
	if File_keystone_core_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keystone_core_v1_identity_proto_rawDesc), len(file_keystone_core_v1_identity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keystone_core_v1_identity_proto_goTypes,
		DependencyIndexes: file_keystone_core_v1_identity_proto_depIdxs,
		EnumInfos:         file_keystone_core_v1_identity_proto_enumTypes,
		MessageInfos:      file_keystone_core_v1_identity_proto_msgTypes,
	}.Build()
	File_keystone_core_v1_identity_proto = out.File
	file_keystone_core_v1_identity_proto_goTypes = nil
	file_keystone_core_v1_identity_proto_depIdxs = nil
}
