// Placeholder proto used to verify buf codegen wiring in epic 01 task 11.
// Replaced by real service protos (agent, controlplane, state, event, policy,
// secrets, cluster, coordination) in epic 03.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: keystone/core/v1/placeholder.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Placeholder is a stand-in message that exists solely to give the codegen
// pipeline something to compile. It carries no fields and has no users.
type Placeholder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placeholder) Reset() {
	*x = Placeholder{}
	mi := &file_keystone_core_v1_placeholder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placeholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placeholder) ProtoMessage() {}

func (x *Placeholder) ProtoReflect() protoreflect.Message {
	mi := &file_keystone_core_v1_placeholder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placeholder.ProtoReflect.Descriptor instead.
func (*Placeholder) Descriptor() ([]byte, []int) {
	return file_keystone_core_v1_placeholder_proto_rawDescGZIP(), []int{0}
}

var File_keystone_core_v1_placeholder_proto protoreflect.FileDescriptor

const file_keystone_core_v1_placeholder_proto_rawDesc = "" +
	"\n" +
	"\"keystone/core/v1/placeholder.proto\x12\x10keystone.core.v1\"\r\n" +
	"\vPlaceholderB1Z/go.keystone-core.io/keystone-core/pkg/api/v1;v1b\x06proto3"

var (
	file_keystone_core_v1_placeholder_proto_rawDescOnce sync.Once
	file_keystone_core_v1_placeholder_proto_rawDescData []byte
)

func file_keystone_core_v1_placeholder_proto_rawDescGZIP() []byte {
	file_keystone_core_v1_placeholder_proto_rawDescOnce.Do(func() {
		file_keystone_core_v1_placeholder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keystone_core_v1_placeholder_proto_rawDesc), len(file_keystone_core_v1_placeholder_proto_rawDesc)))
	})
	return file_keystone_core_v1_placeholder_proto_rawDescData
}

var file_keystone_core_v1_placeholder_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_keystone_core_v1_placeholder_proto_goTypes = []any{
	(*Placeholder)(nil), // 0: keystone.core.v1.Placeholder
}
var file_keystone_core_v1_placeholder_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keystone_core_v1_placeholder_proto_init() }
func file_keystone_core_v1_placeholder_proto_init() {
	if File_keystone_core_v1_placeholder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keystone_core_v1_placeholder_proto_rawDesc), len(file_keystone_core_v1_placeholder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keystone_core_v1_placeholder_proto_goTypes,
		DependencyIndexes: file_keystone_core_v1_placeholder_proto_depIdxs,
		MessageInfos:      file_keystone_core_v1_placeholder_proto_msgTypes,
	}.Build()
	File_keystone_core_v1_placeholder_proto = out.File
	file_keystone_core_v1_placeholder_proto_goTypes = nil
	file_keystone_core_v1_placeholder_proto_depIdxs = nil
}
