// StateService — declarative state management RPCs. Epic 08 (State
// Management & Stdlib) ships these.
//
// Wire format: clients submit raw YAML via yaml_content; the server
// compiles via the statemgmt pipeline (Parse → Render → Validate →
// Resolve → Run / Check / Drift). Includes in the YAML are rejected
// in v1.0 — server-side library directories are a v1.x extension.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: keystone/core/v1/state.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StateService_ApplyState_FullMethodName      = "/keystone.core.v1.StateService/ApplyState"
	StateService_CheckState_FullMethodName      = "/keystone.core.v1.StateService/CheckState"
	StateService_DetectDrift_FullMethodName     = "/keystone.core.v1.StateService/DetectDrift"
	StateService_GetStateHistory_FullMethodName = "/keystone.core.v1.StateService/GetStateHistory"
	StateService_GetStateStatus_FullMethodName  = "/keystone.core.v1.StateService/GetStateStatus"
)

// StateServiceClient is the client API for StateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateServiceClient interface {
	// ApplyState compiles + applies a YAML state file. Streams per-
	// declaration outcomes as the runner progresses, then closes with
	// a terminal event.
	ApplyState(ctx context.Context, in *ApplyStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApplyStateResponse], error)
	// CheckState compiles the file and runs the Check phase only.
	// Returns drift / unchanged per declaration without mutating.
	CheckState(ctx context.Context, in *CheckStateRequest, opts ...grpc.CallOption) (*CheckStateResponse, error)
	// DetectDrift compiles the file, runs Check, and adds per-decl
	// severity classification + aggregate severity.
	DetectDrift(ctx context.Context, in *DetectDriftRequest, opts ...grpc.CallOption) (*DetectDriftResponse, error)
	// GetStateHistory lists past runs (headers only, no per-decl
	// results). Use GetStateStatus to hydrate a specific run.
	GetStateHistory(ctx context.Context, in *GetStateHistoryRequest, opts ...grpc.CallOption) (*GetStateHistoryResponse, error)
	// GetStateStatus returns one run's header plus all its per-decl
	// results.
	GetStateStatus(ctx context.Context, in *GetStateStatusRequest, opts ...grpc.CallOption) (*GetStateStatusResponse, error)
}

type stateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateServiceClient(cc grpc.ClientConnInterface) StateServiceClient {
	return &stateServiceClient{cc}
}

func (c *stateServiceClient) ApplyState(ctx context.Context, in *ApplyStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApplyStateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateService_ServiceDesc.Streams[0], StateService_ApplyState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApplyStateRequest, ApplyStateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateService_ApplyStateClient = grpc.ServerStreamingClient[ApplyStateResponse]

func (c *stateServiceClient) CheckState(ctx context.Context, in *CheckStateRequest, opts ...grpc.CallOption) (*CheckStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckStateResponse)
	err := c.cc.Invoke(ctx, StateService_CheckState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) DetectDrift(ctx context.Context, in *DetectDriftRequest, opts ...grpc.CallOption) (*DetectDriftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectDriftResponse)
	err := c.cc.Invoke(ctx, StateService_DetectDrift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetStateHistory(ctx context.Context, in *GetStateHistoryRequest, opts ...grpc.CallOption) (*GetStateHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateHistoryResponse)
	err := c.cc.Invoke(ctx, StateService_GetStateHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetStateStatus(ctx context.Context, in *GetStateStatusRequest, opts ...grpc.CallOption) (*GetStateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateStatusResponse)
	err := c.cc.Invoke(ctx, StateService_GetStateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateServiceServer is the server API for StateService service.
// All implementations must embed UnimplementedStateServiceServer
// for forward compatibility.
type StateServiceServer interface {
	// ApplyState compiles + applies a YAML state file. Streams per-
	// declaration outcomes as the runner progresses, then closes with
	// a terminal event.
	ApplyState(*ApplyStateRequest, grpc.ServerStreamingServer[ApplyStateResponse]) error
	// CheckState compiles the file and runs the Check phase only.
	// Returns drift / unchanged per declaration without mutating.
	CheckState(context.Context, *CheckStateRequest) (*CheckStateResponse, error)
	// DetectDrift compiles the file, runs Check, and adds per-decl
	// severity classification + aggregate severity.
	DetectDrift(context.Context, *DetectDriftRequest) (*DetectDriftResponse, error)
	// GetStateHistory lists past runs (headers only, no per-decl
	// results). Use GetStateStatus to hydrate a specific run.
	GetStateHistory(context.Context, *GetStateHistoryRequest) (*GetStateHistoryResponse, error)
	// GetStateStatus returns one run's header plus all its per-decl
	// results.
	GetStateStatus(context.Context, *GetStateStatusRequest) (*GetStateStatusResponse, error)
	mustEmbedUnimplementedStateServiceServer()
}

// UnimplementedStateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateServiceServer struct{}

func (UnimplementedStateServiceServer) ApplyState(*ApplyStateRequest, grpc.ServerStreamingServer[ApplyStateResponse]) error {
	return status.Error(codes.Unimplemented, "method ApplyState not implemented")
}
func (UnimplementedStateServiceServer) CheckState(context.Context, *CheckStateRequest) (*CheckStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckState not implemented")
}
func (UnimplementedStateServiceServer) DetectDrift(context.Context, *DetectDriftRequest) (*DetectDriftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectDrift not implemented")
}
func (UnimplementedStateServiceServer) GetStateHistory(context.Context, *GetStateHistoryRequest) (*GetStateHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStateHistory not implemented")
}
func (UnimplementedStateServiceServer) GetStateStatus(context.Context, *GetStateStatusRequest) (*GetStateStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStateStatus not implemented")
}
func (UnimplementedStateServiceServer) mustEmbedUnimplementedStateServiceServer() {}
func (UnimplementedStateServiceServer) testEmbeddedByValue()                      {}

// UnsafeStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateServiceServer will
// result in compilation errors.
type UnsafeStateServiceServer interface {
	mustEmbedUnimplementedStateServiceServer()
}

func RegisterStateServiceServer(s grpc.ServiceRegistrar, srv StateServiceServer) {
	// If the following call panics, it indicates UnimplementedStateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateService_ServiceDesc, srv)
}

func _StateService_ApplyState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApplyStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateServiceServer).ApplyState(m, &grpc.GenericServerStream[ApplyStateRequest, ApplyStateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateService_ApplyStateServer = grpc.ServerStreamingServer[ApplyStateResponse]

func _StateService_CheckState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).CheckState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_CheckState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).CheckState(ctx, req.(*CheckStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_DetectDrift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectDriftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).DetectDrift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_DetectDrift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).DetectDrift(ctx, req.(*DetectDriftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetStateHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetStateHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetStateHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetStateHistory(ctx, req.(*GetStateHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetStateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetStateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetStateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetStateStatus(ctx, req.(*GetStateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StateService_ServiceDesc is the grpc.ServiceDesc for StateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keystone.core.v1.StateService",
	HandlerType: (*StateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckState",
			Handler:    _StateService_CheckState_Handler,
		},
		{
			MethodName: "DetectDrift",
			Handler:    _StateService_DetectDrift_Handler,
		},
		{
			MethodName: "GetStateHistory",
			Handler:    _StateService_GetStateHistory_Handler,
		},
		{
			MethodName: "GetStateStatus",
			Handler:    _StateService_GetStateStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ApplyState",
			Handler:       _StateService_ApplyState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "keystone/core/v1/state.proto",
}
