package main

import (
	_ "embed"
	"fmt"
	"io"
	"os"
	"regexp"
	"strconv"
	"strings"

	yaml "go.yaml.in/yaml/v3"
)

//go:embed config/release-order.yaml
var releaseOrderYAML []byte

func loadReleaseOrder(version string) ([]string, error) {
	m := map[string][]string{}
	if err := yaml.Unmarshal(releaseOrderYAML, &m); err != nil {
		return nil, fmt.Errorf("parse config/release-order.yaml: %w", err)
	}
	return m[version], nil
}

func trackerTitle(version string) string { return version + " — release tracker" }

// orderEntries returns the version's backlog entries in tracker order: the
// release-order.yaml sequence first, then any remaining backlog entries in file
// order. It writes warnings about mismatches to w.
func orderEntries(entries []backlogEntry, order []string, w io.Writer) []backlogEntry {
	byTitle := make(map[string]backlogEntry, len(entries))
	for _, e := range entries {
		byTitle[e.Title] = e
	}
	used := make(map[string]bool, len(entries))
	var out []backlogEntry
	for _, title := range order {
		e, ok := byTitle[title]
		if !ok {
			fmt.Fprintf(w, "! release-order.yaml: %q matches no backlog entry for this version\n", title)
			continue
		}
		if used[title] {
			continue
		}
		used[title] = true
		out = append(out, e)
	}
	for _, e := range entries {
		if !used[e.Title] {
			if len(order) > 0 {
				fmt.Fprintf(w, "! %q is not in release-order.yaml; appended at end\n", e.Title)
			}
			out = append(out, e)
		}
	}
	return out
}

var checklistLineRe = regexp.MustCompile(`(?m)^- \[([ xX])\]\s+#(\d+)\b`)

// checkedNumbers extracts the set of issue numbers whose checkbox is ticked in
// an existing tracker body, so regeneration preserves completion state.
func checkedNumbers(body string) map[int64]bool {
	out := map[int64]bool{}
	for _, m := range checklistLineRe.FindAllStringSubmatch(body, -1) {
		if strings.EqualFold(m[1], "x") {
			if n, err := strconv.ParseInt(m[2], 10, 64); err == nil {
				out[n] = true
			}
		}
	}
	return out
}

type trackerItem struct {
	number  int64
	title   string
	checked bool
}

func buildTrackerBody(version string, items []trackerItem) string {
	var b strings.Builder
	fmt.Fprintf(&b, "Execution order for %s. \"Next item\" = first unchecked box.\n\n", version)
	b.WriteString("Reorder by editing `tools/trackerctl/config/release-order.yaml` (the canonical order — see `docs/project/ISSUE-TRACKING.md` §5) and re-running `trackerctl gen-tracker --version " + version + "`. Tick boxes here as work lands; the rest of this body is regenerated, so don't keep notes in it.\n\n")
	for _, it := range items {
		box := " "
		if it.checked {
			box = "x"
		}
		fmt.Fprintf(&b, "- [%s] #%d %s\n", box, it.number, it.title)
	}
	b.WriteString("\n_Generated by `tools/trackerctl gen-tracker`._")
	return b.String()
}

func genTracker(c *client, backlogPath, version string, apply bool, out io.Writer) error {
	if version == "" {
		return fmt.Errorf("gen-tracker requires --version (e.g. --version v1.1)")
	}

	f, err := os.Open(backlogPath)
	if err != nil {
		return err
	}
	defer f.Close()
	parsed, err := parseBacklog(f)
	if err != nil {
		return err
	}
	entries := selectEntries(parsed, []string{version})
	if len(entries) == 0 {
		return fmt.Errorf("no backlog entries for %q", version)
	}

	order, err := loadReleaseOrder(version)
	if err != nil {
		return err
	}
	ordered := orderEntries(entries, order, out)

	issues, err := c.listIssues()
	if err != nil {
		return err
	}
	numByTitle := make(map[string]int64, len(issues))
	var existing *issue
	want := trackerTitle(version)
	for i := range issues {
		if issues[i].Title == want {
			existing = &issues[i]
			continue
		}
		numByTitle[issues[i].Title] = issues[i].Number
	}

	prevChecked := map[int64]bool{}
	if existing != nil {
		prevChecked = checkedNumbers(existing.Body)
	}

	var items []trackerItem
	var missing int
	for _, e := range ordered {
		n, ok := numByTitle[e.Title]
		if !ok {
			fmt.Fprintf(out, "! no issue titled %q yet — run gen-issues --versions %s; omitted from tracker\n", e.Title, version)
			missing++
			continue
		}
		items = append(items, trackerItem{number: n, title: e.Title, checked: prevChecked[n]})
	}
	if len(items) == 0 {
		return fmt.Errorf("no leaf issues found for %s; run gen-issues --versions %s first", version, version)
	}
	body := buildTrackerBody(version, items)

	if existing != nil {
		fmt.Fprintf(out, "~ update tracker #%d %q (%d items, %d already checked)\n", existing.Number, want, len(items), len(prevChecked))
		if apply {
			if _, err := c.editIssueBody(existing.Number, body); err != nil {
				return err
			}
		}
	} else {
		var labels []int64
		if id, err := labelID(c, "kind/release-tracker"); err == nil {
			labels = append(labels, id)
		}
		var mid int64
		if id, err := milestoneID(c, version); err == nil {
			mid = id
		}
		fmt.Fprintf(out, "+ create tracker %q (%d items)\n", want, len(items))
		if apply {
			if _, err := c.createIssue(issuePayload{Title: want, Body: body, Labels: labels, Milestone: mid}); err != nil {
				return err
			}
		}
	}
	if missing > 0 {
		fmt.Fprintf(out, "tracker: %d backlog entries had no issue and were omitted\n", missing)
	}
	return nil
}

func labelID(c *client, name string) (int64, error) {
	labels, err := c.listLabels()
	if err != nil {
		return 0, err
	}
	for _, l := range labels {
		if l.Name == name {
			return l.ID, nil
		}
	}
	return 0, fmt.Errorf("label %q not found (run sync-labels)", name)
}

func milestoneID(c *client, title string) (int64, error) {
	miles, err := c.listMilestones()
	if err != nil {
		return 0, err
	}
	for _, m := range miles {
		if m.Title == title {
			return m.ID, nil
		}
	}
	return 0, fmt.Errorf("milestone %q not found (run sync-milestones)", title)
}
