// SPDX-License-Identifier: Apache-2.0

package statemgmt

// ModuleDoc is structured reference documentation for a stdlib state
// module. Modules expose it via the optional [Documented] interface;
// tools/gendocs/modules renders it into the docs-site "State Modules"
// reference. The reference is regenerated by `make docs-sync` and
// drift-gated by `make docs-sync-check`, so it stays in sync with the
// code — the Doc method lives in the module's own package alongside the
// logic it documents.
//
// The generator cross-checks each Doc against the live module: every
// [StateDoc] must correspond to a value in Module.ValidStates() and vice
// versa, so a module that adds or removes a state without updating its
// Doc fails the generator (and CI).
type ModuleDoc struct {
	// Summary is a one- or two-sentence description of what the module
	// manages. Rendered as the page intro.
	Summary string

	// Category groups the module in the reference index, e.g.
	// "System & core", "Storage", "Network (base)". Mirrors the
	// grouping in docs/project/STATE-SUPPORT-MATRIX.md and FEATURES.md §8.
	Category string

	// States documents each value Declaration.State may take. Must match
	// Module.ValidStates() exactly (the generator enforces this).
	States []StateDoc

	// Params documents the keys a Declaration carries for this module.
	Params []ParamDoc

	// Examples are runnable state-file snippets (Salt-style YAML).
	Examples []ModuleExample

	// Notes are caveats worth surfacing: distro/backend coverage,
	// support status, and out-of-scope items.
	Notes []string
}

// StateDoc documents one valid Declaration.State value.
type StateDoc struct {
	Name string
	Desc string
}

// ParamDoc documents one Declaration parameter.
type ParamDoc struct {
	Name     string // the YAML key, e.g. "content"
	Type     string // "string", "int", "bool", "list", "map", ...
	Required bool
	Default  string // rendered default value; "" if there is none
	Desc     string
}

// ModuleExample is a runnable state-file snippet for a module's
// reference page. YAML is a complete Salt-style declaration (a
// top-level `<module>:` block).
type ModuleExample struct {
	Title string
	Desc  string // optional one-line lead-in
	YAML  string
}

// Documented is implemented by stdlib modules that provide structured
// reference documentation. tools/gendocs/modules requires every
// registered module to implement it.
type Documented interface {
	Doc() ModuleDoc
}
