apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy all Keystone Core components
resources:
  - kscore-server
  - kscore-agent
  - kscore-registry
  - kscore-telemetry-gateway

commonLabels:
  app.kubernetes.io/part-of: keystone-core
  app.kubernetes.io/version: "0.10.0"
