apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy both server and agent
resources:
  - kscore-server
  - kscore-agent

commonLabels:
  app.kubernetes.io/part-of: keystone-core
  app.kubernetes.io/version: "0.10.0"
