// SPDX-License-Identifier: Apache-2.0

// gendocs/config builds docs/project/CONFIGURATION-REFERENCE.md by
// walking internal/config/*.go with go/ast, extracting every struct
// field that carries a `koanf:"..."` tag, and emitting a table per
// top-level config section.
//
// Per-field doc comment becomes the description; struct embedding
// resolves to dotted paths (e.g., `server.tls.enabled`); enum types
// (e.g., `config.Mode`, `config.NATSMode`) surface their underlying
// kind. Defaults aren't auto-extracted (defaultConfig() lives at
// runtime); the per-section preamble references the runtime-default
// source location.
//
// Usage:
//
//	go run ./tools/gendocs/config > docs/project/CONFIGURATION-REFERENCE.md
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
)

const header = `# Configuration reference

Generated by ` + "`make docs-sync`" + ` from ` + "`tools/gendocs/config`" + `.
Source of truth is the ` + "`koanf:\"...\"`" + ` struct tags + doc comments in
` + "`internal/config/*.go`" + `. Do not edit by hand — ` + "`make docs-sync`" + ` re-runs
the generator and ` + "`git diff`" + ` will catch drift.

Defaults are seeded by ` + "`internal/config/config.go::defaultConfig()`" + ` (and
the per-section ` + "`applyXxxDefaults`" + ` helpers). The reference below names
the type + the doc comment; the runtime default is in the seed.

## Top-level structure

The root config is a single YAML document. The ` + "`Config`" + ` struct
(` + "`internal/config/config.go`" + `) lists every top-level section; each
section has its own struct in the same package.

Sections covered below:

`

// koanfTag pulls the koanf field name out of a struct tag.
func koanfTag(tag *ast.BasicLit) string {
	if tag == nil {
		return ""
	}
	t := reflect.StructTag(strings.Trim(tag.Value, "`"))
	return t.Get("koanf")
}

// typeName renders an ast.Expr as the type string (e.g., "string",
// "[]string", "map[string]string", "*Foo", "Bar").
func typeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + typeName(t.X)
	case *ast.ArrayType:
		return "[]" + typeName(t.Elt)
	case *ast.MapType:
		return "map[" + typeName(t.Key) + "]" + typeName(t.Value)
	case *ast.SelectorExpr:
		return typeName(t.X) + "." + t.Sel.Name
	default:
		return fmt.Sprintf("%T", expr)
	}
}

// commentText strips leading "// " and joins multi-line doc comments
// into a single space-separated line. Returns "" for nil comments.
func commentText(doc *ast.CommentGroup) string {
	if doc == nil {
		return ""
	}
	var parts []string
	for _, c := range doc.List {
		line := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		line = strings.TrimSpace(strings.TrimPrefix(line, "/*"))
		line = strings.TrimSpace(strings.TrimSuffix(line, "*/"))
		if line == "" {
			continue
		}
		parts = append(parts, line)
	}
	out := strings.Join(parts, " ")
	// Markdown tables can't carry raw pipes; encode them.
	out = strings.ReplaceAll(out, "|", "\\|")
	// Wrap bare http(s):// URLs in angle brackets so markdownlint
	// MD034 (no-bare-urls) doesn't fire when a doc comment shows
	// an example URL.
	out = bareURLPattern.ReplaceAllString(out, "<$0>")
	// Collapse runs of whitespace.
	out = strings.Join(strings.Fields(out), " ")
	return out
}

// bareURLPattern matches http(s) URLs that aren't already wrapped
// in angle brackets or markdown link syntax.
var bareURLPattern = regexp.MustCompile(`https?://[A-Za-z0-9._:/?&=#@%~+-]+`)


// structField is one koanf-tagged field after AST parsing.
type structField struct {
	Name     string // Go name (e.g., "GRPCPort")
	KoanfKey string // YAML key (e.g., "grpcport")
	GoType   string // rendered type
	Doc      string
}

// structEntry is one struct type definition with its koanf-tagged fields.
type structEntry struct {
	Name   string
	Doc    string
	Fields []structField
}

func main() {
	configDir := "internal/config"
	fset := token.NewFileSet()
	entries, err := os.ReadDir(configDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gendocs/config: read internal/config/:", err)
		os.Exit(1)
	}

	structs := map[string]*structEntry{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		path := filepath.Join(configDir, e.Name())
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gendocs/config: parse %s: %v\n", path, err)
			os.Exit(1)
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts := spec.(*ast.TypeSpec)
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				entry := &structEntry{
					Name: ts.Name.Name,
					Doc:  commentText(gen.Doc),
				}
				for _, field := range st.Fields.List {
					key := koanfTag(field.Tag)
					if key == "" {
						continue
					}
					for _, fname := range field.Names {
						entry.Fields = append(entry.Fields, structField{
							Name:     fname.Name,
							KoanfKey: key,
							GoType:   typeName(field.Type),
							Doc:      commentText(field.Doc),
						})
					}
				}
				if len(entry.Fields) > 0 {
					structs[entry.Name] = entry
				}
			}
		}
	}

	root, ok := structs["Config"]
	if !ok {
		fmt.Fprintln(os.Stderr, "gendocs/config: no Config struct found in internal/config/")
		os.Exit(1)
	}

	out := &strings.Builder{}
	out.WriteString(header)
	for _, f := range root.Fields {
		// Only emit TOC entries for fields whose type is a known
		// struct (struct fields become their own section below);
		// scalar fields like `mode` don't have a target heading.
		if _, ok := structs[strings.TrimPrefix(strings.TrimPrefix(f.GoType, "*"), "[]")]; !ok {
			continue
		}
		fmt.Fprintf(out, "- [`%s`](#%s)\n", f.KoanfKey, anchor(f.KoanfKey))
	}
	out.WriteString("\n")

	// Walk each top-level section. Render its struct + every
	// transitively-referenced struct rooted under it (resolved by
	// type-name lookup in `structs`).
	rendered := map[string]bool{}
	for _, f := range root.Fields {
		renderSection(out, f.KoanfKey, f.GoType, structs, rendered)
	}

	// Trim trailing blank lines — markdownlint's MD012 fires on
	// double-newline-at-EOF.
	body := strings.TrimRight(out.String(), "\n") + "\n"
	if _, err := os.Stdout.WriteString(body); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs/config: write:", err)
		os.Exit(1)
	}
}

// renderSection emits a section for the koanf key + every sub-struct
// it transitively references. Skips already-rendered structs.
func renderSection(out *strings.Builder, prefix, goType string, structs map[string]*structEntry, rendered map[string]bool) {
	entry, ok := structs[goType]
	if !ok {
		// Not a known struct (probably a built-in or enum).
		return
	}
	if rendered[goType] {
		return
	}
	rendered[goType] = true

	fmt.Fprintf(out, "## `%s`\n\n", prefix)
	if entry.Doc != "" {
		out.WriteString(entry.Doc)
		out.WriteString("\n\n")
	}
	out.WriteString("| Key | Type | Description |\n")
	out.WriteString("|-----|------|-------------|\n")
	// sort by Go field name for stable output
	fields := append([]structField{}, entry.Fields...)
	sort.Slice(fields, func(i, j int) bool { return fields[i].KoanfKey < fields[j].KoanfKey })
	for _, f := range fields {
		key := prefix + "." + f.KoanfKey
		fmt.Fprintf(out, "| `%s` | `%s` | %s |\n", key, f.GoType, f.Doc)
	}
	out.WriteString("\n")
	// Recurse into sub-structs.
	for _, f := range fields {
		baseType := strings.TrimPrefix(f.GoType, "*")
		baseType = strings.TrimPrefix(baseType, "[]")
		if _, ok := structs[baseType]; ok {
			renderSection(out, prefix+"."+f.KoanfKey, baseType, structs, rendered)
		}
	}
}

// anchor builds a github-style markdown anchor from a heading.
func anchor(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '-' || r == '.':
			b.WriteRune('-')
		default:
		}
	}
	return b.String()
}
